# -*- coding: UTF-8 -*-
# source: https://en.wikipedia.org/wiki/List_of_country_calling_codes
# license: https://en.wikipedia.org/wiki/Wikipedia:Text_of_Creative_Commons_Attribution-ShareAlike_3.0_Unported_License

WIKIP_MSISDN = \
{ '1': [ ('AG', 'Antigua and Barbuda', 'https://en.wikipedia.org/wiki/antigua_and_barbuda'),
         ('AI', 'Anguilla', 'https://en.wikipedia.org/wiki/anguilla'),
         ('AS', 'American Samoa', 'https://en.wikipedia.org/wiki/american_samoa'),
         ('BB', 'Barbados', 'https://en.wikipedia.org/wiki/barbados'),
         ('BM', 'Bermuda', 'https://en.wikipedia.org/wiki/bermuda'),
         ('BS', 'The Bahamas', 'https://en.wikipedia.org/wiki/the_bahamas'),
         ('CA', 'Canada', 'https://en.wikipedia.org/wiki/canada'),
         ('DM', 'Dominica', 'https://en.wikipedia.org/wiki/dominica'),
         ('DO', 'Dominican Republic', 'https://en.wikipedia.org/wiki/dominican_republic'),
         ('GD', 'Grenada', 'https://en.wikipedia.org/wiki/grenada'),
         ('GU', 'Guam', 'https://en.wikipedia.org/wiki/guam'),
         ('JM', 'Jamaica', 'https://en.wikipedia.org/wiki/jamaica'),
         ('KN', 'St. Kitts and Nevis', 'https://en.wikipedia.org/wiki/st._kitts_and_nevis'),
         ('KY', 'Cayman Islands', 'https://en.wikipedia.org/wiki/cayman_islands'),
         ('LC', 'St. Lucia', 'https://en.wikipedia.org/wiki/st._lucia'),
         ('MP', 'Northern Mariana Islands', 'https://en.wikipedia.org/wiki/northern_mariana_islands'),
         ('MS', 'Montserrat', 'https://en.wikipedia.org/wiki/montserrat'),
         ('PR', 'Puerto Rico', 'https://en.wikipedia.org/wiki/puerto_rico'),
         ('SX', 'Sint Maarten', 'https://en.wikipedia.org/wiki/sint_maarten'),
         ('TC', 'Turks and Caicos Islands', 'https://en.wikipedia.org/wiki/turks_and_caicos_islands'),
         ('TT', 'Trinidad and Tobago', 'https://en.wikipedia.org/wiki/trinidad_and_tobago'),
         ( 'UM',
           'United States Minor Outlying Islands',
           'https://en.wikipedia.org/wiki/united_states_minor_outlying_islands'),
         ('US', 'United States', 'https://en.wikipedia.org/wiki/united_states'),
         ('VC', 'St. Vincent and the Grenadines', 'https://en.wikipedia.org/wiki/st._vincent_and_the_grenadines'),
         ('VG', 'British Virgin Islands', 'https://en.wikipedia.org/wiki/british_virgin_islands'),
         ('VI', 'United States Virgin Islands', 'https://en.wikipedia.org/wiki/united_states_virgin_islands')],
  '1242': [('BS', 'The Bahamas', 'https://en.wikipedia.org/wiki/the_bahamas')],
  '1246': [('BB', 'Barbados', 'https://en.wikipedia.org/wiki/barbados')],
  '1264': [('AI', 'Anguilla', 'https://en.wikipedia.org/wiki/anguilla')],
  '1268': [('AG', 'Antigua and Barbuda', 'https://en.wikipedia.org/wiki/antigua_and_barbuda')],
  '1284': [('VG', 'British Virgin Islands', 'https://en.wikipedia.org/wiki/british_virgin_islands')],
  '1340': [('VI', 'United States Virgin Islands', 'https://en.wikipedia.org/wiki/united_states_virgin_islands')],
  '1345': [('KY', 'Cayman Islands', 'https://en.wikipedia.org/wiki/cayman_islands')],
  '1441': [('BM', 'Bermuda', 'https://en.wikipedia.org/wiki/bermuda')],
  '1473': [('GD', 'Grenada', 'https://en.wikipedia.org/wiki/grenada')],
  '1649': [('TC', 'Turks and Caicos Islands', 'https://en.wikipedia.org/wiki/turks_and_caicos_islands')],
  '1658': [('JM', 'Jamaica', 'https://en.wikipedia.org/wiki/jamaica')],
  '1664': [('MS', 'Montserrat', 'https://en.wikipedia.org/wiki/montserrat')],
  '1670': [('MP', 'Northern Mariana Islands', 'https://en.wikipedia.org/wiki/northern_mariana_islands')],
  '1671': [('GU', 'Guam', 'https://en.wikipedia.org/wiki/guam')],
  '1684': [('AS', 'American Samoa', 'https://en.wikipedia.org/wiki/american_samoa')],
  '1721': [('SX', 'Sint Maarten', 'https://en.wikipedia.org/wiki/sint_maarten')],
  '1758': [('LC', 'St. Lucia', 'https://en.wikipedia.org/wiki/st._lucia')],
  '1767': [('DM', 'Dominica', 'https://en.wikipedia.org/wiki/dominica')],
  '1784': [('VC', 'St. Vincent and the Grenadines', 'https://en.wikipedia.org/wiki/st._vincent_and_the_grenadines')],
  '1787': [('PR', 'Puerto Rico', 'https://en.wikipedia.org/wiki/puerto_rico')],
  '1809': [('DO', 'Dominican Republic', 'https://en.wikipedia.org/wiki/dominican_republic')],
  '1829': [('DO', 'Dominican Republic', 'https://en.wikipedia.org/wiki/dominican_republic')],
  '1849': [('DO', 'Dominican Republic', 'https://en.wikipedia.org/wiki/dominican_republic')],
  '1868': [('TT', 'Trinidad and Tobago', 'https://en.wikipedia.org/wiki/trinidad_and_tobago')],
  '1869': [('KN', 'St. Kitts and Nevis', 'https://en.wikipedia.org/wiki/st._kitts_and_nevis')],
  '1876': [('JM', 'Jamaica', 'https://en.wikipedia.org/wiki/jamaica')],
  '1939': [('PR', 'Puerto Rico', 'https://en.wikipedia.org/wiki/puerto_rico')],
  '20': [('EG', 'Egypt', 'https://en.wikipedia.org/wiki/egypt')],
  '211': [('SS', 'South Sudan', 'https://en.wikipedia.org/wiki/south_sudan')],
  '212': [ ('EH', 'Western Sahara', 'https://en.wikipedia.org/wiki/western_sahara'),
           ('MA', 'Morocco', 'https://en.wikipedia.org/wiki/morocco')],
  '213': [('DZ', 'Algeria', 'https://en.wikipedia.org/wiki/algeria')],
  '216': [('TN', 'Tunisia', 'https://en.wikipedia.org/wiki/tunisia')],
  '218': [('LY', 'Libya', 'https://en.wikipedia.org/wiki/libya')],
  '220': [('GM', 'The Gambia', 'https://en.wikipedia.org/wiki/the_gambia')],
  '221': [('SN', 'Senegal', 'https://en.wikipedia.org/wiki/senegal')],
  '222': [('MR', 'Mauritania', 'https://en.wikipedia.org/wiki/mauritania')],
  '223': [('ML', 'Mali', 'https://en.wikipedia.org/wiki/mali')],
  '224': [('GN', 'Guinea', 'https://en.wikipedia.org/wiki/guinea')],
  '225': [('CI', 'Ivory Coast', 'https://en.wikipedia.org/wiki/ivory_coast')],
  '226': [('BF', 'Burkina Faso', 'https://en.wikipedia.org/wiki/burkina_faso')],
  '227': [('NE', 'Niger', 'https://en.wikipedia.org/wiki/niger')],
  '228': [('TG', 'Togo', 'https://en.wikipedia.org/wiki/togo')],
  '229': [('BJ', 'Benin', 'https://en.wikipedia.org/wiki/benin')],
  '230': [('MU', 'Mauritius', 'https://en.wikipedia.org/wiki/mauritius')],
  '231': [('LR', 'Liberia', 'https://en.wikipedia.org/wiki/liberia')],
  '232': [('SL', 'Sierra Leone', 'https://en.wikipedia.org/wiki/sierra_leone')],
  '233': [('GH', 'Ghana', 'https://en.wikipedia.org/wiki/ghana')],
  '234': [('NG', 'Nigeria', 'https://en.wikipedia.org/wiki/nigeria')],
  '235': [('TD', 'Chad', 'https://en.wikipedia.org/wiki/chad')],
  '236': [('CF', 'Central African Republic', 'https://en.wikipedia.org/wiki/central_african_republic')],
  '237': [('CM', 'Cameroon', 'https://en.wikipedia.org/wiki/cameroon')],
  '238': [('CV', 'Cape Verde', 'https://en.wikipedia.org/wiki/cape_verde')],
  '239': [('ST', 'São Tomé and Príncipe', 'https://en.wikipedia.org/wiki/s%c3%a3o_tom%c3%a9_and_pr%c3%adncipe')],
  '240': [('GQ', 'Equatorial Guinea', 'https://en.wikipedia.org/wiki/equatorial_guinea')],
  '241': [('GA', 'Gabon', 'https://en.wikipedia.org/wiki/gabon')],
  '242': [('CG', 'Republic of Congo', 'https://en.wikipedia.org/wiki/republic_of_congo')],
  '243': [('CD', 'Democratic Republic of the Congo', 'https://en.wikipedia.org/wiki/democratic_republic_of_the_congo')],
  '244': [('AO', 'Angola', 'https://en.wikipedia.org/wiki/angola')],
  '245': [('GW', 'Guinea-Bissau', 'https://en.wikipedia.org/wiki/guinea-bissau')],
  '246': [('IO', 'British Indian Ocean Territory', 'https://en.wikipedia.org/wiki/british_indian_ocean_territory')],
  '247': [('AC', 'Ascension Island', 'https://en.wikipedia.org/wiki/ascension_island')],
  '248': [('SC', 'Seychelles', 'https://en.wikipedia.org/wiki/seychelles')],
  '249': [('SD', 'Sudan', 'https://en.wikipedia.org/wiki/sudan')],
  '250': [('RW', 'Rwanda', 'https://en.wikipedia.org/wiki/rwanda')],
  '251': [('ET', 'Ethiopia', 'https://en.wikipedia.org/wiki/ethiopia')],
  '252': [('SO', 'Somalia', 'https://en.wikipedia.org/wiki/somalia')],
  '253': [('DJ', 'Djibouti', 'https://en.wikipedia.org/wiki/djibouti')],
  '254': [('KE', 'Kenya', 'https://en.wikipedia.org/wiki/kenya')],
  '255': [('TZ', 'Tanzania', 'https://en.wikipedia.org/wiki/tanzania')],
  '256': [('UG', 'Uganda', 'https://en.wikipedia.org/wiki/uganda')],
  '257': [('BI', 'Burundi', 'https://en.wikipedia.org/wiki/burundi')],
  '258': [('MZ', 'Mozambique', 'https://en.wikipedia.org/wiki/mozambique')],
  '260': [('ZM', 'Zambia', 'https://en.wikipedia.org/wiki/zambia')],
  '261': [('MG', 'Madagascar', 'https://en.wikipedia.org/wiki/madagascar')],
  '262': [ ('RE', 'Réunion', 'https://en.wikipedia.org/wiki/r%c3%a9union'),
           ( 'TF',
             'French Southern and Antarctic Lands',
             'https://en.wikipedia.org/wiki/french_southern_and_antarctic_lands'),
           ('YT', 'Mayotte', 'https://en.wikipedia.org/wiki/mayotte')],
  '263': [('ZW', 'Zimbabwe', 'https://en.wikipedia.org/wiki/zimbabwe')],
  '264': [('NA', 'Namibia', 'https://en.wikipedia.org/wiki/namibia')],
  '265': [('MW', 'Malawi', 'https://en.wikipedia.org/wiki/malawi')],
  '266': [('LS', 'Lesotho', 'https://en.wikipedia.org/wiki/lesotho')],
  '267': [('BW', 'Botswana', 'https://en.wikipedia.org/wiki/botswana')],
  '268': [('SZ', 'Swaziland', 'https://en.wikipedia.org/wiki/swaziland')],
  '269': [('KM', 'Comoros', 'https://en.wikipedia.org/wiki/comoros')],
  '27': [('ZA', 'South Africa', 'https://en.wikipedia.org/wiki/south_africa')],
  '290': [ ('SH', 'Saint Helena', 'https://en.wikipedia.org/wiki/saint_helena'),
           ('TA', 'Tristan da Cunha', 'https://en.wikipedia.org/wiki/tristan_da_cunha')],
  '291': [('ER', 'Eritrea', 'https://en.wikipedia.org/wiki/eritrea')],
  '297': [('AW', 'Aruba', 'https://en.wikipedia.org/wiki/aruba')],
  '298': [('FO', 'Faroe Islands', 'https://en.wikipedia.org/wiki/faroe_islands')],
  '299': [('GL', 'Greenland', 'https://en.wikipedia.org/wiki/greenland')],
  '30': [('GR', 'Greece', 'https://en.wikipedia.org/wiki/greece')],
  '31': [('NL', 'Netherlands', 'https://en.wikipedia.org/wiki/netherlands')],
  '32': [('BE', 'Belgium', 'https://en.wikipedia.org/wiki/belgium')],
  '33': [('FR', 'France', 'https://en.wikipedia.org/wiki/france')],
  '34': [('ES', 'Spain', 'https://en.wikipedia.org/wiki/spain')],
  '350': [('GI', 'Gibraltar', 'https://en.wikipedia.org/wiki/gibraltar')],
  '351': [('PT', 'Portugal', 'https://en.wikipedia.org/wiki/portugal')],
  '352': [('LU', 'Luxembourg', 'https://en.wikipedia.org/wiki/luxembourg')],
  '353': [('IE', 'Republic of Ireland', 'https://en.wikipedia.org/wiki/republic_of_ireland')],
  '354': [('IS', 'Iceland', 'https://en.wikipedia.org/wiki/iceland')],
  '355': [('AL', 'Albania', 'https://en.wikipedia.org/wiki/albania')],
  '356': [('MT', 'Malta', 'https://en.wikipedia.org/wiki/malta')],
  '357': [('CY', 'Cyprus', 'https://en.wikipedia.org/wiki/cyprus')],
  '358': [ ('AX', 'Åland Islands', 'https://en.wikipedia.org/wiki/%c3%85land_islands'),
           ('FI', 'Finland', 'https://en.wikipedia.org/wiki/finland')],
  '359': [('BG', 'Bulgaria', 'https://en.wikipedia.org/wiki/bulgaria')],
  '36': [('HU', 'Hungary', 'https://en.wikipedia.org/wiki/hungary')],
  '370': [('LT', 'Lithuania', 'https://en.wikipedia.org/wiki/lithuania')],
  '371': [('LV', 'Latvia', 'https://en.wikipedia.org/wiki/latvia')],
  '372': [('EE', 'Estonia', 'https://en.wikipedia.org/wiki/estonia')],
  '373': [('MD', 'Moldova', 'https://en.wikipedia.org/wiki/moldova')],
  '374': [ ('AM', 'Armenia', 'https://en.wikipedia.org/wiki/armenia'),
           ('QN', 'Nagorno-Karabakh', 'https://en.wikipedia.org/wiki/nagorno-karabakh')],
  '375': [('BY', 'Belarus', 'https://en.wikipedia.org/wiki/belarus')],
  '376': [('AD', 'Andorra', 'https://en.wikipedia.org/wiki/andorra')],
  '377': [('MC', 'Monaco', 'https://en.wikipedia.org/wiki/monaco')],
  '378': [('SM', 'San Marino', 'https://en.wikipedia.org/wiki/san_marino')],
  '379': [('VA', 'Vatican City', 'https://en.wikipedia.org/wiki/vatican_city')],
  '380': [('UA', 'Ukraine', 'https://en.wikipedia.org/wiki/ukraine')],
  '381': [('RS', 'Serbia', 'https://en.wikipedia.org/wiki/serbia')],
  '382': [('ME', 'Montenegro', 'https://en.wikipedia.org/wiki/montenegro')],
  '383': [('XK', 'Kosovo', 'https://en.wikipedia.org/wiki/kosovo')],
  '385': [('HR', 'Croatia', 'https://en.wikipedia.org/wiki/croatia')],
  '386': [('SI', 'Slovenia', 'https://en.wikipedia.org/wiki/slovenia')],
  '387': [('BA', 'Bosnia and Herzegovina', 'https://en.wikipedia.org/wiki/bosnia_and_herzegovina')],
  '388': [ ( 'EU',
             'European Telephony Numbering Space',
             'https://en.wikipedia.org/wiki/european_telephony_numbering_space')],
  '389': [('MK', 'North Macedonia', 'https://en.wikipedia.org/wiki/north_macedonia')],
  '39': [ ('IT', 'Italy', 'https://en.wikipedia.org/wiki/italy'),
          ('VA', 'Vatican City', 'https://en.wikipedia.org/wiki/vatican_city')],
  '40': [('RO', 'Romania', 'https://en.wikipedia.org/wiki/romania')],
  '41': [('CH', 'Switzerland', 'https://en.wikipedia.org/wiki/switzerland')],
  '420': [('CZ', 'Czech Republic', 'https://en.wikipedia.org/wiki/czech_republic')],
  '421': [('SK', 'Slovakia', 'https://en.wikipedia.org/wiki/slovakia')],
  '423': [('LI', 'Liechtenstein', 'https://en.wikipedia.org/wiki/liechtenstein')],
  '43': [('AT', 'Austria', 'https://en.wikipedia.org/wiki/austria')],
  '44': [ ('GG', 'Guernsey', 'https://en.wikipedia.org/wiki/guernsey'),
          ('IM', 'Isle of Man', 'https://en.wikipedia.org/wiki/isle_of_man'),
          ('JE', 'Jersey', 'https://en.wikipedia.org/wiki/jersey'),
          ('UK', 'United Kingdom', 'https://en.wikipedia.org/wiki/united_kingdom')],
  '45': [('DK', 'Denmark', 'https://en.wikipedia.org/wiki/denmark')],
  '46': [('SE', 'Sweden', 'https://en.wikipedia.org/wiki/sweden')],
  '47': [ ('BV', 'Bouvet Island', 'https://en.wikipedia.org/wiki/bouvet_island'),
          ('NO', 'Norway', 'https://en.wikipedia.org/wiki/norway'),
          ('SJ', 'Svalbard and Jan Mayen', 'https://en.wikipedia.org/wiki/svalbard_and_jan_mayen')],
  '48': [('PL', 'Poland', 'https://en.wikipedia.org/wiki/poland')],
  '49': [('DE', 'Germany', 'https://en.wikipedia.org/wiki/germany')],
  '500': [ ('FK', 'Falkland Islands', 'https://en.wikipedia.org/wiki/falkland_islands'),
           ( 'GS',
             'South Georgia and the South Sandwich Islands',
             'https://en.wikipedia.org/wiki/south_georgia_and_the_south_sandwich_islands')],
  '501': [('BZ', 'Belize', 'https://en.wikipedia.org/wiki/belize')],
  '502': [('GT', 'Guatemala', 'https://en.wikipedia.org/wiki/guatemala')],
  '503': [('SV', 'El Salvador', 'https://en.wikipedia.org/wiki/el_salvador')],
  '504': [('HN', 'Honduras', 'https://en.wikipedia.org/wiki/honduras')],
  '505': [('NI', 'Nicaragua', 'https://en.wikipedia.org/wiki/nicaragua')],
  '506': [('CR', 'Costa Rica', 'https://en.wikipedia.org/wiki/costa_rica')],
  '507': [('PA', 'Panama', 'https://en.wikipedia.org/wiki/panama')],
  '508': [('PM', 'St. Pierre and Miquelon', 'https://en.wikipedia.org/wiki/st._pierre_and_miquelon')],
  '509': [('HT', 'Haiti', 'https://en.wikipedia.org/wiki/haiti')],
  '51': [('PE', 'Peru', 'https://en.wikipedia.org/wiki/peru')],
  '52': [('MX', 'Mexico', 'https://en.wikipedia.org/wiki/mexico')],
  '53': [('CU', 'Cuba', 'https://en.wikipedia.org/wiki/cuba')],
  '54': [('AR', 'Argentina', 'https://en.wikipedia.org/wiki/argentina')],
  '55': [('BR', 'Brazil', 'https://en.wikipedia.org/wiki/brazil')],
  '56': [('CL', 'Chile', 'https://en.wikipedia.org/wiki/chile')],
  '57': [('CO', 'Colombia', 'https://en.wikipedia.org/wiki/colombia')],
  '58': [('VE', 'Venezuela', 'https://en.wikipedia.org/wiki/venezuela')],
  '590': [ ('BL', 'Saint Barthélemy', 'https://en.wikipedia.org/wiki/saint_barth%c3%a9lemy'),
           ('GP', 'Guadeloupe', 'https://en.wikipedia.org/wiki/guadeloupe'),
           ('MF', 'Saint Martin', 'https://en.wikipedia.org/wiki/saint_martin')],
  '591': [('BO', 'Bolivia', 'https://en.wikipedia.org/wiki/bolivia')],
  '592': [('GY', 'Guyana', 'https://en.wikipedia.org/wiki/guyana')],
  '593': [('EC', 'Ecuador', 'https://en.wikipedia.org/wiki/ecuador')],
  '594': [('GF', 'French Guiana', 'https://en.wikipedia.org/wiki/french_guiana')],
  '595': [('PY', 'Paraguay', 'https://en.wikipedia.org/wiki/paraguay')],
  '596': [('MQ', 'Martinique', 'https://en.wikipedia.org/wiki/martinique')],
  '597': [('SR', 'Suriname', 'https://en.wikipedia.org/wiki/suriname')],
  '598': [('UY', 'Uruguay', 'https://en.wikipedia.org/wiki/uruguay')],
  '599': [ ('BQ', 'Caribbean Netherlands', 'https://en.wikipedia.org/wiki/caribbean_netherlands'),
           ('CW', 'Curaçao', 'https://en.wikipedia.org/wiki/cura%c3%a7ao')],
  '60': [('MY', 'Malaysia', 'https://en.wikipedia.org/wiki/malaysia')],
  '61': [ ('AU', 'Australia', 'https://en.wikipedia.org/wiki/australia'),
          ('CC', 'Cocos Islands', 'https://en.wikipedia.org/wiki/cocos_islands'),
          ('CX', 'Christmas Island', 'https://en.wikipedia.org/wiki/christmas_island')],
  '62': [('ID', 'Indonesia', 'https://en.wikipedia.org/wiki/indonesia')],
  '63': [('PH', 'Philippines', 'https://en.wikipedia.org/wiki/philippines')],
  '64': [ ('NZ', 'New Zealand', 'https://en.wikipedia.org/wiki/new_zealand'),
          ('PN', 'Pitcairn Islands', 'https://en.wikipedia.org/wiki/pitcairn_islands')],
  '65': [('SG', 'Singapore', 'https://en.wikipedia.org/wiki/singapore')],
  '66': [('TH', 'Thailand', 'https://en.wikipedia.org/wiki/thailand')],
  '670': [('TL', 'East Timor', 'https://en.wikipedia.org/wiki/east_timor')],
  '672': [ ('AQ', 'Australian Antarctic Territory', 'https://en.wikipedia.org/wiki/australian_antarctic_territory'),
           ( 'HM',
             'Heard Island and McDonald Islands',
             'https://en.wikipedia.org/wiki/heard_island_and_mcdonald_islands'),
           ('NF', 'Norfolk Island', 'https://en.wikipedia.org/wiki/norfolk_island')],
  '673': [('BN', 'Brunei Darussalam', 'https://en.wikipedia.org/wiki/brunei_darussalam')],
  '674': [('NR', 'Nauru', 'https://en.wikipedia.org/wiki/nauru')],
  '675': [('PG', 'Papua New Guinea', 'https://en.wikipedia.org/wiki/papua_new_guinea')],
  '676': [('TO', 'Tonga', 'https://en.wikipedia.org/wiki/tonga')],
  '677': [('SB', 'Solomon Islands', 'https://en.wikipedia.org/wiki/solomon_islands')],
  '678': [('VU', 'Vanuatu', 'https://en.wikipedia.org/wiki/vanuatu')],
  '679': [('FJ', 'Fiji', 'https://en.wikipedia.org/wiki/fiji')],
  '680': [('PW', 'Palau', 'https://en.wikipedia.org/wiki/palau')],
  '681': [('WF', 'Wallis and Futuna', 'https://en.wikipedia.org/wiki/wallis_and_futuna')],
  '682': [('CK', 'Cook Islands', 'https://en.wikipedia.org/wiki/cook_islands')],
  '683': [('NU', 'Niue', 'https://en.wikipedia.org/wiki/niue')],
  '685': [('WS', 'Samoa', 'https://en.wikipedia.org/wiki/samoa')],
  '686': [('KI', 'Kiribati', 'https://en.wikipedia.org/wiki/kiribati')],
  '687': [('NC', 'New Caledonia', 'https://en.wikipedia.org/wiki/new_caledonia')],
  '688': [('TV', 'Tuvalu', 'https://en.wikipedia.org/wiki/tuvalu')],
  '689': [('PF', 'French Polynesia', 'https://en.wikipedia.org/wiki/french_polynesia')],
  '690': [('TK', 'Tokelau', 'https://en.wikipedia.org/wiki/tokelau')],
  '691': [('FM', 'Federated States of Micronesia', 'https://en.wikipedia.org/wiki/federated_states_of_micronesia')],
  '692': [('MH', 'Marshall Islands', 'https://en.wikipedia.org/wiki/marshall_islands')],
  '7': [ ('KZ', 'Kazakhstan', 'https://en.wikipedia.org/wiki/kazakhstan'),
         ('RU', 'Russia', 'https://en.wikipedia.org/wiki/russia')],
  '73': [('RU', 'Russia', 'https://en.wikipedia.org/wiki/russia')],
  '74': [('RU', 'Russia', 'https://en.wikipedia.org/wiki/russia')],
  '76': [('KZ', 'Kazakhstan', 'https://en.wikipedia.org/wiki/kazakhstan')],
  '77': [('KZ', 'Kazakhstan', 'https://en.wikipedia.org/wiki/kazakhstan')],
  '78': [('RU', 'Russia', 'https://en.wikipedia.org/wiki/russia')],
  '79': [('RU', 'Russia', 'https://en.wikipedia.org/wiki/russia')],
  '800': [ ( 'XT',
             'Universal international freephone number',
             'https://en.wikipedia.org/wiki/universal_international_freephone_number')],
  '808': [('XS', 'Shared Cost Service', 'https://en.wikipedia.org/wiki/shared_cost_service')],
  '81': [('JP', 'Japan', 'https://en.wikipedia.org/wiki/japan')],
  '82': [('KR', 'South Korea', 'https://en.wikipedia.org/wiki/south_korea')],
  '84': [('VN', 'Vietnam', 'https://en.wikipedia.org/wiki/vietnam')],
  '850': [('KP', 'North Korea', 'https://en.wikipedia.org/wiki/north_korea')],
  '852': [('HK', 'Hong Kong', 'https://en.wikipedia.org/wiki/hong_kong')],
  '853': [('MO', 'Macau', 'https://en.wikipedia.org/wiki/macau')],
  '855': [('KH', 'Cambodia', 'https://en.wikipedia.org/wiki/cambodia')],
  '856': [('LA', 'Laos', 'https://en.wikipedia.org/wiki/laos')],
  '86': [('CN', 'China', 'https://en.wikipedia.org/wiki/china')],
  '878': [ ( 'XP',
             'Universal Personal Telecommunications',
             'https://en.wikipedia.org/wiki/universal_personal_telecommunications')],
  '880': [('BD', 'Bangladesh', 'https://en.wikipedia.org/wiki/bangladesh')],
  '881': [('XG', 'Global Mobile Satellite System', 'https://en.wikipedia.org/wiki/global_mobile_satellite_system')],
  '882': [ ( 'XV',
             'International Networks (country code)',
             'https://en.wikipedia.org/wiki/international_networks_(country_code)')],
  '883': [ ( 'XV',
             'International Networks (country code)',
             'https://en.wikipedia.org/wiki/international_networks_(country_code)')],
  '886': [('TW', 'Taiwan', 'https://en.wikipedia.org/wiki/taiwan')],
  '888': [('XD', 'OCHA', 'https://en.wikipedia.org/wiki/ocha')],
  '90': [ ('CT', 'Northern Cyprus', 'https://en.wikipedia.org/wiki/northern_cyprus'),
          ('TR', 'Turkey', 'https://en.wikipedia.org/wiki/turkey')],
  '91': [('IN', 'India', 'https://en.wikipedia.org/wiki/india')],
  '92': [('PK', 'Pakistan', 'https://en.wikipedia.org/wiki/pakistan')],
  '93': [('AF', 'Afghanistan', 'https://en.wikipedia.org/wiki/afghanistan')],
  '94': [('LK', 'Sri Lanka', 'https://en.wikipedia.org/wiki/sri_lanka')],
  '95': [('MM', 'Myanmar', 'https://en.wikipedia.org/wiki/myanmar')],
  '960': [('MV', 'Maldives', 'https://en.wikipedia.org/wiki/maldives')],
  '961': [('LB', 'Lebanon', 'https://en.wikipedia.org/wiki/lebanon')],
  '962': [('JO', 'Jordan', 'https://en.wikipedia.org/wiki/jordan')],
  '963': [('SY', 'Syria', 'https://en.wikipedia.org/wiki/syria')],
  '964': [('IQ', 'Iraq', 'https://en.wikipedia.org/wiki/iraq')],
  '965': [('KW', 'Kuwait', 'https://en.wikipedia.org/wiki/kuwait')],
  '966': [('SA', 'Saudi Arabia', 'https://en.wikipedia.org/wiki/saudi_arabia')],
  '967': [('YE', 'Yemen', 'https://en.wikipedia.org/wiki/yemen')],
  '968': [('OM', 'Oman', 'https://en.wikipedia.org/wiki/oman')],
  '970': [('PS', 'State of Palestine', 'https://en.wikipedia.org/wiki/state_of_palestine')],
  '971': [('AE', 'United Arab Emirates', 'https://en.wikipedia.org/wiki/united_arab_emirates')],
  '972': [('IL', 'Israel', 'https://en.wikipedia.org/wiki/israel')],
  '973': [('BH', 'Bahrain', 'https://en.wikipedia.org/wiki/bahrain')],
  '974': [('QA', 'Qatar', 'https://en.wikipedia.org/wiki/qatar')],
  '975': [('BT', 'Bhutan', 'https://en.wikipedia.org/wiki/bhutan')],
  '976': [('MN', 'Mongolia', 'https://en.wikipedia.org/wiki/mongolia')],
  '977': [('NP', 'Nepal', 'https://en.wikipedia.org/wiki/nepal')],
  '979': [ ( 'XR',
             'International premium rate service',
             'https://en.wikipedia.org/wiki/international_premium_rate_service')],
  '98': [('IR', 'Iran', 'https://en.wikipedia.org/wiki/iran')],
  '991': [('XC', 'ITPCS', 'https://en.wikipedia.org/wiki/itpcs')],
  '992': [('TJ', 'Tajikistan', 'https://en.wikipedia.org/wiki/tajikistan')],
  '993': [('TM', 'Turkmenistan', 'https://en.wikipedia.org/wiki/turkmenistan')],
  '994': [('AZ', 'Azerbaijan', 'https://en.wikipedia.org/wiki/azerbaijan')],
  '995': [('GE', 'Georgia (country)', 'https://en.wikipedia.org/wiki/georgia_(country)')],
  '996': [('KG', 'Kyrgyzstan', 'https://en.wikipedia.org/wiki/kyrgyzstan')],
  '998': [('UZ', 'Uzbekistan', 'https://en.wikipedia.org/wiki/uzbekistan')]}
