WIKIP_BORDERS = \
[ { 'border_len_km': 5529,
    'border_len_mi': 3436,
    'country_name': 'Afghanistan',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Afghanistan',
    'neigh': [ ('China', 'https://en.wikipedia.org/wiki/China'),
               ('Iran', 'https://en.wikipedia.org/wiki/Iran'),
               ('Pakistan', 'https://en.wikipedia.org/wiki/Pakistan'),
               ('Tajikistan', 'https://en.wikipedia.org/wiki/Tajikistan'),
               ('Turkmenistan', 'https://en.wikipedia.org/wiki/Turkmenistan'),
               ('Uzbekistan', 'https://en.wikipedia.org/wiki/Uzbekistan')],
    'neigh_num': 6},
  { 'border_len_km': 720,
    'border_len_mi': 450,
    'country_name': 'Albania',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Albania',
    'neigh': [ ('Greece', 'https://en.wikipedia.org/wiki/Greece'),
               ('Kosovo', 'https://en.wikipedia.org/wiki/Kosovo'),
               ('Montenegro', 'https://en.wikipedia.org/wiki/Montenegro'),
               ('North Macedonia', 'https://en.wikipedia.org/wiki/North_Macedonia')],
    'neigh_num': 4},
  { 'border_len_km': 6470,
    'border_len_mi': 4020,
    'country_name': 'Algeria',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Algeria',
    'neigh': [ ('Libya', 'https://en.wikipedia.org/wiki/Libya'),
               ('Mali', 'https://en.wikipedia.org/wiki/Mali'),
               ('Mauritania', 'https://en.wikipedia.org/wiki/Mauritania'),
               ('Morocco', 'https://en.wikipedia.org/wiki/Morocco'),
               ('Niger', 'https://en.wikipedia.org/wiki/Niger'),
               ('Tunisia', 'https://en.wikipedia.org/wiki/Tunisia'),
               ('Western Sahara', 'https://en.wikipedia.org/wiki/Western_Sahara')],
    'neigh_num': 7},
  { 'border_len_km': 120,
    'border_len_mi': 75,
    'country_name': 'Andorra',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Andorra',
    'neigh': [('France', 'https://en.wikipedia.org/wiki/France'), ('Spain', 'https://en.wikipedia.org/wiki/Spain')],
    'neigh_num': 2},
  { 'border_len_km': 5198,
    'border_len_mi': 3230,
    'country_name': 'Angola',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Angola',
    'neigh': [ ('Democratic Republic of the Congo', 'https://en.wikipedia.org/wiki/Democratic_Republic_of_the_Congo'),
               ('Namibia', 'https://en.wikipedia.org/wiki/Namibia'),
               ('Republic of the Congo', 'https://en.wikipedia.org/wiki/Republic_of_the_Congo'),
               ('Zambia', 'https://en.wikipedia.org/wiki/Zambia')],
    'neigh_num': 4},
  { 'border_len_km': 0,
    'border_len_mi': 0,
    'country_name': 'Antigua and Barbuda',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Antigua_and_Barbuda',
    'neigh': [],
    'neigh_num': 0},
  { 'border_len_km': 9665,
    'border_len_mi': 6006,
    'country_name': 'Argentina',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Argentina',
    'neigh': [ ('Bolivia', 'https://en.wikipedia.org/wiki/Bolivia'),
               ('Brazil', 'https://en.wikipedia.org/wiki/Brazil'),
               ('Chile', 'https://en.wikipedia.org/wiki/Chile'),
               ('Paraguay', 'https://en.wikipedia.org/wiki/Paraguay'),
               ('Uruguay', 'https://en.wikipedia.org/wiki/Uruguay')],
    'neigh_num': 5},
  { 'border_len_km': 1254,
    'border_len_mi': 779,
    'country_name': 'Armenia',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Armenia',
    'neigh': [ ('Azerbaijan', 'https://en.wikipedia.org/wiki/Azerbaijan'),
               ('Georgia (country)', 'https://en.wikipedia.org/wiki/Georgia_(country)'),
               ('Iran', 'https://en.wikipedia.org/wiki/Iran'),
               ('Turkey', 'https://en.wikipedia.org/wiki/Turkey')],
    'neigh_num': 4},
  { 'border_len_km': 0,
    'border_len_mi': 0,
    'country_name': 'Australia',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Australia',
    'neigh': [],
    'neigh_num': 0},
  { 'border_len_km': 2562,
    'border_len_mi': 1592,
    'country_name': 'Austria',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Austria',
    'neigh': [ ('Czech Republic', 'https://en.wikipedia.org/wiki/Czech_Republic'),
               ('Germany', 'https://en.wikipedia.org/wiki/Germany'),
               ('Hungary', 'https://en.wikipedia.org/wiki/Hungary'),
               ('Italy', 'https://en.wikipedia.org/wiki/Italy'),
               ('Liechtenstein', 'https://en.wikipedia.org/wiki/Liechtenstein'),
               ('Slovakia', 'https://en.wikipedia.org/wiki/Slovakia'),
               ('Slovenia', 'https://en.wikipedia.org/wiki/Slovenia'),
               ('Switzerland', 'https://en.wikipedia.org/wiki/Switzerland')],
    'neigh_num': 8},
  { 'border_len_km': 2013,
    'border_len_mi': 1251,
    'country_name': 'Azerbaijan',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Azerbaijan',
    'neigh': [ ('Armenia', 'https://en.wikipedia.org/wiki/Armenia'),
               ('Georgia (country)', 'https://en.wikipedia.org/wiki/Georgia_(country)'),
               ('Iran', 'https://en.wikipedia.org/wiki/Iran'),
               ('Russia', 'https://en.wikipedia.org/wiki/Russia'),
               ('Turkey', 'https://en.wikipedia.org/wiki/Turkey')],
    'neigh_num': 5},
  { 'border_len_km': 0,
    'border_len_mi': 0,
    'country_name': 'Bahrain',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Bahrain',
    'neigh': [],
    'neigh_num': 0},
  { 'border_len_km': 4246,
    'border_len_mi': 2638,
    'country_name': 'Bangladesh',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Bangladesh',
    'neigh': [('India', 'https://en.wikipedia.org/wiki/India'), ('Myanmar', 'https://en.wikipedia.org/wiki/Myanmar')],
    'neigh_num': 2},
  { 'border_len_km': 0,
    'border_len_mi': 0,
    'country_name': 'Barbados',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Barbados',
    'neigh': [],
    'neigh_num': 0},
  { 'border_len_km': 2900,
    'border_len_mi': 1800,
    'country_name': 'Belarus',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Belarus',
    'neigh': [ ('Latvia', 'https://en.wikipedia.org/wiki/Latvia'),
               ('Lithuania', 'https://en.wikipedia.org/wiki/Lithuania'),
               ('Poland', 'https://en.wikipedia.org/wiki/Poland'),
               ('Russia', 'https://en.wikipedia.org/wiki/Russia'),
               ('Ukraine', 'https://en.wikipedia.org/wiki/Ukraine')],
    'neigh_num': 5},
  { 'border_len_km': 1385,
    'border_len_mi': 861,
    'country_name': 'Belgium',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Belgium',
    'neigh': [ ('France', 'https://en.wikipedia.org/wiki/France'),
               ('Germany', 'https://en.wikipedia.org/wiki/Germany'),
               ('Luxembourg', 'https://en.wikipedia.org/wiki/Luxembourg'),
               ('Netherlands', 'https://en.wikipedia.org/wiki/Netherlands')],
    'neigh_num': 4},
  { 'border_len_km': 516,
    'border_len_mi': 321,
    'country_name': 'Belize',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Belize',
    'neigh': [ ('Guatemala', 'https://en.wikipedia.org/wiki/Guatemala'),
               ('Mexico', 'https://en.wikipedia.org/wiki/Mexico')],
    'neigh_num': 2},
  { 'border_len_km': 1989,
    'border_len_mi': 1236,
    'country_name': 'Benin',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Benin',
    'neigh': [ ('Burkina Faso', 'https://en.wikipedia.org/wiki/Burkina_Faso'),
               ('Niger', 'https://en.wikipedia.org/wiki/Niger'),
               ('Nigeria', 'https://en.wikipedia.org/wiki/Nigeria'),
               ('Togo', 'https://en.wikipedia.org/wiki/Togo')],
    'neigh_num': 4},
  { 'border_len_km': 1075,
    'border_len_mi': 668,
    'country_name': 'Bhutan',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Bhutan',
    'neigh': [('China', 'https://en.wikipedia.org/wiki/China'), ('India', 'https://en.wikipedia.org/wiki/India')],
    'neigh_num': 2},
  { 'border_len_km': 6743,
    'border_len_mi': 4190,
    'country_name': 'Bolivia',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Bolivia',
    'neigh': [ ('Argentina', 'https://en.wikipedia.org/wiki/Argentina'),
               ('Brazil', 'https://en.wikipedia.org/wiki/Brazil'),
               ('Chile', 'https://en.wikipedia.org/wiki/Chile'),
               ('Paraguay', 'https://en.wikipedia.org/wiki/Paraguay'),
               ('Peru', 'https://en.wikipedia.org/wiki/Peru')],
    'neigh_num': 5},
  { 'border_len_km': 1459,
    'border_len_mi': 907,
    'country_name': 'Bosnia and Herzegovina',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Bosnia_and_Herzegovina',
    'neigh': [ ('Croatia', 'https://en.wikipedia.org/wiki/Croatia'),
               ('Montenegro', 'https://en.wikipedia.org/wiki/Montenegro'),
               ('Serbia', 'https://en.wikipedia.org/wiki/Serbia')],
    'neigh_num': 3},
  { 'border_len_km': 4015,
    'border_len_mi': 2495,
    'country_name': 'Botswana',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Botswana',
    'neigh': [ ('Namibia', 'https://en.wikipedia.org/wiki/Namibia'),
               ('South Africa', 'https://en.wikipedia.org/wiki/South_Africa'),
               ('Zambia', 'https://en.wikipedia.org/wiki/Zambia'),
               ('Zimbabwe', 'https://en.wikipedia.org/wiki/Zimbabwe')],
    'neigh_num': 4},
  { 'border_len_km': 14691,
    'border_len_mi': 9129,
    'country_name': 'Brazil',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Brazil',
    'neigh': [ ('Argentina', 'https://en.wikipedia.org/wiki/Argentina'),
               ('Bolivia', 'https://en.wikipedia.org/wiki/Bolivia'),
               ('Colombia', 'https://en.wikipedia.org/wiki/Colombia'),
               ('France', 'https://en.wikipedia.org/wiki/France'),
               ('French Guiana', 'https://en.wikipedia.org/wiki/French_Guiana'),
               ('Guyana', 'https://en.wikipedia.org/wiki/Guyana'),
               ('Paraguay', 'https://en.wikipedia.org/wiki/Paraguay'),
               ('Peru', 'https://en.wikipedia.org/wiki/Peru'),
               ('Suriname', 'https://en.wikipedia.org/wiki/Suriname'),
               ('Uruguay', 'https://en.wikipedia.org/wiki/Uruguay'),
               ('Venezuela', 'https://en.wikipedia.org/wiki/Venezuela')],
    'neigh_num': 10},
  { 'border_len_km': 381,
    'border_len_mi': 237,
    'country_name': 'Brunei',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Brunei',
    'neigh': [('Malaysia', 'https://en.wikipedia.org/wiki/Malaysia')],
    'neigh_num': 1},
  { 'border_len_km': 1808,
    'border_len_mi': 1123,
    'country_name': 'Bulgaria',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Bulgaria',
    'neigh': [ ('Greece', 'https://en.wikipedia.org/wiki/Greece'),
               ('North Macedonia', 'https://en.wikipedia.org/wiki/North_Macedonia'),
               ('Romania', 'https://en.wikipedia.org/wiki/Romania'),
               ('Serbia', 'https://en.wikipedia.org/wiki/Serbia'),
               ('Turkey', 'https://en.wikipedia.org/wiki/Turkey')],
    'neigh_num': 5},
  { 'border_len_km': 3193,
    'border_len_mi': 1984,
    'country_name': 'Burkina Faso',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Burkina_Faso',
    'neigh': [ ('Benin', 'https://en.wikipedia.org/wiki/Benin'),
               ('Ghana', 'https://en.wikipedia.org/wiki/Ghana'),
               ('Ivory Coast', 'https://en.wikipedia.org/wiki/Ivory_Coast'),
               ('Mali', 'https://en.wikipedia.org/wiki/Mali'),
               ('Niger', 'https://en.wikipedia.org/wiki/Niger'),
               ('Togo', 'https://en.wikipedia.org/wiki/Togo')],
    'neigh_num': 6},
  { 'border_len_km': 974,
    'border_len_mi': 605,
    'country_name': 'Burundi',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Burundi',
    'neigh': [ ('Democratic Republic of the Congo', 'https://en.wikipedia.org/wiki/Democratic_Republic_of_the_Congo'),
               ('Rwanda', 'https://en.wikipedia.org/wiki/Rwanda'),
               ('Tanzania', 'https://en.wikipedia.org/wiki/Tanzania')],
    'neigh_num': 3},
  { 'border_len_km': 2572,
    'border_len_mi': 1598,
    'country_name': 'Cambodia',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Cambodia',
    'neigh': [ ('Laos', 'https://en.wikipedia.org/wiki/Laos'),
               ('Thailand', 'https://en.wikipedia.org/wiki/Thailand'),
               ('Vietnam', 'https://en.wikipedia.org/wiki/Vietnam')],
    'neigh_num': 3},
  { 'border_len_km': 4591,
    'border_len_mi': 2853,
    'country_name': 'Cameroon',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Cameroon',
    'neigh': [ ('Central African Republic', 'https://en.wikipedia.org/wiki/Central_African_Republic'),
               ('Chad', 'https://en.wikipedia.org/wiki/Chad'),
               ('Equatorial Guinea', 'https://en.wikipedia.org/wiki/Equatorial_Guinea'),
               ('Gabon', 'https://en.wikipedia.org/wiki/Gabon'),
               ('Nigeria', 'https://en.wikipedia.org/wiki/Nigeria'),
               ('Republic of the Congo', 'https://en.wikipedia.org/wiki/Republic_of_the_Congo')],
    'neigh_num': 6},
  { 'border_len_km': 8893,
    'border_len_mi': 5526,
    'country_name': 'Canada',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Canada',
    'neigh': [('United States', 'https://en.wikipedia.org/wiki/United_States')],
    'neigh_num': 1},
  { 'border_len_km': 0,
    'border_len_mi': 0,
    'country_name': 'Cape Verde',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Cape_Verde',
    'neigh': [],
    'neigh_num': 0},
  { 'border_len_km': 5213,
    'border_len_mi': 3239,
    'country_name': 'Central African Republic',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Central_African_Republic',
    'neigh': [ ('Cameroon', 'https://en.wikipedia.org/wiki/Cameroon'),
               ('Chad', 'https://en.wikipedia.org/wiki/Chad'),
               ('Democratic Republic of the Congo', 'https://en.wikipedia.org/wiki/Democratic_Republic_of_the_Congo'),
               ('Republic of the Congo', 'https://en.wikipedia.org/wiki/Republic_of_the_Congo'),
               ('South Sudan', 'https://en.wikipedia.org/wiki/South_Sudan'),
               ('Sudan', 'https://en.wikipedia.org/wiki/Sudan')],
    'neigh_num': 6},
  { 'border_len_km': 5968,
    'border_len_mi': 3708,
    'country_name': 'Chad',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Chad',
    'neigh': [ ('Cameroon', 'https://en.wikipedia.org/wiki/Cameroon'),
               ('Central African Republic', 'https://en.wikipedia.org/wiki/Central_African_Republic'),
               ('Libya', 'https://en.wikipedia.org/wiki/Libya'),
               ('Niger', 'https://en.wikipedia.org/wiki/Niger'),
               ('Nigeria', 'https://en.wikipedia.org/wiki/Nigeria'),
               ('Sudan', 'https://en.wikipedia.org/wiki/Sudan')],
    'neigh_num': 6},
  { 'border_len_km': 6171,
    'border_len_mi': 3834,
    'country_name': 'Chile',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Chile',
    'neigh': [ ('Argentina', 'https://en.wikipedia.org/wiki/Argentina'),
               ('Bolivia', 'https://en.wikipedia.org/wiki/Bolivia'),
               ('Peru', 'https://en.wikipedia.org/wiki/Peru')],
    'neigh_num': 3},
  { 'border_len_km': 22147,
    'border_len_mi': 13762,
    'country_name': 'China',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/China',
    'neigh': [ ('Afghanistan', 'https://en.wikipedia.org/wiki/Afghanistan'),
               ('Bhutan', 'https://en.wikipedia.org/wiki/Bhutan'),
               ('Hong Kong', 'https://en.wikipedia.org/wiki/Hong_Kong'),
               ('India', 'https://en.wikipedia.org/wiki/India'),
               ('Kazakhstan', 'https://en.wikipedia.org/wiki/Kazakhstan'),
               ('Kyrgyzstan', 'https://en.wikipedia.org/wiki/Kyrgyzstan'),
               ('Laos', 'https://en.wikipedia.org/wiki/Laos'),
               ('Macau', 'https://en.wikipedia.org/wiki/Macau'),
               ('Mongolia', 'https://en.wikipedia.org/wiki/Mongolia'),
               ('Myanmar', 'https://en.wikipedia.org/wiki/Myanmar'),
               ('Nepal', 'https://en.wikipedia.org/wiki/Nepal'),
               ('North Korea', 'https://en.wikipedia.org/wiki/North_Korea'),
               ('Pakistan', 'https://en.wikipedia.org/wiki/Pakistan'),
               ('Russia', 'https://en.wikipedia.org/wiki/Russia'),
               ( 'Special administrative regions of China',
                 'https://en.wikipedia.org/wiki/Special_administrative_regions_of_China'),
               ( 'Special administrative regions of China',
                 'https://en.wikipedia.org/wiki/Special_administrative_regions_of_China'),
               ('Tajikistan', 'https://en.wikipedia.org/wiki/Tajikistan'),
               ('Vietnam', 'https://en.wikipedia.org/wiki/Vietnam')],
    'neigh_num': 14},
  { 'border_len_km': 6004,
    'border_len_mi': 3731,
    'country_name': 'Colombia',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Colombia',
    'neigh': [ ('Brazil', 'https://en.wikipedia.org/wiki/Brazil'),
               ('Ecuador', 'https://en.wikipedia.org/wiki/Ecuador'),
               ('Panama', 'https://en.wikipedia.org/wiki/Panama'),
               ('Peru', 'https://en.wikipedia.org/wiki/Peru'),
               ('Venezuela', 'https://en.wikipedia.org/wiki/Venezuela')],
    'neigh_num': 5},
  { 'border_len_km': 0,
    'border_len_mi': 0,
    'country_name': 'Comoros',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Comoros',
    'neigh': [],
    'neigh_num': 0},
  { 'border_len_km': 639,
    'border_len_mi': 397,
    'country_name': 'Costa Rica',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Costa_Rica',
    'neigh': [ ('Nicaragua', 'https://en.wikipedia.org/wiki/Nicaragua'),
               ('Panama', 'https://en.wikipedia.org/wiki/Panama')],
    'neigh_num': 2},
  { 'border_len_km': 2197,
    'border_len_mi': 1365,
    'country_name': 'Croatia',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Croatia',
    'neigh': [ ('Bosnia and Herzegovina', 'https://en.wikipedia.org/wiki/Bosnia_and_Herzegovina'),
               ('Hungary', 'https://en.wikipedia.org/wiki/Hungary'),
               ('Montenegro', 'https://en.wikipedia.org/wiki/Montenegro'),
               ('Serbia', 'https://en.wikipedia.org/wiki/Serbia'),
               ('Slovenia', 'https://en.wikipedia.org/wiki/Slovenia')],
    'neigh_num': 5},
  { 'border_len_km': 0,
    'border_len_mi': 0,
    'country_name': 'Cuba',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Cuba',
    'neigh': [],
    'neigh_num': 0},
  { 'border_len_km': 152,
    'border_len_mi': 94,
    'country_name': 'Cyprus',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Cyprus',
    'neigh': [ ('Akrotiri and Dhekelia', 'https://en.wikipedia.org/wiki/Akrotiri_and_Dhekelia'),
               ('United Kingdom', 'https://en.wikipedia.org/wiki/United_Kingdom')],
    'neigh_num': 1},
  { 'border_len_km': 1881,
    'border_len_mi': 1169,
    'country_name': 'Czech Republic',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Czech_Republic',
    'neigh': [ ('Austria', 'https://en.wikipedia.org/wiki/Austria'),
               ('Germany', 'https://en.wikipedia.org/wiki/Germany'),
               ('Poland', 'https://en.wikipedia.org/wiki/Poland'),
               ('Slovakia', 'https://en.wikipedia.org/wiki/Slovakia')],
    'neigh_num': 4},
  { 'border_len_km': 10730,
    'border_len_mi': 6670,
    'country_name': 'Democratic Republic of the Congo',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Democratic_Republic_of_the_Congo',
    'neigh': [ ('Angola', 'https://en.wikipedia.org/wiki/Angola'),
               ('Burundi', 'https://en.wikipedia.org/wiki/Burundi'),
               ('Central African Republic', 'https://en.wikipedia.org/wiki/Central_African_Republic'),
               ('Republic of the Congo', 'https://en.wikipedia.org/wiki/Republic_of_the_Congo'),
               ('Rwanda', 'https://en.wikipedia.org/wiki/Rwanda'),
               ('South Sudan', 'https://en.wikipedia.org/wiki/South_Sudan'),
               ('Tanzania', 'https://en.wikipedia.org/wiki/Tanzania'),
               ('Uganda', 'https://en.wikipedia.org/wiki/Uganda'),
               ('Zambia', 'https://en.wikipedia.org/wiki/Zambia')],
    'neigh_num': 9},
  { 'border_len_km': 68,
    'border_len_mi': 42,
    'country_name': 'Denmark',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Denmark',
    'neigh': [('Germany', 'https://en.wikipedia.org/wiki/Germany')],
    'neigh_num': 1},
  { 'border_len_km': 528,
    'border_len_mi': 328,
    'country_name': 'Djibouti',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Djibouti',
    'neigh': [ ('Eritrea', 'https://en.wikipedia.org/wiki/Eritrea'),
               ('Ethiopia', 'https://en.wikipedia.org/wiki/Ethiopia'),
               ('Somaliland', 'https://en.wikipedia.org/wiki/Somaliland')],
    'neigh_num': 3},
  { 'border_len_km': 0,
    'border_len_mi': 0,
    'country_name': 'Dominica',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Dominica',
    'neigh': [],
    'neigh_num': 0},
  { 'border_len_km': 360,
    'border_len_mi': 220,
    'country_name': 'Dominican Republic',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Dominican_Republic',
    'neigh': [('Haiti', 'https://en.wikipedia.org/wiki/Haiti')],
    'neigh_num': 1},
  { 'border_len_km': 228,
    'border_len_mi': 142,
    'country_name': 'East Timor',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/East_Timor',
    'neigh': [('Indonesia', 'https://en.wikipedia.org/wiki/Indonesia')],
    'neigh_num': 1},
  { 'border_len_km': 2010,
    'border_len_mi': 1250,
    'country_name': 'Ecuador',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Ecuador',
    'neigh': [('Colombia', 'https://en.wikipedia.org/wiki/Colombia'), ('Peru', 'https://en.wikipedia.org/wiki/Peru')],
    'neigh_num': 2},
  { 'border_len_km': 2665,
    'border_len_mi': 1656,
    'country_name': 'Egypt',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Egypt',
    'neigh': [ ('Gaza Strip', 'https://en.wikipedia.org/wiki/Gaza_Strip'),
               ('State of Palestine', 'https://en.wikipedia.org/wiki/State_of_Palestine')],
    'neigh_num': 4},
  { 'border_len_km': 545,
    'border_len_mi': 339,
    'country_name': 'El Salvador',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/El_Salvador',
    'neigh': [ ('Guatemala', 'https://en.wikipedia.org/wiki/Guatemala'),
               ('Honduras', 'https://en.wikipedia.org/wiki/Honduras')],
    'neigh_num': 2},
  { 'border_len_km': 539,
    'border_len_mi': 335,
    'country_name': 'Equatorial Guinea',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Equatorial_Guinea',
    'neigh': [('Cameroon', 'https://en.wikipedia.org/wiki/Cameroon'), ('Gabon', 'https://en.wikipedia.org/wiki/Gabon')],
    'neigh_num': 2},
  { 'border_len_km': 1626,
    'border_len_mi': 1010,
    'country_name': 'Eritrea',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Eritrea',
    'neigh': [ ('Djibouti', 'https://en.wikipedia.org/wiki/Djibouti'),
               ('Ethiopia', 'https://en.wikipedia.org/wiki/Ethiopia'),
               ('Sudan', 'https://en.wikipedia.org/wiki/Sudan')],
    'neigh_num': 3},
  { 'border_len_km': 633,
    'border_len_mi': 393,
    'country_name': 'Estonia',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Estonia',
    'neigh': [('Latvia', 'https://en.wikipedia.org/wiki/Latvia'), ('Russia', 'https://en.wikipedia.org/wiki/Russia')],
    'neigh_num': 2},
  { 'border_len_km': 535,
    'border_len_mi': 332,
    'country_name': 'Eswatini',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Eswatini',
    'neigh': [ ('Mozambique', 'https://en.wikipedia.org/wiki/Mozambique'),
               ('South Africa', 'https://en.wikipedia.org/wiki/South_Africa')],
    'neigh_num': 2},
  { 'border_len_km': 5328,
    'border_len_mi': 3311,
    'country_name': 'Ethiopia',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Ethiopia',
    'neigh': [ ('Djibouti', 'https://en.wikipedia.org/wiki/Djibouti'),
               ('Eritrea', 'https://en.wikipedia.org/wiki/Eritrea'),
               ('Kenya', 'https://en.wikipedia.org/wiki/Kenya'),
               ('Somalia', 'https://en.wikipedia.org/wiki/Somalia'),
               ('South Sudan', 'https://en.wikipedia.org/wiki/South_Sudan'),
               ('Sudan', 'https://en.wikipedia.org/wiki/Sudan')],
    'neigh_num': 6},
  { 'border_len_km': 0,
    'border_len_mi': 0,
    'country_name': 'Federated States of Micronesia',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Federated_States_of_Micronesia',
    'neigh': [],
    'neigh_num': 0},
  { 'border_len_km': 0,
    'border_len_mi': 0,
    'country_name': 'Fiji',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Fiji',
    'neigh': [],
    'neigh_num': 0},
  { 'border_len_km': 2690,
    'border_len_mi': 1670,
    'country_name': 'Finland',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Finland',
    'neigh': [ ('Norway', 'https://en.wikipedia.org/wiki/Norway'),
               ('Russia', 'https://en.wikipedia.org/wiki/Russia'),
               ('Sweden', 'https://en.wikipedia.org/wiki/Sweden')],
    'neigh_num': 3},
  { 'border_len_km': 2889,
    'border_len_mi': 1795,
    'country_name': 'France',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/France',
    'neigh': [ ('Andorra', 'https://en.wikipedia.org/wiki/Andorra'),
               ('Belgium', 'https://en.wikipedia.org/wiki/Belgium'),
               ('Germany', 'https://en.wikipedia.org/wiki/Germany'),
               ('Italy', 'https://en.wikipedia.org/wiki/Italy'),
               ('Luxembourg', 'https://en.wikipedia.org/wiki/Luxembourg'),
               ('Monaco', 'https://en.wikipedia.org/wiki/Monaco'),
               ('Spain', 'https://en.wikipedia.org/wiki/Spain'),
               ('Switzerland', 'https://en.wikipedia.org/wiki/Switzerland')],
    'neigh_num': 8},
  { 'border_len_km': 4082,
    'border_len_mi': 2536,
    'country_name': 'France',
    'country_sub': [ ('Clipperton Island', 'https://en.wikipedia.org/wiki/Clipperton_Island'),
                     ('Collectivity of Saint Martin', 'https://en.wikipedia.org/wiki/Collectivity_of_Saint_Martin'),
                     ('French Guiana', 'https://en.wikipedia.org/wiki/French_Guiana'),
                     ('French Polynesia', 'https://en.wikipedia.org/wiki/French_Polynesia'),
                     ( 'French Southern and Antarctic Lands',
                       'https://en.wikipedia.org/wiki/French_Southern_and_Antarctic_Lands'),
                     ('Guadeloupe', 'https://en.wikipedia.org/wiki/Guadeloupe'),
                     ('Martinique', 'https://en.wikipedia.org/wiki/Martinique'),
                     ('Mayotte', 'https://en.wikipedia.org/wiki/Mayotte'),
                     ('New Caledonia', 'https://en.wikipedia.org/wiki/New_Caledonia'),
                     ('Réunion', 'https://en.wikipedia.org/wiki/R%C3%A9union'),
                     ('Saint Barthélemy', 'https://en.wikipedia.org/wiki/Saint_Barth%C3%A9lemy'),
                     ('Saint Pierre and Miquelon', 'https://en.wikipedia.org/wiki/Saint_Pierre_and_Miquelon'),
                     ('Wallis and Futuna', 'https://en.wikipedia.org/wiki/Wallis_and_Futuna')],
    'country_url': 'https://en.wikipedia.org/wiki/France',
    'neigh': [ ('Andorra', 'https://en.wikipedia.org/wiki/Andorra'),
               ('Belgium', 'https://en.wikipedia.org/wiki/Belgium'),
               ('Brazil', 'https://en.wikipedia.org/wiki/Brazil'),
               ('Germany', 'https://en.wikipedia.org/wiki/Germany'),
               ('Italy', 'https://en.wikipedia.org/wiki/Italy'),
               ('Kingdom of the Netherlands', 'https://en.wikipedia.org/wiki/Kingdom_of_the_Netherlands'),
               ('Luxembourg', 'https://en.wikipedia.org/wiki/Luxembourg'),
               ('Monaco', 'https://en.wikipedia.org/wiki/Monaco'),
               ('Sint Maarten', 'https://en.wikipedia.org/wiki/Sint_Maarten'),
               ('Spain', 'https://en.wikipedia.org/wiki/Spain'),
               ('Suriname', 'https://en.wikipedia.org/wiki/Suriname'),
               ('Switzerland', 'https://en.wikipedia.org/wiki/Switzerland')],
    'neigh_num': 11},
  { 'border_len_km': 2551,
    'border_len_mi': 1585,
    'country_name': 'Gabon',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Gabon',
    'neigh': [ ('Cameroon', 'https://en.wikipedia.org/wiki/Cameroon'),
               ('Equatorial Guinea', 'https://en.wikipedia.org/wiki/Equatorial_Guinea'),
               ('Republic of the Congo', 'https://en.wikipedia.org/wiki/Republic_of_the_Congo')],
    'neigh_num': 3},
  { 'border_len_km': 1461,
    'border_len_mi': 908,
    'country_name': 'Georgia (country)',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Georgia_(country)',
    'neigh': [ ('Abkhazia', 'https://en.wikipedia.org/wiki/Abkhazia'),
               ('Armenia', 'https://en.wikipedia.org/wiki/Armenia'),
               ('Azerbaijan', 'https://en.wikipedia.org/wiki/Azerbaijan'),
               ('Russia', 'https://en.wikipedia.org/wiki/Russia'),
               ('South Ossetia', 'https://en.wikipedia.org/wiki/South_Ossetia'),
               ('Turkey', 'https://en.wikipedia.org/wiki/Turkey')],
    'neigh_num': 4},
  { 'border_len_km': 3621,
    'border_len_mi': 2250,
    'country_name': 'Germany',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Germany',
    'neigh': [ ('Austria', 'https://en.wikipedia.org/wiki/Austria'),
               ('Belgium', 'https://en.wikipedia.org/wiki/Belgium'),
               ('Czech Republic', 'https://en.wikipedia.org/wiki/Czech_Republic'),
               ('Denmark', 'https://en.wikipedia.org/wiki/Denmark'),
               ('France', 'https://en.wikipedia.org/wiki/France'),
               ('Luxembourg', 'https://en.wikipedia.org/wiki/Luxembourg'),
               ('Netherlands', 'https://en.wikipedia.org/wiki/Netherlands'),
               ('Poland', 'https://en.wikipedia.org/wiki/Poland'),
               ('Switzerland', 'https://en.wikipedia.org/wiki/Switzerland')],
    'neigh_num': 9},
  { 'border_len_km': 2094,
    'border_len_mi': 1301,
    'country_name': 'Ghana',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Ghana',
    'neigh': [ ('Burkina Faso', 'https://en.wikipedia.org/wiki/Burkina_Faso'),
               ('Ivory Coast', 'https://en.wikipedia.org/wiki/Ivory_Coast'),
               ('Togo', 'https://en.wikipedia.org/wiki/Togo')],
    'neigh_num': 3},
  { 'border_len_km': 1228,
    'border_len_mi': 763,
    'country_name': 'Greece',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Greece',
    'neigh': [ ('Albania', 'https://en.wikipedia.org/wiki/Albania'),
               ('Bulgaria', 'https://en.wikipedia.org/wiki/Bulgaria'),
               ('North Macedonia', 'https://en.wikipedia.org/wiki/North_Macedonia'),
               ('Turkey', 'https://en.wikipedia.org/wiki/Turkey')],
    'neigh_num': 4},
  { 'border_len_km': 0,
    'border_len_mi': 0,
    'country_name': 'Grenada',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Grenada',
    'neigh': [],
    'neigh_num': 0},
  { 'border_len_km': 1687,
    'border_len_mi': 1048,
    'country_name': 'Guatemala',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Guatemala',
    'neigh': [ ('Belize', 'https://en.wikipedia.org/wiki/Belize'),
               ('El Salvador', 'https://en.wikipedia.org/wiki/El_Salvador'),
               ('Honduras', 'https://en.wikipedia.org/wiki/Honduras'),
               ('Mexico', 'https://en.wikipedia.org/wiki/Mexico')],
    'neigh_num': 4},
  { 'border_len_km': 3399,
    'border_len_mi': 2112,
    'country_name': 'Guinea',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Guinea',
    'neigh': [ ('Guinea-Bissau', 'https://en.wikipedia.org/wiki/Guinea-Bissau'),
               ('Ivory Coast', 'https://en.wikipedia.org/wiki/Ivory_Coast'),
               ('Liberia', 'https://en.wikipedia.org/wiki/Liberia'),
               ('Mali', 'https://en.wikipedia.org/wiki/Mali'),
               ('Senegal', 'https://en.wikipedia.org/wiki/Senegal'),
               ('Sierra Leone', 'https://en.wikipedia.org/wiki/Sierra_Leone')],
    'neigh_num': 6},
  { 'border_len_km': 724,
    'border_len_mi': 450,
    'country_name': 'Guinea-Bissau',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Guinea-Bissau',
    'neigh': [('Guinea', 'https://en.wikipedia.org/wiki/Guinea'), ('Senegal', 'https://en.wikipedia.org/wiki/Senegal')],
    'neigh_num': 2},
  { 'border_len_km': 2462,
    'border_len_mi': 1530,
    'country_name': 'Guyana',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Guyana',
    'neigh': [ ('Brazil', 'https://en.wikipedia.org/wiki/Brazil'),
               ('Suriname', 'https://en.wikipedia.org/wiki/Suriname'),
               ('Venezuela', 'https://en.wikipedia.org/wiki/Venezuela')],
    'neigh_num': 3},
  { 'border_len_km': 360,
    'border_len_mi': 220,
    'country_name': 'Haiti',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Haiti',
    'neigh': [('Dominican Republic', 'https://en.wikipedia.org/wiki/Dominican_Republic')],
    'neigh_num': 1},
  { 'border_len_km': 1520,
    'border_len_mi': 940,
    'country_name': 'Honduras',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Honduras',
    'neigh': [ ('El Salvador', 'https://en.wikipedia.org/wiki/El_Salvador'),
               ('Guatemala', 'https://en.wikipedia.org/wiki/Guatemala'),
               ('Nicaragua', 'https://en.wikipedia.org/wiki/Nicaragua')],
    'neigh_num': 3},
  { 'border_len_km': 30,
    'border_len_mi': 19,
    'country_name': 'Hong Kong',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Hong_Kong',
    'neigh': [('China', 'https://en.wikipedia.org/wiki/China')],
    'neigh_num': 1},
  { 'border_len_km': 2171,
    'border_len_mi': 1349,
    'country_name': 'Hungary',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Hungary',
    'neigh': [ ('Austria', 'https://en.wikipedia.org/wiki/Austria'),
               ('Croatia', 'https://en.wikipedia.org/wiki/Croatia'),
               ('Romania', 'https://en.wikipedia.org/wiki/Romania'),
               ('Serbia', 'https://en.wikipedia.org/wiki/Serbia'),
               ('Slovakia', 'https://en.wikipedia.org/wiki/Slovakia'),
               ('Slovenia', 'https://en.wikipedia.org/wiki/Slovenia'),
               ('Ukraine', 'https://en.wikipedia.org/wiki/Ukraine')],
    'neigh_num': 7},
  { 'border_len_km': 0,
    'border_len_mi': 0,
    'country_name': 'Iceland',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Iceland',
    'neigh': [],
    'neigh_num': 0},
  { 'border_len_km': 14209,
    'border_len_mi': 8829,
    'country_name': 'India',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/India',
    'neigh': [ ("Adam's bridge", 'https://en.wikipedia.org/wiki/Adam%27s_bridge'),
               ('Afghanistan', 'https://en.wikipedia.org/wiki/Afghanistan'),
               ('Bangladesh', 'https://en.wikipedia.org/wiki/Bangladesh'),
               ('Bhutan', 'https://en.wikipedia.org/wiki/Bhutan'),
               ('Borders of India', 'https://en.wikipedia.org/wiki/Borders_of_India'),
               ('China', 'https://en.wikipedia.org/wiki/China'),
               ('Myanmar', 'https://en.wikipedia.org/wiki/Myanmar'),
               ('Nepal', 'https://en.wikipedia.org/wiki/Nepal'),
               ('Pakistan', 'https://en.wikipedia.org/wiki/Pakistan'),
               ('Sri Lanka', 'https://en.wikipedia.org/wiki/Sri_Lanka')],
    'neigh_num': 8},
  { 'border_len_km': 2830,
    'border_len_mi': 1760,
    'country_name': 'Indonesia',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Indonesia',
    'neigh': [ ('East Timor', 'https://en.wikipedia.org/wiki/East_Timor'),
               ('Malaysia', 'https://en.wikipedia.org/wiki/Malaysia'),
               ('Papua New Guinea', 'https://en.wikipedia.org/wiki/Papua_New_Guinea')],
    'neigh_num': 3},
  { 'border_len_km': 5440,
    'border_len_mi': 3380,
    'country_name': 'Iran',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Iran',
    'neigh': [ ('Afghanistan', 'https://en.wikipedia.org/wiki/Afghanistan'),
               ('Armenia', 'https://en.wikipedia.org/wiki/Armenia'),
               ('Azerbaijan', 'https://en.wikipedia.org/wiki/Azerbaijan'),
               ('Iraq', 'https://en.wikipedia.org/wiki/Iraq'),
               ('Pakistan', 'https://en.wikipedia.org/wiki/Pakistan'),
               ('Turkey', 'https://en.wikipedia.org/wiki/Turkey'),
               ('Turkmenistan', 'https://en.wikipedia.org/wiki/Turkmenistan')],
    'neigh_num': 7},
  { 'border_len_km': 3650,
    'border_len_mi': 2270,
    'country_name': 'Iraq',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Iraq',
    'neigh': [ ('Iran', 'https://en.wikipedia.org/wiki/Iran'),
               ('Jordan', 'https://en.wikipedia.org/wiki/Jordan'),
               ('Kuwait', 'https://en.wikipedia.org/wiki/Kuwait'),
               ('Saudi Arabia', 'https://en.wikipedia.org/wiki/Saudi_Arabia'),
               ('Syria', 'https://en.wikipedia.org/wiki/Syria'),
               ('Turkey', 'https://en.wikipedia.org/wiki/Turkey')],
    'neigh_num': 6},
  { 'border_len_km': 1017,
    'border_len_mi': 632,
    'country_name': 'Israel',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Israel',
    'neigh': [ ('Egypt', 'https://en.wikipedia.org/wiki/Egypt'),
               ('Gaza Strip', 'https://en.wikipedia.org/wiki/Gaza_Strip'),
               ('Jordan', 'https://en.wikipedia.org/wiki/Jordan'),
               ('Lebanon', 'https://en.wikipedia.org/wiki/Lebanon'),
               ('State of Palestine', 'https://en.wikipedia.org/wiki/State_of_Palestine'),
               ('State of palestine', 'https://en.wikipedia.org/wiki/State_of_palestine'),
               ('Syria', 'https://en.wikipedia.org/wiki/Syria'),
               ('West Bank', 'https://en.wikipedia.org/wiki/West_Bank')],
    'neigh_num': 5},
  { 'border_len_km': 1932,
    'border_len_mi': 1200,
    'country_name': 'Italy',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Italy',
    'neigh': [ ('Austria', 'https://en.wikipedia.org/wiki/Austria'),
               ('France', 'https://en.wikipedia.org/wiki/France'),
               ('San Marino', 'https://en.wikipedia.org/wiki/San_Marino'),
               ('Slovenia', 'https://en.wikipedia.org/wiki/Slovenia'),
               ('Switzerland', 'https://en.wikipedia.org/wiki/Switzerland'),
               ('Vatican City', 'https://en.wikipedia.org/wiki/Vatican_City')],
    'neigh_num': 6},
  { 'border_len_km': 3110,
    'border_len_mi': 1930,
    'country_name': 'Ivory Coast',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Ivory_Coast',
    'neigh': [ ('Burkina Faso', 'https://en.wikipedia.org/wiki/Burkina_Faso'),
               ('Ghana', 'https://en.wikipedia.org/wiki/Ghana'),
               ('Guinea', 'https://en.wikipedia.org/wiki/Guinea'),
               ('Liberia', 'https://en.wikipedia.org/wiki/Liberia'),
               ('Mali', 'https://en.wikipedia.org/wiki/Mali')],
    'neigh_num': 5},
  { 'border_len_km': 0,
    'border_len_mi': 0,
    'country_name': 'Jamaica',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Jamaica',
    'neigh': [],
    'neigh_num': 0},
  { 'border_len_km': 0,
    'border_len_mi': 0,
    'country_name': 'Japan',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Japan',
    'neigh': [],
    'neigh_num': 0},
  { 'border_len_km': 1635,
    'border_len_mi': 1016,
    'country_name': 'Jordan',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Jordan',
    'neigh': [ ('Iraq', 'https://en.wikipedia.org/wiki/Iraq'),
               ('Israel', 'https://en.wikipedia.org/wiki/Israel'),
               ('Saudi Arabia', 'https://en.wikipedia.org/wiki/Saudi_Arabia'),
               ('State of Palestine', 'https://en.wikipedia.org/wiki/State_of_Palestine'),
               ('Syria', 'https://en.wikipedia.org/wiki/Syria'),
               ('West Bank', 'https://en.wikipedia.org/wiki/West_Bank')],
    'neigh_num': 5},
  { 'border_len_km': 12012,
    'border_len_mi': 7464,
    'country_name': 'Kazakhstan',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Kazakhstan',
    'neigh': [ ('China', 'https://en.wikipedia.org/wiki/China'),
               ('Kyrgyzstan', 'https://en.wikipedia.org/wiki/Kyrgyzstan'),
               ('Russia', 'https://en.wikipedia.org/wiki/Russia'),
               ('Turkmenistan', 'https://en.wikipedia.org/wiki/Turkmenistan'),
               ('Uzbekistan', 'https://en.wikipedia.org/wiki/Uzbekistan')],
    'neigh_num': 5},
  { 'border_len_km': 3477,
    'border_len_mi': 2161,
    'country_name': 'Kenya',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Kenya',
    'neigh': [ ('Ethiopia', 'https://en.wikipedia.org/wiki/Ethiopia'),
               ('Somalia', 'https://en.wikipedia.org/wiki/Somalia'),
               ('South Sudan', 'https://en.wikipedia.org/wiki/South_Sudan'),
               ('Tanzania', 'https://en.wikipedia.org/wiki/Tanzania'),
               ('Uganda', 'https://en.wikipedia.org/wiki/Uganda')],
    'neigh_num': 5},
  { 'border_len_km': 1037,
    'border_len_mi': 644,
    'country_name': 'Kingdom of the Netherlands',
    'country_sub': [ ('Aruba', 'https://en.wikipedia.org/wiki/Aruba'),
                     ('Caribbean Netherlands', 'https://en.wikipedia.org/wiki/Caribbean_Netherlands'),
                     ('Curaçao', 'https://en.wikipedia.org/wiki/Cura%C3%A7ao'),
                     ('Netherlands', 'https://en.wikipedia.org/wiki/Netherlands'),
                     ('Sint Maarten', 'https://en.wikipedia.org/wiki/Sint_Maarten')],
    'country_url': 'https://en.wikipedia.org/wiki/Kingdom_of_the_Netherlands',
    'neigh': [ ('Belgium', 'https://en.wikipedia.org/wiki/Belgium'),
               ('Collectivity of Saint Martin', 'https://en.wikipedia.org/wiki/Collectivity_of_Saint_Martin'),
               ('France', 'https://en.wikipedia.org/wiki/France'),
               ('Germany', 'https://en.wikipedia.org/wiki/Germany')],
    'neigh_num': 3},
  { 'border_len_km': 0,
    'border_len_mi': 0,
    'country_name': 'Kiribati',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Kiribati',
    'neigh': [],
    'neigh_num': 0},
  { 'border_len_km': 701,
    'border_len_mi': 436,
    'country_name': 'Kosovo',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Kosovo',
    'neigh': [ ('Albania', 'https://en.wikipedia.org/wiki/Albania'),
               ('Montenegro', 'https://en.wikipedia.org/wiki/Montenegro'),
               ('North Macedonia', 'https://en.wikipedia.org/wiki/North_Macedonia'),
               ('Serbia', 'https://en.wikipedia.org/wiki/Serbia')],
    'neigh_num': 4},
  { 'border_len_km': 462,
    'border_len_mi': 287,
    'country_name': 'Kuwait',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Kuwait',
    'neigh': [ ('Iraq', 'https://en.wikipedia.org/wiki/Iraq'),
               ('Saudi Arabia', 'https://en.wikipedia.org/wiki/Saudi_Arabia')],
    'neigh_num': 2},
  { 'border_len_km': 3878,
    'border_len_mi': 2410,
    'country_name': 'Kyrgyzstan',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Kyrgyzstan',
    'neigh': [ ('China', 'https://en.wikipedia.org/wiki/China'),
               ('Kazakhstan', 'https://en.wikipedia.org/wiki/Kazakhstan'),
               ('Tajikistan', 'https://en.wikipedia.org/wiki/Tajikistan'),
               ('Uzbekistan', 'https://en.wikipedia.org/wiki/Uzbekistan')],
    'neigh_num': 4},
  { 'border_len_km': 5083,
    'border_len_mi': 3158,
    'country_name': 'Laos',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Laos',
    'neigh': [ ('Cambodia', 'https://en.wikipedia.org/wiki/Cambodia'),
               ('China', 'https://en.wikipedia.org/wiki/China'),
               ('Myanmar', 'https://en.wikipedia.org/wiki/Myanmar'),
               ('Thailand', 'https://en.wikipedia.org/wiki/Thailand'),
               ('Vietnam', 'https://en.wikipedia.org/wiki/Vietnam')],
    'neigh_num': 5},
  { 'border_len_km': 1150,
    'border_len_mi': 710,
    'country_name': 'Latvia',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Latvia',
    'neigh': [ ('Belarus', 'https://en.wikipedia.org/wiki/Belarus'),
               ('Estonia', 'https://en.wikipedia.org/wiki/Estonia'),
               ('Lithuania', 'https://en.wikipedia.org/wiki/Lithuania'),
               ('Russia', 'https://en.wikipedia.org/wiki/Russia')],
    'neigh_num': 4},
  { 'border_len_km': 454,
    'border_len_mi': 282,
    'country_name': 'Lebanon',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Lebanon',
    'neigh': [('Israel', 'https://en.wikipedia.org/wiki/Israel'), ('Syria', 'https://en.wikipedia.org/wiki/Syria')],
    'neigh_num': 2},
  { 'border_len_km': 909,
    'border_len_mi': 565,
    'country_name': 'Lesotho',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Lesotho',
    'neigh': [('South Africa', 'https://en.wikipedia.org/wiki/South_Africa')],
    'neigh_num': 1},
  { 'border_len_km': 1585,
    'border_len_mi': 985,
    'country_name': 'Liberia',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Liberia',
    'neigh': [ ('Guinea', 'https://en.wikipedia.org/wiki/Guinea'),
               ('Ivory Coast', 'https://en.wikipedia.org/wiki/Ivory_Coast'),
               ('Sierra Leone', 'https://en.wikipedia.org/wiki/Sierra_Leone')],
    'neigh_num': 3},
  { 'border_len_km': 4348,
    'border_len_mi': 2702,
    'country_name': 'Libya',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Libya',
    'neigh': [ ('Algeria', 'https://en.wikipedia.org/wiki/Algeria'),
               ('Chad', 'https://en.wikipedia.org/wiki/Chad'),
               ('Egypt', 'https://en.wikipedia.org/wiki/Egypt'),
               ('Niger', 'https://en.wikipedia.org/wiki/Niger'),
               ('Sudan', 'https://en.wikipedia.org/wiki/Sudan'),
               ('Tunisia', 'https://en.wikipedia.org/wiki/Tunisia')],
    'neigh_num': 6},
  { 'border_len_km': 76,
    'border_len_mi': 47,
    'country_name': 'Liechtenstein',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Liechtenstein',
    'neigh': [ ('Austria', 'https://en.wikipedia.org/wiki/Austria'),
               ('Switzerland', 'https://en.wikipedia.org/wiki/Switzerland')],
    'neigh_num': 2},
  { 'border_len_km': 1273,
    'border_len_mi': 791,
    'country_name': 'Lithuania',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Lithuania',
    'neigh': [ ('Belarus', 'https://en.wikipedia.org/wiki/Belarus'),
               ('Latvia', 'https://en.wikipedia.org/wiki/Latvia'),
               ('Poland', 'https://en.wikipedia.org/wiki/Poland'),
               ('Russia', 'https://en.wikipedia.org/wiki/Russia')],
    'neigh_num': 4},
  { 'border_len_km': 359,
    'border_len_mi': 223,
    'country_name': 'Luxembourg',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Luxembourg',
    'neigh': [ ('Belgium', 'https://en.wikipedia.org/wiki/Belgium'),
               ('France', 'https://en.wikipedia.org/wiki/France'),
               ('Germany', 'https://en.wikipedia.org/wiki/Germany')],
    'neigh_num': 3},
  { 'border_len_km': 0,
    'border_len_mi': 0,
    'country_name': 'Macau',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Macau',
    'neigh': [('China', 'https://en.wikipedia.org/wiki/China')],
    'neigh_num': 1},
  { 'border_len_km': 0,
    'border_len_mi': 0,
    'country_name': 'Madagascar',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Madagascar',
    'neigh': [],
    'neigh_num': 0},
  { 'border_len_km': 0,
    'border_len_mi': 0,
    'country_name': 'Madeira',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Madeira',
    'neigh': [],
    'neigh_num': 0},
  { 'border_len_km': 2881,
    'border_len_mi': 1790,
    'country_name': 'Malawi',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Malawi',
    'neigh': [ ('Mozambique', 'https://en.wikipedia.org/wiki/Mozambique'),
               ('Tanzania', 'https://en.wikipedia.org/wiki/Tanzania'),
               ('Zambia', 'https://en.wikipedia.org/wiki/Zambia')],
    'neigh_num': 3},
  { 'border_len_km': 3147,
    'border_len_mi': 1955,
    'country_name': 'Malaysia',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Malaysia',
    'neigh': [ ('Brunei', 'https://en.wikipedia.org/wiki/Brunei'),
               ('Indonesia', 'https://en.wikipedia.org/wiki/Indonesia'),
               ('Thailand', 'https://en.wikipedia.org/wiki/Thailand')],
    'neigh_num': 3},
  { 'border_len_km': 0,
    'border_len_mi': 0,
    'country_name': 'Maldives',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Maldives',
    'neigh': [],
    'neigh_num': 0},
  { 'border_len_km': 7243,
    'border_len_mi': 4501,
    'country_name': 'Mali',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Mali',
    'neigh': [ ('Algeria', 'https://en.wikipedia.org/wiki/Algeria'),
               ('Burkina Faso', 'https://en.wikipedia.org/wiki/Burkina_Faso'),
               ('Guinea', 'https://en.wikipedia.org/wiki/Guinea'),
               ('Ivory Coast', 'https://en.wikipedia.org/wiki/Ivory_Coast'),
               ('Mauritania', 'https://en.wikipedia.org/wiki/Mauritania'),
               ('Niger', 'https://en.wikipedia.org/wiki/Niger'),
               ('Senegal', 'https://en.wikipedia.org/wiki/Senegal')],
    'neigh_num': 7},
  { 'border_len_km': 0,
    'border_len_mi': 0,
    'country_name': 'Malta',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Malta',
    'neigh': [],
    'neigh_num': 0},
  { 'border_len_km': 0,
    'border_len_mi': 0,
    'country_name': 'Marshall Islands',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Marshall_Islands',
    'neigh': [],
    'neigh_num': 0},
  { 'border_len_km': 5074,
    'border_len_mi': 3153,
    'country_name': 'Mauritania',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Mauritania',
    'neigh': [ ('Algeria', 'https://en.wikipedia.org/wiki/Algeria'),
               ('Mali', 'https://en.wikipedia.org/wiki/Mali'),
               ('Senegal', 'https://en.wikipedia.org/wiki/Senegal'),
               ('Western Sahara', 'https://en.wikipedia.org/wiki/Western_Sahara')],
    'neigh_num': 4},
  { 'border_len_km': 0,
    'border_len_mi': 0,
    'country_name': 'Mauritius',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Mauritius',
    'neigh': [],
    'neigh_num': 0},
  { 'border_len_km': 4353,
    'border_len_mi': 2705,
    'country_name': 'Mexico',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Mexico',
    'neigh': [ ('Belize', 'https://en.wikipedia.org/wiki/Belize'),
               ('Guatemala', 'https://en.wikipedia.org/wiki/Guatemala'),
               ('United States', 'https://en.wikipedia.org/wiki/United_States')],
    'neigh_num': 3},
  { 'border_len_km': 1389,
    'border_len_mi': 863,
    'country_name': 'Moldova',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Moldova',
    'neigh': [ ('Romania', 'https://en.wikipedia.org/wiki/Romania'),
               ('Ukraine', 'https://en.wikipedia.org/wiki/Ukraine')],
    'neigh_num': 2},
  { 'border_len_km': 4,
    'border_len_mi': 2,
    'country_name': 'Monaco',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Monaco',
    'neigh': [('France', 'https://en.wikipedia.org/wiki/France')],
    'neigh_num': 1},
  { 'border_len_km': 8220,
    'border_len_mi': 5110,
    'country_name': 'Mongolia',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Mongolia',
    'neigh': [('China', 'https://en.wikipedia.org/wiki/China'), ('Russia', 'https://en.wikipedia.org/wiki/Russia')],
    'neigh_num': 2},
  { 'border_len_km': 625,
    'border_len_mi': 388,
    'country_name': 'Montenegro',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Montenegro',
    'neigh': [ ('Albania', 'https://en.wikipedia.org/wiki/Albania'),
               ('Bosnia and Herzegovina', 'https://en.wikipedia.org/wiki/Bosnia_and_Herzegovina'),
               ('Croatia', 'https://en.wikipedia.org/wiki/Croatia'),
               ('Kosovo', 'https://en.wikipedia.org/wiki/Kosovo'),
               ('Serbia', 'https://en.wikipedia.org/wiki/Serbia')],
    'neigh_num': 5},
  { 'border_len_km': 2018,
    'border_len_mi': 1254,
    'country_name': 'Morocco',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Morocco',
    'neigh': [ ('Algeria', 'https://en.wikipedia.org/wiki/Algeria'),
               ('Spain', 'https://en.wikipedia.org/wiki/Spain'),
               ('Western Sahara', 'https://en.wikipedia.org/wiki/Western_Sahara')],
    'neigh_num': 3},
  { 'border_len_km': 4571,
    'border_len_mi': 2840,
    'country_name': 'Mozambique',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Mozambique',
    'neigh': [ ('Eswatini', 'https://en.wikipedia.org/wiki/Eswatini'),
               ('Malawi', 'https://en.wikipedia.org/wiki/Malawi'),
               ('South Africa', 'https://en.wikipedia.org/wiki/South_Africa'),
               ('Tanzania', 'https://en.wikipedia.org/wiki/Tanzania'),
               ('Zambia', 'https://en.wikipedia.org/wiki/Zambia'),
               ('Zimbabwe', 'https://en.wikipedia.org/wiki/Zimbabwe')],
    'neigh_num': 6},
  { 'border_len_km': 5876,
    'border_len_mi': 3651,
    'country_name': 'Myanmar',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Myanmar',
    'neigh': [ ('Bangladesh', 'https://en.wikipedia.org/wiki/Bangladesh'),
               ('China', 'https://en.wikipedia.org/wiki/China'),
               ('India', 'https://en.wikipedia.org/wiki/India'),
               ('Laos', 'https://en.wikipedia.org/wiki/Laos'),
               ('Thailand', 'https://en.wikipedia.org/wiki/Thailand')],
    'neigh_num': 5},
  { 'border_len_km': 3936,
    'border_len_mi': 2446,
    'country_name': 'Namibia',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Namibia',
    'neigh': [ ('Angola', 'https://en.wikipedia.org/wiki/Angola'),
               ('Botswana', 'https://en.wikipedia.org/wiki/Botswana'),
               ('South Africa', 'https://en.wikipedia.org/wiki/South_Africa'),
               ('Zambia', 'https://en.wikipedia.org/wiki/Zambia')],
    'neigh_num': 4},
  { 'border_len_km': 0,
    'border_len_mi': 0,
    'country_name': 'Nauru',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Nauru',
    'neigh': [],
    'neigh_num': 0},
  { 'border_len_km': 2926,
    'border_len_mi': 1818,
    'country_name': 'Nepal',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Nepal',
    'neigh': [('China', 'https://en.wikipedia.org/wiki/China'), ('India', 'https://en.wikipedia.org/wiki/India')],
    'neigh_num': 2},
  { 'border_len_km': 1027,
    'border_len_mi': 638,
    'country_name': 'Netherlands',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Netherlands',
    'neigh': [ ('Belgium', 'https://en.wikipedia.org/wiki/Belgium'),
               ('Germany', 'https://en.wikipedia.org/wiki/Germany')],
    'neigh_num': 2},
  { 'border_len_km': 0,
    'border_len_mi': 0,
    'country_name': 'New Zealand',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/New_Zealand',
    'neigh': [],
    'neigh_num': 0},
  { 'border_len_km': 1231,
    'border_len_mi': 765,
    'country_name': 'Nicaragua',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Nicaragua',
    'neigh': [ ('Costa Rica', 'https://en.wikipedia.org/wiki/Costa_Rica'),
               ('Honduras', 'https://en.wikipedia.org/wiki/Honduras')],
    'neigh_num': 2},
  { 'border_len_km': 5697,
    'border_len_mi': 3540,
    'country_name': 'Niger',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Niger',
    'neigh': [ ('Algeria', 'https://en.wikipedia.org/wiki/Algeria'),
               ('Benin', 'https://en.wikipedia.org/wiki/Benin'),
               ('Burkina Faso', 'https://en.wikipedia.org/wiki/Burkina_Faso'),
               ('Chad', 'https://en.wikipedia.org/wiki/Chad'),
               ('Libya', 'https://en.wikipedia.org/wiki/Libya'),
               ('Mali', 'https://en.wikipedia.org/wiki/Mali'),
               ('Nigeria', 'https://en.wikipedia.org/wiki/Nigeria')],
    'neigh_num': 7},
  { 'border_len_km': 4047,
    'border_len_mi': 2515,
    'country_name': 'Nigeria',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Nigeria',
    'neigh': [ ('Benin', 'https://en.wikipedia.org/wiki/Benin'),
               ('Cameroon', 'https://en.wikipedia.org/wiki/Cameroon'),
               ('Chad', 'https://en.wikipedia.org/wiki/Chad'),
               ('Niger', 'https://en.wikipedia.org/wiki/Niger')],
    'neigh_num': 4},
  { 'border_len_km': 1673,
    'border_len_mi': 1040,
    'country_name': 'North Korea',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/North_Korea',
    'neigh': [ ('China', 'https://en.wikipedia.org/wiki/China'),
               ('Russia', 'https://en.wikipedia.org/wiki/Russia'),
               ('South Korea', 'https://en.wikipedia.org/wiki/South_Korea')],
    'neigh_num': 3},
  { 'border_len_km': 766,
    'border_len_mi': 476,
    'country_name': 'North Macedonia',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/North_Macedonia',
    'neigh': [ ('Albania', 'https://en.wikipedia.org/wiki/Albania'),
               ('Bulgaria', 'https://en.wikipedia.org/wiki/Bulgaria'),
               ('Greece', 'https://en.wikipedia.org/wiki/Greece'),
               ('Kosovo', 'https://en.wikipedia.org/wiki/Kosovo'),
               ('Serbia', 'https://en.wikipedia.org/wiki/Serbia')],
    'neigh_num': 5},
  { 'border_len_km': 2551,
    'border_len_mi': 1585,
    'country_name': 'Norway',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Norway',
    'neigh': [ ('Finland', 'https://en.wikipedia.org/wiki/Finland'),
               ('Russia', 'https://en.wikipedia.org/wiki/Russia'),
               ('Sweden', 'https://en.wikipedia.org/wiki/Sweden')],
    'neigh_num': 3},
  { 'border_len_km': 1374,
    'border_len_mi': 854,
    'country_name': 'Oman',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Oman',
    'neigh': [ ('Saudi Arabia', 'https://en.wikipedia.org/wiki/Saudi_Arabia'),
               ('United Arab Emirates', 'https://en.wikipedia.org/wiki/United_Arab_Emirates'),
               ('Yemen', 'https://en.wikipedia.org/wiki/Yemen')],
    'neigh_num': 3},
  { 'border_len_km': 6774,
    'border_len_mi': 4209,
    'country_name': 'Pakistan',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Pakistan',
    'neigh': [ ('Afghanistan', 'https://en.wikipedia.org/wiki/Afghanistan'),
               ('China', 'https://en.wikipedia.org/wiki/China'),
               ('India', 'https://en.wikipedia.org/wiki/India'),
               ('Iran', 'https://en.wikipedia.org/wiki/Iran')],
    'neigh_num': 4},
  { 'border_len_km': 0,
    'border_len_mi': 0,
    'country_name': 'Palau',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Palau',
    'neigh': [],
    'neigh_num': 0},
  { 'border_len_km': 555,
    'border_len_mi': 345,
    'country_name': 'Panama',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Panama',
    'neigh': [ ('Colombia', 'https://en.wikipedia.org/wiki/Colombia'),
               ('Costa Rica', 'https://en.wikipedia.org/wiki/Costa_Rica')],
    'neigh_num': 2},
  { 'border_len_km': 820,
    'border_len_mi': 510,
    'country_name': 'Papua New Guinea',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Papua_New_Guinea',
    'neigh': [('Indonesia', 'https://en.wikipedia.org/wiki/Indonesia')],
    'neigh_num': 1},
  { 'border_len_km': 3920,
    'border_len_mi': 2440,
    'country_name': 'Paraguay',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Paraguay',
    'neigh': [ ('Argentina', 'https://en.wikipedia.org/wiki/Argentina'),
               ('Bolivia', 'https://en.wikipedia.org/wiki/Bolivia'),
               ('Brazil', 'https://en.wikipedia.org/wiki/Brazil')],
    'neigh_num': 3},
  { 'border_len_km': 5536,
    'border_len_mi': 3440,
    'country_name': 'Peru',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Peru',
    'neigh': [ ('Bolivia', 'https://en.wikipedia.org/wiki/Bolivia'),
               ('Brazil', 'https://en.wikipedia.org/wiki/Brazil'),
               ('Chile', 'https://en.wikipedia.org/wiki/Chile'),
               ('Colombia', 'https://en.wikipedia.org/wiki/Colombia'),
               ('Ecuador', 'https://en.wikipedia.org/wiki/Ecuador')],
    'neigh_num': 5},
  { 'border_len_km': 0,
    'border_len_mi': 0,
    'country_name': 'Philippines',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Philippines',
    'neigh': [],
    'neigh_num': 0},
  { 'border_len_km': 2788,
    'border_len_mi': 1732,
    'country_name': 'Poland',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Poland',
    'neigh': [ ('Belarus', 'https://en.wikipedia.org/wiki/Belarus'),
               ('Czech Republic', 'https://en.wikipedia.org/wiki/Czech_Republic'),
               ('Germany', 'https://en.wikipedia.org/wiki/Germany'),
               ('Lithuania', 'https://en.wikipedia.org/wiki/Lithuania'),
               ('Russia', 'https://en.wikipedia.org/wiki/Russia'),
               ('Slovakia', 'https://en.wikipedia.org/wiki/Slovakia'),
               ('Ukraine', 'https://en.wikipedia.org/wiki/Ukraine')],
    'neigh_num': 7},
  { 'border_len_km': 1214,
    'border_len_mi': 754,
    'country_name': 'Portugal',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Portugal',
    'neigh': [('Spain', 'https://en.wikipedia.org/wiki/Spain')],
    'neigh_num': 1},
  { 'border_len_km': 60,
    'border_len_mi': 37,
    'country_name': 'Qatar',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Qatar',
    'neigh': [('Saudi Arabia', 'https://en.wikipedia.org/wiki/Saudi_Arabia')],
    'neigh_num': 1},
  { 'border_len_km': 499,
    'border_len_mi': 310,
    'country_name': 'Republic of Ireland',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Republic_of_Ireland',
    'neigh': [('United Kingdom', 'https://en.wikipedia.org/wiki/United_Kingdom')],
    'neigh_num': 1},
  { 'border_len_km': 5504,
    'border_len_mi': 3420,
    'country_name': 'Republic of the Congo',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Republic_of_the_Congo',
    'neigh': [ ('Angola', 'https://en.wikipedia.org/wiki/Angola'),
               ('Cameroon', 'https://en.wikipedia.org/wiki/Cameroon'),
               ('Central African Republic', 'https://en.wikipedia.org/wiki/Central_African_Republic'),
               ('Democratic Republic of the Congo', 'https://en.wikipedia.org/wiki/Democratic_Republic_of_the_Congo'),
               ('Gabon', 'https://en.wikipedia.org/wiki/Gabon')],
    'neigh_num': 5},
  { 'border_len_km': 2508,
    'border_len_mi': 1558,
    'country_name': 'Romania',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Romania',
    'neigh': [ ('Bulgaria', 'https://en.wikipedia.org/wiki/Bulgaria'),
               ('Hungary', 'https://en.wikipedia.org/wiki/Hungary'),
               ('Moldova', 'https://en.wikipedia.org/wiki/Moldova'),
               ('Serbia', 'https://en.wikipedia.org/wiki/Serbia'),
               ('Ukraine', 'https://en.wikipedia.org/wiki/Ukraine')],
    'neigh_num': 5},
  { 'border_len_km': 20017,
    'border_len_mi': 12438,
    'country_name': 'Russia',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Russia',
    'neigh': [ ('Abkhazia', 'https://en.wikipedia.org/wiki/Abkhazia'),
               ('Azerbaijan', 'https://en.wikipedia.org/wiki/Azerbaijan'),
               ('Belarus', 'https://en.wikipedia.org/wiki/Belarus'),
               ('China', 'https://en.wikipedia.org/wiki/China'),
               ('Estonia', 'https://en.wikipedia.org/wiki/Estonia'),
               ('Finland', 'https://en.wikipedia.org/wiki/Finland'),
               ('Georgia (country)', 'https://en.wikipedia.org/wiki/Georgia_(country)'),
               ('Kazakhstan', 'https://en.wikipedia.org/wiki/Kazakhstan'),
               ('Latvia', 'https://en.wikipedia.org/wiki/Latvia'),
               ('Lithuania', 'https://en.wikipedia.org/wiki/Lithuania'),
               ('Mongolia', 'https://en.wikipedia.org/wiki/Mongolia'),
               ('North Korea', 'https://en.wikipedia.org/wiki/North_Korea'),
               ('Norway', 'https://en.wikipedia.org/wiki/Norway'),
               ('Poland', 'https://en.wikipedia.org/wiki/Poland'),
               ('South Ossetia', 'https://en.wikipedia.org/wiki/South_Ossetia'),
               ('Ukraine', 'https://en.wikipedia.org/wiki/Ukraine')],
    'neigh_num': 14},
  { 'border_len_km': 893,
    'border_len_mi': 555,
    'country_name': 'Rwanda',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Rwanda',
    'neigh': [ ('Burundi', 'https://en.wikipedia.org/wiki/Burundi'),
               ('Democratic Republic of the Congo', 'https://en.wikipedia.org/wiki/Democratic_Republic_of_the_Congo'),
               ('Tanzania', 'https://en.wikipedia.org/wiki/Tanzania'),
               ('Uganda', 'https://en.wikipedia.org/wiki/Uganda')],
    'neigh_num': 4},
  { 'border_len_km': 0,
    'border_len_mi': 0,
    'country_name': 'Saint Kitts and Nevis',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Saint_Kitts_and_Nevis',
    'neigh': [],
    'neigh_num': 0},
  { 'border_len_km': 0,
    'border_len_mi': 0,
    'country_name': 'Saint Lucia',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Saint_Lucia',
    'neigh': [],
    'neigh_num': 0},
  { 'border_len_km': 0,
    'border_len_mi': 0,
    'country_name': 'Saint Vincent and the Grenadines',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Saint_Vincent_and_the_Grenadines',
    'neigh': [],
    'neigh_num': 0},
  { 'border_len_km': 0,
    'border_len_mi': 0,
    'country_name': 'Samoa',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Samoa',
    'neigh': [],
    'neigh_num': 0},
  { 'border_len_km': 39,
    'border_len_mi': 24,
    'country_name': 'San Marino',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/San_Marino',
    'neigh': [('Italy', 'https://en.wikipedia.org/wiki/Italy')],
    'neigh_num': 1},
  { 'border_len_km': 4431,
    'border_len_mi': 2753,
    'country_name': 'Saudi Arabia',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Saudi_Arabia',
    'neigh': [ ('Iraq', 'https://en.wikipedia.org/wiki/Iraq'),
               ('Jordan', 'https://en.wikipedia.org/wiki/Jordan'),
               ('Kuwait', 'https://en.wikipedia.org/wiki/Kuwait'),
               ('Oman', 'https://en.wikipedia.org/wiki/Oman'),
               ('Qatar', 'https://en.wikipedia.org/wiki/Qatar'),
               ('United Arab Emirates', 'https://en.wikipedia.org/wiki/United_Arab_Emirates'),
               ('Yemen', 'https://en.wikipedia.org/wiki/Yemen')],
    'neigh_num': 7},
  { 'border_len_km': 2640,
    'border_len_mi': 1640,
    'country_name': 'Senegal',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Senegal',
    'neigh': [ ('Guinea', 'https://en.wikipedia.org/wiki/Guinea'),
               ('Guinea-Bissau', 'https://en.wikipedia.org/wiki/Guinea-Bissau'),
               ('Mali', 'https://en.wikipedia.org/wiki/Mali'),
               ('Mauritania', 'https://en.wikipedia.org/wiki/Mauritania'),
               ('The Gambia', 'https://en.wikipedia.org/wiki/The_Gambia')],
    'neigh_num': 5},
  { 'border_len_km': 2027,
    'border_len_mi': 1260,
    'country_name': 'Serbia',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Serbia',
    'neigh': [ ('Bosnia and Herzegovina', 'https://en.wikipedia.org/wiki/Bosnia_and_Herzegovina'),
               ('Bulgaria', 'https://en.wikipedia.org/wiki/Bulgaria'),
               ('Croatia', 'https://en.wikipedia.org/wiki/Croatia'),
               ('Hungary', 'https://en.wikipedia.org/wiki/Hungary'),
               ('Kosovo', 'https://en.wikipedia.org/wiki/Kosovo'),
               ('Montenegro', 'https://en.wikipedia.org/wiki/Montenegro'),
               ('North Macedonia', 'https://en.wikipedia.org/wiki/North_Macedonia'),
               ('Romania', 'https://en.wikipedia.org/wiki/Romania')],
    'neigh_num': 8},
  { 'border_len_km': 0,
    'border_len_mi': 0,
    'country_name': 'Seychelles',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Seychelles',
    'neigh': [],
    'neigh_num': 0},
  { 'border_len_km': 958,
    'border_len_mi': 595,
    'country_name': 'Sierra Leone',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Sierra_Leone',
    'neigh': [('Guinea', 'https://en.wikipedia.org/wiki/Guinea'), ('Liberia', 'https://en.wikipedia.org/wiki/Liberia')],
    'neigh_num': 2},
  { 'border_len_km': 0,
    'border_len_mi': 0,
    'country_name': 'Singapore',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Singapore',
    'neigh': [],
    'neigh_num': 0},
  { 'border_len_km': 1524,
    'border_len_mi': 947,
    'country_name': 'Slovakia',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Slovakia',
    'neigh': [ ('Austria', 'https://en.wikipedia.org/wiki/Austria'),
               ('Czech Republic', 'https://en.wikipedia.org/wiki/Czech_Republic'),
               ('Hungary', 'https://en.wikipedia.org/wiki/Hungary'),
               ('Poland', 'https://en.wikipedia.org/wiki/Poland'),
               ('Ukraine', 'https://en.wikipedia.org/wiki/Ukraine')],
    'neigh_num': 5},
  { 'border_len_km': 1334,
    'border_len_mi': 829,
    'country_name': 'Slovenia',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Slovenia',
    'neigh': [ ('Austria', 'https://en.wikipedia.org/wiki/Austria'),
               ('Croatia', 'https://en.wikipedia.org/wiki/Croatia'),
               ('Hungary', 'https://en.wikipedia.org/wiki/Hungary'),
               ('Italy', 'https://en.wikipedia.org/wiki/Italy')],
    'neigh_num': 4},
  { 'border_len_km': 0,
    'border_len_mi': 0,
    'country_name': 'Solomon Islands',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Solomon_Islands',
    'neigh': [],
    'neigh_num': 0},
  { 'border_len_km': 2340,
    'border_len_mi': 1450,
    'country_name': 'Somalia',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Somalia',
    'neigh': [ ('Djibouti', 'https://en.wikipedia.org/wiki/Djibouti'),
               ('Ethiopia', 'https://en.wikipedia.org/wiki/Ethiopia'),
               ('Kenya', 'https://en.wikipedia.org/wiki/Kenya')],
    'neigh_num': 3},
  { 'border_len_km': 4862,
    'border_len_mi': 3021,
    'country_name': 'South Africa',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/South_Africa',
    'neigh': [ ('Botswana', 'https://en.wikipedia.org/wiki/Botswana'),
               ('Eswatini', 'https://en.wikipedia.org/wiki/Eswatini'),
               ('Lesotho', 'https://en.wikipedia.org/wiki/Lesotho'),
               ('Mozambique', 'https://en.wikipedia.org/wiki/Mozambique'),
               ('Namibia', 'https://en.wikipedia.org/wiki/Namibia'),
               ('Zimbabwe', 'https://en.wikipedia.org/wiki/Zimbabwe')],
    'neigh_num': 6},
  { 'border_len_km': 238,
    'border_len_mi': 148,
    'country_name': 'South Korea',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/South_Korea',
    'neigh': [('North Korea', 'https://en.wikipedia.org/wiki/North_Korea')],
    'neigh_num': 1},
  { 'border_len_km': 466,
    'border_len_mi': 290,
    'country_name': 'South Ossetia',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/South_Ossetia',
    'neigh': [ ('Georgia (country)', 'https://en.wikipedia.org/wiki/Georgia_(country)'),
               ('Russia', 'https://en.wikipedia.org/wiki/Russia')],
    'neigh_num': 2},
  { 'border_len_km': 4797,
    'border_len_mi': 2981,
    'country_name': 'South Sudan',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/South_Sudan',
    'neigh': [ ('Central African Republic', 'https://en.wikipedia.org/wiki/Central_African_Republic'),
               ('Democratic Republic of the Congo', 'https://en.wikipedia.org/wiki/Democratic_Republic_of_the_Congo'),
               ('Ethiopia', 'https://en.wikipedia.org/wiki/Ethiopia'),
               ('Kenya', 'https://en.wikipedia.org/wiki/Kenya'),
               ('Sudan', 'https://en.wikipedia.org/wiki/Sudan'),
               ('Uganda', 'https://en.wikipedia.org/wiki/Uganda')],
    'neigh_num': 6},
  { 'border_len_km': 1918,
    'border_len_mi': 1192,
    'country_name': 'Spain',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Spain',
    'neigh': [ ('Andorra', 'https://en.wikipedia.org/wiki/Andorra'),
               ('France', 'https://en.wikipedia.org/wiki/France'),
               ('Gibraltar', 'https://en.wikipedia.org/wiki/Gibraltar'),
               ('Morocco', 'https://en.wikipedia.org/wiki/Morocco'),
               ('Portugal', 'https://en.wikipedia.org/wiki/Portugal')],
    'neigh_num': 5},
  { 'border_len_km': 0,
    'border_len_mi': 0,
    'country_name': 'Sri Lanka',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Sri_Lanka',
    'neigh': [],
    'neigh_num': 0},
  { 'border_len_km': 466,
    'border_len_mi': 290,
    'country_name': 'State of Palestine',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/State_of_Palestine',
    'neigh': [ ('Egypt', 'https://en.wikipedia.org/wiki/Egypt'),
               ('Israel', 'https://en.wikipedia.org/wiki/Israel'),
               ('Jordan', 'https://en.wikipedia.org/wiki/Jordan')],
    'neigh_num': 3},
  { 'border_len_km': 6764,
    'border_len_mi': 4203,
    'country_name': 'Sudan',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Sudan',
    'neigh': [ ('Central African Republic', 'https://en.wikipedia.org/wiki/Central_African_Republic'),
               ('Chad', 'https://en.wikipedia.org/wiki/Chad'),
               ('Egypt', 'https://en.wikipedia.org/wiki/Egypt'),
               ('Eritrea', 'https://en.wikipedia.org/wiki/Eritrea'),
               ('Ethiopia', 'https://en.wikipedia.org/wiki/Ethiopia'),
               ('Libya', 'https://en.wikipedia.org/wiki/Libya'),
               ('South Sudan', 'https://en.wikipedia.org/wiki/South_Sudan')],
    'neigh_num': 7},
  { 'border_len_km': 1707,
    'border_len_mi': 1061,
    'country_name': 'Suriname',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Suriname',
    'neigh': [ ('Brazil', 'https://en.wikipedia.org/wiki/Brazil'),
               ('France', 'https://en.wikipedia.org/wiki/France'),
               ('French Guiana', 'https://en.wikipedia.org/wiki/French_Guiana'),
               ('Guyana', 'https://en.wikipedia.org/wiki/Guyana')],
    'neigh_num': 3},
  { 'border_len_km': 2233,
    'border_len_mi': 1388,
    'country_name': 'Sweden',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Sweden',
    'neigh': [ ('Finland', 'https://en.wikipedia.org/wiki/Finland'),
               ('Norway', 'https://en.wikipedia.org/wiki/Norway'),
               ('Åland Islands', 'https://en.wikipedia.org/wiki/%C3%85land_Islands')],
    'neigh_num': 2},
  { 'border_len_km': 1852,
    'border_len_mi': 1151,
    'country_name': 'Switzerland',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Switzerland',
    'neigh': [ ('Austria', 'https://en.wikipedia.org/wiki/Austria'),
               ('France', 'https://en.wikipedia.org/wiki/France'),
               ('Germany', 'https://en.wikipedia.org/wiki/Germany'),
               ('Italy', 'https://en.wikipedia.org/wiki/Italy'),
               ('Liechtenstein', 'https://en.wikipedia.org/wiki/Liechtenstein')],
    'neigh_num': 5},
  { 'border_len_km': 2253,
    'border_len_mi': 1400,
    'country_name': 'Syria',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Syria',
    'neigh': [ ('Iraq', 'https://en.wikipedia.org/wiki/Iraq'),
               ('Israel', 'https://en.wikipedia.org/wiki/Israel'),
               ('Jordan', 'https://en.wikipedia.org/wiki/Jordan'),
               ('Lebanon', 'https://en.wikipedia.org/wiki/Lebanon'),
               ('Turkey', 'https://en.wikipedia.org/wiki/Turkey')],
    'neigh_num': 5},
  { 'border_len_km': 0,
    'border_len_mi': 0,
    'country_name': 'São Tomé and Príncipe',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/S%C3%A3o_Tom%C3%A9_and_Pr%C3%ADncipe',
    'neigh': [],
    'neigh_num': 0},
  { 'border_len_km': 3651,
    'border_len_mi': 2269,
    'country_name': 'Tajikistan',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Tajikistan',
    'neigh': [ ('Afghanistan', 'https://en.wikipedia.org/wiki/Afghanistan'),
               ('China', 'https://en.wikipedia.org/wiki/China'),
               ('Kyrgyzstan', 'https://en.wikipedia.org/wiki/Kyrgyzstan'),
               ('Uzbekistan', 'https://en.wikipedia.org/wiki/Uzbekistan')],
    'neigh_num': 4},
  { 'border_len_km': 3861,
    'border_len_mi': 2399,
    'country_name': 'Tanzania',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Tanzania',
    'neigh': [ ('Burundi', 'https://en.wikipedia.org/wiki/Burundi'),
               ('Democratic Republic of the Congo', 'https://en.wikipedia.org/wiki/Democratic_Republic_of_the_Congo'),
               ('Kenya', 'https://en.wikipedia.org/wiki/Kenya'),
               ('Malawi', 'https://en.wikipedia.org/wiki/Malawi'),
               ('Mozambique', 'https://en.wikipedia.org/wiki/Mozambique'),
               ('Rwanda', 'https://en.wikipedia.org/wiki/Rwanda'),
               ('Uganda', 'https://en.wikipedia.org/wiki/Uganda'),
               ('Zambia', 'https://en.wikipedia.org/wiki/Zambia')],
    'neigh_num': 8},
  { 'border_len_km': 4863,
    'border_len_mi': 3022,
    'country_name': 'Thailand',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Thailand',
    'neigh': [ ('Cambodia', 'https://en.wikipedia.org/wiki/Cambodia'),
               ('Laos', 'https://en.wikipedia.org/wiki/Laos'),
               ('Malaysia', 'https://en.wikipedia.org/wiki/Malaysia'),
               ('Myanmar', 'https://en.wikipedia.org/wiki/Myanmar')],
    'neigh_num': 4},
  { 'border_len_km': 0,
    'border_len_mi': 0,
    'country_name': 'The Bahamas',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/The_Bahamas',
    'neigh': [],
    'neigh_num': 0},
  { 'border_len_km': 740,
    'border_len_mi': 460,
    'country_name': 'The Gambia',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/The_Gambia',
    'neigh': [('Senegal', 'https://en.wikipedia.org/wiki/Senegal')],
    'neigh_num': 1},
  { 'border_len_km': 1647,
    'border_len_mi': 1023,
    'country_name': 'Togo',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Togo',
    'neigh': [ ('Benin', 'https://en.wikipedia.org/wiki/Benin'),
               ('Burkina Faso', 'https://en.wikipedia.org/wiki/Burkina_Faso'),
               ('Ghana', 'https://en.wikipedia.org/wiki/Ghana')],
    'neigh_num': 3},
  { 'border_len_km': 0,
    'border_len_mi': 0,
    'country_name': 'Tonga',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Tonga',
    'neigh': [],
    'neigh_num': 0},
  { 'border_len_km': 0,
    'border_len_mi': 0,
    'country_name': 'Trinidad and Tobago',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Trinidad_and_Tobago',
    'neigh': [],
    'neigh_num': 0},
  { 'border_len_km': 1469,
    'border_len_mi': 913,
    'country_name': 'Tunisia',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Tunisia',
    'neigh': [('Algeria', 'https://en.wikipedia.org/wiki/Algeria'), ('Libya', 'https://en.wikipedia.org/wiki/Libya')],
    'neigh_num': 2},
  { 'border_len_km': 2648,
    'border_len_mi': 1645,
    'country_name': 'Turkey',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Turkey',
    'neigh': [ ('Armenia', 'https://en.wikipedia.org/wiki/Armenia'),
               ('Azerbaijan', 'https://en.wikipedia.org/wiki/Azerbaijan'),
               ('Bulgaria', 'https://en.wikipedia.org/wiki/Bulgaria'),
               ('Georgia (country)', 'https://en.wikipedia.org/wiki/Georgia_(country)'),
               ('Greece', 'https://en.wikipedia.org/wiki/Greece'),
               ('Iran', 'https://en.wikipedia.org/wiki/Iran'),
               ('Iraq', 'https://en.wikipedia.org/wiki/Iraq'),
               ('Syria', 'https://en.wikipedia.org/wiki/Syria')],
    'neigh_num': 8},
  { 'border_len_km': 3736,
    'border_len_mi': 2321,
    'country_name': 'Turkmenistan',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Turkmenistan',
    'neigh': [ ('Afghanistan', 'https://en.wikipedia.org/wiki/Afghanistan'),
               ('Iran', 'https://en.wikipedia.org/wiki/Iran'),
               ('Kazakhstan', 'https://en.wikipedia.org/wiki/Kazakhstan'),
               ('Uzbekistan', 'https://en.wikipedia.org/wiki/Uzbekistan')],
    'neigh_num': 4},
  { 'border_len_km': 0,
    'border_len_mi': 0,
    'country_name': 'Tuvalu',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Tuvalu',
    'neigh': [],
    'neigh_num': 0},
  { 'border_len_km': 2698,
    'border_len_mi': 1676,
    'country_name': 'Uganda',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Uganda',
    'neigh': [ ('Democratic Republic of the Congo', 'https://en.wikipedia.org/wiki/Democratic_Republic_of_the_Congo'),
               ('Kenya', 'https://en.wikipedia.org/wiki/Kenya'),
               ('Rwanda', 'https://en.wikipedia.org/wiki/Rwanda'),
               ('South Sudan', 'https://en.wikipedia.org/wiki/South_Sudan'),
               ('Tanzania', 'https://en.wikipedia.org/wiki/Tanzania')],
    'neigh_num': 5},
  { 'border_len_km': 4663,
    'border_len_mi': 2897,
    'country_name': 'Ukraine',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Ukraine',
    'neigh': [ ('Belarus', 'https://en.wikipedia.org/wiki/Belarus'),
               ('Hungary', 'https://en.wikipedia.org/wiki/Hungary'),
               ('Moldova', 'https://en.wikipedia.org/wiki/Moldova'),
               ('Poland', 'https://en.wikipedia.org/wiki/Poland'),
               ('Romania', 'https://en.wikipedia.org/wiki/Romania'),
               ('Russia', 'https://en.wikipedia.org/wiki/Russia'),
               ('Slovakia', 'https://en.wikipedia.org/wiki/Slovakia')],
    'neigh_num': 7},
  { 'border_len_km': 867,
    'border_len_mi': 539,
    'country_name': 'United Arab Emirates',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/United_Arab_Emirates',
    'neigh': [ ('Oman', 'https://en.wikipedia.org/wiki/Oman'),
               ('Saudi Arabia', 'https://en.wikipedia.org/wiki/Saudi_Arabia')],
    'neigh_num': 2},
  { 'border_len_km': 499,
    'border_len_mi': 310,
    'country_name': 'United Kingdom',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/United_Kingdom',
    'neigh': [('Republic of Ireland', 'https://en.wikipedia.org/wiki/Republic_of_Ireland')],
    'neigh_num': 1},
  { 'border_len_km': 513,
    'border_len_mi': 319,
    'country_name': 'United Kingdom',
    'country_sub': [ ('Akrotiri and Dhekelia', 'https://en.wikipedia.org/wiki/Akrotiri_and_Dhekelia'),
                     ('Anguilla', 'https://en.wikipedia.org/wiki/Anguilla'),
                     ('Bermuda', 'https://en.wikipedia.org/wiki/Bermuda'),
                     ('British Indian Ocean Territory', 'https://en.wikipedia.org/wiki/British_Indian_Ocean_Territory'),
                     ('British Virgin Islands', 'https://en.wikipedia.org/wiki/British_Virgin_Islands'),
                     ('Cayman Islands', 'https://en.wikipedia.org/wiki/Cayman_Islands'),
                     ('Falkland Islands', 'https://en.wikipedia.org/wiki/Falkland_Islands'),
                     ('Gibraltar', 'https://en.wikipedia.org/wiki/Gibraltar'),
                     ('Guernsey', 'https://en.wikipedia.org/wiki/Guernsey'),
                     ('Isle of Man', 'https://en.wikipedia.org/wiki/Isle_of_Man'),
                     ('Jersey', 'https://en.wikipedia.org/wiki/Jersey'),
                     ('Montserrat', 'https://en.wikipedia.org/wiki/Montserrat'),
                     ('Pitcairn Islands', 'https://en.wikipedia.org/wiki/Pitcairn_Islands'),
                     ( 'Saint Helena, Ascension and Tristan da Cunha',
                       'https://en.wikipedia.org/wiki/Saint_Helena,_Ascension_and_Tristan_da_Cunha'),
                     ( 'South Georgia and the South Sandwich Islands',
                       'https://en.wikipedia.org/wiki/South_Georgia_and_the_South_Sandwich_Islands'),
                     ('Turks and Caicos Islands', 'https://en.wikipedia.org/wiki/Turks_and_Caicos_Islands')],
    'country_url': 'https://en.wikipedia.org/wiki/United_Kingdom',
    'neigh': [ ('Cyprus', 'https://en.wikipedia.org/wiki/Cyprus'),
               ('Republic of Ireland', 'https://en.wikipedia.org/wiki/Republic_of_Ireland'),
               ('Spain', 'https://en.wikipedia.org/wiki/Spain')],
    'neigh_num': 3},
  { 'border_len_km': 12034,
    'border_len_mi': 7478,
    'country_name': 'United States',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/United_States',
    'neigh': [('Canada', 'https://en.wikipedia.org/wiki/Canada'), ('Mexico', 'https://en.wikipedia.org/wiki/Mexico')],
    'neigh_num': 2},
  { 'border_len_km': 1564,
    'border_len_mi': 972,
    'country_name': 'Uruguay',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Uruguay',
    'neigh': [ ('Argentina', 'https://en.wikipedia.org/wiki/Argentina'),
               ('Brazil', 'https://en.wikipedia.org/wiki/Brazil')],
    'neigh_num': 2},
  { 'border_len_km': 6221,
    'border_len_mi': 3866,
    'country_name': 'Uzbekistan',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Uzbekistan',
    'neigh': [ ('Afghanistan', 'https://en.wikipedia.org/wiki/Afghanistan'),
               ('Kazakhstan', 'https://en.wikipedia.org/wiki/Kazakhstan'),
               ('Kyrgyzstan', 'https://en.wikipedia.org/wiki/Kyrgyzstan'),
               ('Tajikistan', 'https://en.wikipedia.org/wiki/Tajikistan'),
               ('Turkmenistan', 'https://en.wikipedia.org/wiki/Turkmenistan')],
    'neigh_num': 5},
  { 'border_len_km': 0,
    'border_len_mi': 0,
    'country_name': 'Vanuatu',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Vanuatu',
    'neigh': [],
    'neigh_num': 0},
  { 'border_len_km': 3,
    'border_len_mi': 2,
    'country_name': 'Vatican City',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Vatican_City',
    'neigh': [('Italy', 'https://en.wikipedia.org/wiki/Italy')],
    'neigh_num': 1},
  { 'border_len_km': 4993,
    'border_len_mi': 3103,
    'country_name': 'Venezuela',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Venezuela',
    'neigh': [ ('Brazil', 'https://en.wikipedia.org/wiki/Brazil'),
               ('Colombia', 'https://en.wikipedia.org/wiki/Colombia'),
               ('Guyana', 'https://en.wikipedia.org/wiki/Guyana')],
    'neigh_num': 3},
  { 'border_len_km': 4639,
    'border_len_mi': 2883,
    'country_name': 'Vietnam',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Vietnam',
    'neigh': [ ('Cambodia', 'https://en.wikipedia.org/wiki/Cambodia'),
               ('China', 'https://en.wikipedia.org/wiki/China'),
               ('Laos', 'https://en.wikipedia.org/wiki/Laos')],
    'neigh_num': 3},
  { 'border_len_km': 2046,
    'border_len_mi': 1271,
    'country_name': 'Western Sahara',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Western_Sahara',
    'neigh': [ ('Algeria', 'https://en.wikipedia.org/wiki/Algeria'),
               ('Mauritania', 'https://en.wikipedia.org/wiki/Mauritania'),
               ('Morocco', 'https://en.wikipedia.org/wiki/Morocco')],
    'neigh_num': 3},
  { 'border_len_km': 1746,
    'border_len_mi': 1085,
    'country_name': 'Yemen',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Yemen',
    'neigh': [ ('Oman', 'https://en.wikipedia.org/wiki/Oman'),
               ('Saudi Arabia', 'https://en.wikipedia.org/wiki/Saudi_Arabia')],
    'neigh_num': 2},
  { 'border_len_km': 5667,
    'border_len_mi': 3521,
    'country_name': 'Zambia',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Zambia',
    'neigh': [ ('Angola', 'https://en.wikipedia.org/wiki/Angola'),
               ('Botswana', 'https://en.wikipedia.org/wiki/Botswana'),
               ('Democratic Republic of the Congo', 'https://en.wikipedia.org/wiki/Democratic_Republic_of_the_Congo'),
               ('Malawi', 'https://en.wikipedia.org/wiki/Malawi'),
               ('Mozambique', 'https://en.wikipedia.org/wiki/Mozambique'),
               ('Namibia', 'https://en.wikipedia.org/wiki/Namibia'),
               ('Tanzania', 'https://en.wikipedia.org/wiki/Tanzania'),
               ('Zimbabwe', 'https://en.wikipedia.org/wiki/Zimbabwe')],
    'neigh_num': 8},
  { 'border_len_km': 3066,
    'border_len_mi': 1905,
    'country_name': 'Zimbabwe',
    'country_sub': [],
    'country_url': 'https://en.wikipedia.org/wiki/Zimbabwe',
    'neigh': [ ('Botswana', 'https://en.wikipedia.org/wiki/Botswana'),
               ('Mozambique', 'https://en.wikipedia.org/wiki/Mozambique'),
               ('South Africa', 'https://en.wikipedia.org/wiki/South_Africa'),
               ('Zambia', 'https://en.wikipedia.org/wiki/Zambia')],
    'neigh_num': 4}]
