# -*- coding: UTF-8 -*-
# source: https://www.itu.int/pub/T-SP
# license: https://www.itu.int/pub/T-SP

ITUT_MNC_INCR = \
{ 'Albania': [ ['Mobile 4 AL', '27604', 'SUP'],
               ['ONE TELECOMMUNICATIONS sh.a', '27601', 'LIR'],
               ['ALBTELECOM sh.a.', '27603', 'LIR']],
  'Angola': [['AFRICELL', '63105', 'ADD']],
  'Australia': [ ['ANGLOGOLD ASHANTI AUSTRALIA LTD', '50546', 'ADD'],
                 ['Vodafone Hutchison Australia Pty Ltd', '50512', 'LIR'],
                 ['Woodside Energy Limited', '50547', 'ADD'],
                 ['Titan ICT Pty Ltd', '50548', 'ADD'],
                 ['Pactel International Pty Ltd', '50518', 'SUP'],
                 ['Field Solutions Group Pty Ltd', '50549', 'ADD'],
                 ['Fortescue Metals Group Ltd', '50551', 'ADD'],
                 ['Optitel Pty Ltd', '50552', 'ADD'],
                 ['Shell Australia Pty Ltd', '50553', 'ADD'],
                 ['Nokia Solutions and Networks Australia Pty Ltd', '50554', 'ADD'],
                 ['Nokia Solutions and Networks Australia Pty Ltd', '50554', 'SUP'],
                 ['New South Wales Government Telecommunications Authority', '50555', 'ADD'],
                 ['Nokia Solutions and Networks Pty Ltd', '50556', 'ADD'],
                 ['UE Access Pty Ltd', '50590', 'LIR']],
  'Bahrain': [['STC Bahrain', '42606', 'ADD'], ['TAIF', '42607', 'ADD']],
  'Barbados': [ ['Neptune Communications Inc.', '342820', 'ADD'],
                ['Ozone', '342800', 'ADD'],
                ['Cable & Wireless', '342600', 'LIR'],
                ['KW Telecommunications Inc.', '342646', 'ADD']],
  'Belgium': [ ['Join Experience (Belgium)', '20640', 'SUP'],
               ['Citymesh', '20603', 'ADD'],
               ['L-Mobi Mobile', '20611', 'ADD'],
               ['FEBO Telecom', '20622', 'ADD'],
               ['TISMI', '20629', 'ADD'],
               ['e-BO Enterprises', '20699', 'ADD'],
               ['MWINGZ (Proximus/Orange Belgium)', '20604', 'ADD'],
               ['ONOFFAPP', '20634', 'ADD']],
  'Bermuda': [['FKB Net Ltd.', '35015', 'ADD'], ['Paradise Mobile', '350007', 'ADD']],
  'Bhutan': [ ['Tashi InfoComm Limited (Tashi Cell)', '40277', 'ADD'],
              ['Bhutan Telecom Limited (Bmobile)', '40211', 'LIR'],
              ['Bhutan Telecom Limited (Bmobile)', '40217', 'LIR']],
  'Brazil': [ ['Telefônica Brasil S.A.', '72406', 'LIR'],
              ['Telefônica Brasil S.A.', '72410', 'LIR'],
              ['Telefônica Brasil S.A.', '72411', 'LIR'],
              ['Telefônica Brasil S.A.', '72423', 'LIR'],
              ['TIM S.A.', '72454', 'LIR'],
              ['LIGUE', '72421', 'ADD'],
              ['SURF TELECOM S.A.', '72417', 'ADD']],
  'Brunei Darussalam': [ ['Telekom Brunei Berhad (TelBru)', '52801', 'ADD'],
                         ['Progresif Cellular Sdn Bhd (PCSB)', '52802', 'ADD'],
                         ['Unified National Networks Sdn Bhd (UNN)', '52803', 'ADD']],
  'Canada': [ ['Blue Canada Wireless Inc', '302330', 'ADD'],
              ['Star Solutions International Inc.', '302550', 'ADD'],
              ['Rogers Communications Canada Inc. (Wireless)', '302721', 'ADD'],
              ['Cogeco Connexion Inc.', '302150', 'ADD'],
              ['Blue Canada Wireless Inc', '302330', 'SUP'],
              ['Powertech Labs (experimental)', '302996', 'ADD'],
              ['Halton Regional Police Service (reserved)', '302910', 'ADD'],
              ['TNW Wireless Inc.', '302770', 'LIR'],
              ['Institut de Recherche d’Hydro-Québec (experimental)', '302998', 'ADD'],
              ['Naskapi Imuun Inc.', '302350', 'ADD'],
              ['Vocom International Telecommunications, Inc', '302848', 'ADD'],
              ['ISP Telecom', '302230', 'ADD'],
              ['Cogeco Connexion Inc.', '302151', 'ADD'],
              ['Cogeco Connexion Inc.', '302152', 'ADD'],
              ['Ligado Networks Corp.', '302570', 'LIR'],
              ['Fibernetics Corporation', '302140', 'ADD'],
              ['Rogers Communications Canada Inc.', '302741', 'ADD'],
              ['Rogers Communications Canada Inc.', '302740', 'LIR'],
              ['Halton Regional Police', '302910', 'LIR']],
  'Cayman Islands': [['WestTel Ltd., trading as Logic', '346001', 'ADD']],
  'Chile': [['WILL S.A.', '73026', 'ADD'], ['Cibeles Telecom S.A.', '73027', 'ADD']],
  'Cyprus': [['Mundio Mobile Cyprus Ltd', '28023', 'SUP'], ['CYTA', '28002', 'ADD']],
  'Czech Rep.': [ ['T-Mobile Czech Republic a.s.', '23007', 'ADD'],
                  ['O2 Czech Republic a.s.', '23002', 'LIR'],
                  ['Nordic Telecom s.r.o.', '23004', 'LIR'],
                  ['Sprava zeleznic, statni organizace', '23098', 'LIR'],
                  ['Uniphone, s.r.o.', '23009', 'ADD'],
                  ['incrate s.r.o.', '23011', 'ADD'],
                  ['Nordic Telecom Regional s.r.o.', '23004', 'LIR']],
  'Denmark': [ ['Telia Danmark', '23896', 'ADD'],
               ['Gotanet AB', '23817', 'ADD'],
               ['Cobira ApS', '23888', 'ADD'],
               ['Telenor', '23877', 'SUP']],
  'Estonia': [ ['SmartTel Plus OÜ', '24816', 'ADD'],
               ['Premium Net International S.R.L. Eesti filiaal', '24815', 'SUP'],
               ['CSC Telecom Estonia OÜ', '24805', 'ADD'],
               ['Baltergo OÜ', '24817', 'ADD'],
               ['CLOUD COMMUNICATIONS OÜ', '24818', 'ADD'],
               ['OkTelecom OÜ', '24819', 'ADD'],
               ['DOTT Telecom OÜ', '24820', 'ADD'],
               ['Tismi B.V.', '24821', 'ADD'],
               ['M2MConnect OÜ', '24822', 'ADD'],
               ['Novametro OÜ', '24824', 'ADD'],
               ['Eurofed OÜ', '24825', 'ADD'],
               ['IT-Decision Telecom OÜ', '24826', 'ADD'],
               ['Nord Connect OÜ', '24828', 'ADD'],
               ['Eurofed OÜ', '24825', 'SUP'],
               ['SkyTel OÜ', '24829', 'ADD'],
               ['Baltergo OÜ', '24817', 'SUP'],
               ['Mediafon Carrier Services OÜ', '24830', 'ADD']],
  'Faroe Islands': [['Sp/f Tosa', '28803', 'SUP'], ['Faroese Telecom', '28810', 'ADD']],
  'France': [ ['Thales communications & Security', '20893', 'SUP'],
              ['Orange', '20895', 'SUP'],
              ['Société Air France', '20898', 'SUP'],
              ['Truphone France', '20812', 'ADD'],
              ['Cellhire (France)', '20834', 'ADD'],
              ['Free mobile', '20835', 'ADD'],
              ['Free mobile', '20836', 'ADD'],
              ['IP Directions', '20837', 'ADD'],
              ['Lebara France Limited', '20838', 'ADD'],
              ['Netwo', '20839', 'ADD'],
              ['Butachimie', '208501', 'ADD'],
              ['EDF', '208502', 'ADD'],
              ['GIP Vendée numérique', '208701', 'ADD'],
              ['17-Numerique', '208702', 'ADD'],
              ['Nivertel', '208703', 'ADD'],
              ['Axione Limousin', '208704', 'ADD'],
              ['Hautes-Pyrénées Numérique', '208705', 'ADD'],
              ['Tours Métropole Numérique', '208706', 'ADD'],
              ['Sartel THD', '208707', 'ADD'],
              ['Melis@ territoires ruraux', '208708', 'ADD'],
              ['Quimper communauté télécom', '208709', 'ADD'],
              ['Losange', '208710', 'ADD'],
              ['Nomotech', '208711', 'ADD'],
              ["Syndicat Audois d'énergies et du Numérique", '208712', 'ADD'],
              ['SD NUM SAS', '208713', 'ADD'],
              ["Département de l'Isère", '208714', 'ADD'],
              ['Haute-Garonne numérique', '20819', 'LIR'],
              ['Bouygues Telecom Business - Distribution', '20826', 'LIR'],
              ['Airmob Infra Full', '20828', 'LIR'],
              ['Syma', '20830', 'LIR'],
              ['Syndicat mixte La Fibre64', '20833', 'LIR'],
              ['Airbus defence and space SAS', '20887', 'LIR'],
              ['Hub One', '20889', 'LIR'],
              ['Région Bourgogne-Franche-Comté', '20896', 'LIR']],
  'French Guiana': [['Guyane Téléphone Mobile', '34011', 'SUP'], ['Free Caraïbe', '74204', 'ADD']],
  'Georgia': [ ['"Datacomm" LTD', '28212', 'ADD'],
               ['"Asanet" LTD', '28213', 'ADD'],
               ['"Datahouseglobal” LTD', '28214', 'ADD'],
               ['"Telecom1" LTD', '28212', 'LIR'],
               ['"Myphone" LTD', '28222', 'ADD'],
               ['"Servicebox" LTD', '28215', 'ADD']],
  'Gibraltar': [['GibFibre Ltd (trading as “Gibfibrespeed”)', '26603', 'ADD']],
  'Greenland': [['GTV', '29003', 'ADD']],
  'Guadeloupe': [['Free Caraïbe', '34004', 'SUP']],
  'Guyana': [['E-Networks Inc.', '73800', 'ADD'], ['E-Networks Inc.', '738040', 'ADD']],
  'Hong Kong, China': [ ['Webbing Hong Kong Limited', '45435', 'ADD'],
                        ['CMMobile Global Communications Ltd', '45409', 'SUP'],
                        ['Lycamobile Hong Kong Ltd', '45423', 'SUP'],
                        ['Easco Telecommunications Limited', '45436', 'ADD'],
                        ['China Mobile Hong Kong Company Limited', '45412', 'LIR'],
                        ['China Mobile Hong Kong Company Limited', '45413', 'LIR'],
                        ['21 ViaNet Group Limited', '45421', 'LIR'],
                        ['China Mobile Hong Kong Company Limited', '45430', 'LIR']],
  'Hungary': [ ['Invitech ICT Services Ltd.', '21604', 'LIR'],
               ['Invitech ICT Services Ltd.', '21604', 'SUP'],
               ['Vodafone Hungary Ltd', '21671', 'LIR'],
               ['Yettel Hungary Ltd.', '21601', 'LIR'],
               ['Yettel Hungary Ltd.', '21620', 'ADD']],
  'International Mobile, shared code': [ ['Plintron Global Technology Solutions Private Limited', '90165', 'ADD'],
                                         ['Limitless Mobile, LLC', '90166', 'ADD'],
                                         ['1NCE GmbH', '90167', 'ADD'],
                                         ['Maersk Line A/S', '90168', 'ADD'],
                                         [ 'UN Office for the Coordination of Humanitarian Affairs (OCHA) - Reserved',
                                           '90188',
                                           'LIR'],
                                         ['Legos', '90169', 'ADD'],
                                         ['Clementvale Baltic OÜ', '90170', 'ADD'],
                                         ['One Network B.V.', '90141', 'LIR'],
                                         ['Tampnet AS', '90171', 'ADD'],
                                         ['Tele2 IoT', '90172', 'ADD'],
                                         ['Cubic Telecom Limited', '90173', 'ADD'],
                                         ['Vodafone Malta (Monaco Telecom)', '90119', 'LIR'],
                                         ['Etisalat', '90174', 'ADD'],
                                         [ 'Mobile Telecommunications Company K.S.C.P. (Formerly Zain Kuwait)',
                                           '90149',
                                           'LIR'],
                                         ['Podsystem Ltd.', '90175', 'ADD'],
                                         ['A1 Telekom Austria AG', '90176', 'ADD'],
                                         ['Bouygues Telecom', '90177', 'ADD'],
                                         ['Tele2 Sverige Aktiebolag (Formerly Tele2 IoT)', '90172', 'LIR'],
                                         ['Inmarsat Ltd. (replacing Deutsche Telekom AG)', '90153', 'LIR'],
                                         ['Telecom Italia Sparkle S.p.A.', '90178', 'ADD'],
                                         ['Nokia Corporation', '90179', 'ADD'],
                                         ['Flo Live Limited', '90180', 'ADD'],
                                         ['Airnity SAS', '90181', 'ADD'],
                                         ['Eseye Limited', '90182', 'ADD'],
                                         ['iBasis Netherlands BV', '90183', 'ADD'],
                                         [ 'UN Office for the Coordination of Humanitarian Affairs (OCHA)',
                                           '90188',
                                           'SUP'],
                                         ['TELEFONICA MOVILES ESPAÑA, S.A. UNIPERSONAL (TME)', '90184', 'ADD'],
                                         ['Telefónica Germany GmbH & Co. OHG', '90185', 'ADD'],
                                         ['GloTell B.V.', '90163', 'SUP'],
                                         ['Telenor Connexion AB', '90129', 'SUP'],
                                         ['Smart Communications, Inc', '90133', 'SUP'],
                                         ['Ooredoo', '90147', 'SUP'],
                                         ['SAP', '90157', 'SUP'],
                                         ['Clementvale Baltic OÜ', '90170', 'SUP'],
                                         ['BJT PARTNERS SAS', '90186', 'ADD'],
                                         ['Cisco Systems, Inc.', '90187', 'ADD'],
                                         ['DIDWW Ireland Limited', '90189', 'ADD'],
                                         ['Truphone Limited', '90190', 'ADD'],
                                         ['World Mobile Group Limited', '90191', 'ADD'],
                                         ['VisionNG', '90151', 'SUP'],
                                         ['Phonegroup SA', '90192', 'ADD'],
                                         ['SkyFive AG', '90193', 'ADD'],
                                         ['BebbiCell AG (Formerly Global Networks Switzerland AG', '90113', 'SUP'],
                                         ['Plintron Global Technology Solutions Private Limited', '90165', 'SUP'],
                                         ['Flo Live Limited', '90180', 'SUP'],
                                         ['Intelsat US LLC', '90194', 'ADD'],
                                         ['HMD Global Oy', '90195', 'ADD'],
                                         ['IMC Island Ehf (formerly DCN Hub ehf)', '90142', 'SUP'],
                                         ['KORE Wireless', '90196', 'ADD'],
                                         ['MegaFon', '90132', 'SUP'],
                                         ['Beezz Communication Solutions Ltd.', '90155', 'SUP'],
                                         ['Satelio IoT Services S.L.', '90197', 'ADD'],
                                         ['Flo Live Limited', '90180', 'ADD'],
                                         ['Skylo Technologies, Inc.', '90198', 'ADD'],
                                         ['Webbing', '90101', 'ADD'],
                                         ['Athalos Global Services BV', '90199', 'ADD'],
                                         ['GlobalmatiX AG', '90102', 'ADD']],
  'Iran (Islamic Republic of)': [ ['Telecommunication Company of Iran (TCI) - Isfahan Celcom GSM', '43219', 'SUP'],
                                  ['KISH CELL PARS', '43201', 'ADD'],
                                  ['NEGIN ERTEBATAT AVA', '43202', 'ADD'],
                                  ['PARSIAN HAMRAH LOTUS', '43203', 'ADD'],
                                  ['TOSE E FANAVARI ERTEBATAT NOVIN HAMRAH', '43204', 'ADD'],
                                  ['HAMRAH HOSHMAND AYANDEH', '43205', 'ADD'],
                                  ['ERTEBATAT ARYANTEL', '43206', 'ADD'],
                                  ['HOOSHMAND AMIN MOBILE', '43207', 'ADD'],
                                  ['HIWEB', '43209', 'ADD'],
                                  ['HIWEB', '43212', 'ADD'],
                                  ['HIWEB', '43213', 'ADD'],
                                  ['RIGHTEL', '43220', 'ADD'],
                                  ['TCI (Telecommunication Company of Iran)', '43232', 'ADD'],
                                  ['IRANCELL', '43235', 'ADD'],
                                  ['ERTEBATAT MOBIN NET', '43244', 'ADD'],
                                  ['FARABORD DADEHAYE IRANIAN', '43245', 'ADD'],
                                  ['HIWEB', '43246', 'ADD'],
                                  ['GOSTARESH ERTEBATAT MABNA', '43249', 'ADD'],
                                  ['PISHGAMAN TOSE-E ERTEBATAT', '43251', 'ADD'],
                                  ['ASIATECH', '43252', 'ADD'],
                                  ['TCI (Telecommunication Company of Iran)', '43270', 'ADD'],
                                  ['ERTEBATAT KOOHE NOOR', '43271', 'ADD'],
                                  ['ERTEBATAT FARZANEGAN PARS', '43293', 'ADD'],
                                  ['TOSE-E ERTEBATAT HAMRAH SHATEL', '43208', 'LIR'],
                                  ['MCI (Mobile Communications of Iran)', '43211', 'LIR'],
                                  ['Kish Free Zone Organization', '43214', 'LIR'],
                                  ['SHATEL', '43250', 'LIR']],
  'Ireland': [ ['Net Feasa Limited', '27221', 'ADD'],
               ['Office of the Government Chief Information Officer', '27268', 'ADD']],
  'Israel': [['Maskyoo Telephonia Ltd.', '42522', 'ADD'], ['BITIT Ltd.', '42527', 'ADD']],
  'Jamaica': [['Symbiote Investment Limited', '338040', 'SUP'], ['Rock Mobile Limited', '338080', 'ADD']],
  'Japan': [ ['Panasonic Systems Solutions Japan Co., Ltd', '44008', 'ADD'],
             ['Marubeni Wireless Communications Inc.', '44009', 'ADD'],
             ['Rakuten Mobile Network, Inc.', '44011', 'ADD'],
             ['CABLE MEDIA WAIWAI CORPORATION', '44012', 'ADD'],
             ['UQ Communications Inc.', '44110', 'SUP'],
             ['NTT Communications Corporation', '44013', 'ADD'],
             ['GRAPE ONE LTD.', '44014', 'ADD'],
             ['BB Backbone Corp.', '44015', 'ADD'],
             ['Nokia Innovations Japan G.K.', '44016', 'ADD'],
             ['OSAKA GAS BUSINESS CREATE CORPORATION', '44017', 'ADD'],
             ['Kintetsu Cable Network, Ltd', '44018', 'ADD'],
             ['NEC Networks & System Integration Corporation', '44019', 'ADD'],
             ['JTOWER Inc.', '44022', 'ADD'],
             ['FUJITSU LIMITED', '44023', 'ADD'],
             ['SORACOM, Inc.', '441200', 'ADD'],
             ['Aurens Co.,Ltd.', '441201', 'ADD'],
             ['Sony Wireless Communications Inc.', '441202', 'ADD'],
             ['GujoCity', '441203', 'ADD'],
             ['Wicom Inc.', '441204', 'ADD'],
             ['KATCH NETWORK INC.', '441205', 'ADD'],
             ['MITSUBISHI ELECTRIC CORPORATION', '441206', 'ADD'],
             ['closip, Inc.', '44007', 'LIR'],
             ['The Tokyo Organising Committee of the Olympic and Paralympic Games', '44191', 'SUP'],
             ['Mitsui Knowledge Industry Co., Ltd.', '441207', 'ADD'],
             ['CHUDENKO CORPORATION', '441208', 'ADD'],
             ['Cable Television TOYAMA Inc.', '441209', 'ADD'],
             ['NIPPON TELEGRAPH AND TELEPHONE EAST CORPORATION', '441210', 'ADD'],
             ['KDDI CORPORATION', '44001', 'LIR'],
             ['KDDI Corporation', '44070', 'SUP'],
             ['KDDI Corporation', '44071', 'SUP'],
             ['KDDI Corporation', '44072', 'SUP'],
             ['KDDI Corporation', '44073', 'SUP'],
             ['KDDI Corporation', '44074', 'SUP'],
             ['KDDI Corporation', '44075', 'SUP'],
             ['KDDI Corporation', '44076', 'SUP'],
             ['STARCAT CABLE NETWORK Co., LTD.', '441211', 'ADD'],
             ['I-TEC Solutions Co., Ltd.', '441212', 'ADD'],
             ['Panasonic Connect Co., Ltd', '44008', 'LIR'],
             ['Marubeni Network Solutions Inc.', '44009', 'LIR'],
             ['Okinawa Cellular Telephone Company', '44078', 'SUP']],
  'Kenya': [ ['WiAfrica Kenya Limited', '63911', 'SUP'],
             ['Safaricom PLC', '63901', 'LIR'],
             ['Safaricom PLC', '63902', 'LIR'],
             ['Sema Mobile Services Limited', '63908', 'SUP'],
             ['Jambo Telcoms Limited', '63911', 'ADD'],
             ['Infura Limited', '63912', 'ADD']],
  'Kosovo*': [['Dukagjini Telecommunications LLC', '22107', 'ADD']],
  'Lao P.D.R.': [ ['Star Telecom Co., Ltd', '45703', 'ADD'],
                  ['Best Telecom Co., Ltd', '45707', 'ADD'],
                  ['Lao Telecommunication Public Company', '45701', 'LIR'],
                  ['ETL Company Limited', '45702', 'LIR'],
                  ['TPLUS Digital Sole Company Limited', '45708', 'LIR']],
  'Liechtenstein': [ ['First Mobile AG', '29507', 'SUP'],
                     ['DIMOCO Messaging AG', '29511', 'ADD'],
                     ['SORACOM CORPORATION, LTD.', '29510', 'LIR']],
  'Luxembourg': [['Proximus Luxembourg S.A.', '27077', 'LIR'], ['Luxembourg Online S.A.', '27005', 'ADD']],
  'Malta': [['Epic Communications Ltd', '27801', 'LIR'], ['Melita Ltd', '27877', 'LIR'], ['YOM', '27811', 'SUP']],
  'Martinique': [['Martinique Téléphone Mobile', '34012', 'SUP']],
  'Mexico': [ ['TELECOMUNICACIONES DE MÉXICO', '334100', 'ADD'],
              ['MAXCOM TELECOMUNICACIONES, S.A.B. DE C.V.', '334110', 'ADD'],
              ['QUICKLY PHONE, S.A. DE C.V.', '334120', 'ADD'],
              ['AXTEL, S.A.B. DE C.V.', '334130', 'ADD'],
              ['ALTÁN REDES, S.A.P.I. DE C.V.', '334140', 'ADD'],
              ['ULTRAVISIÓN, S.A. DE C.V.', '334150', 'ADD'],
              ['CABLEVISIÓN RED, S.A. DE C.V.', '334160', 'ADD'],
              ['OXIO MOBILE, S.A. DE C.V.', '334170', 'ADD'],
              ['AT&T COMUNICACIONES DIGITALES, S. DE R.L. DE C.V.', '334010', 'LIR'],
              ['PEGASO PCS, S.A. DE C.V.', '334030', 'LIR'],
              [ 'AT&T NORTE, S. DE R.L. DE C.V. Y AT&T DESARROLLO EN COMUNICACIONES DE MÉXICO, S. DE R.L. DE C.V.',
                '334040',
                'LIR'],
              ['GRUPO AT&T CELULLAR, S. DE R.L. DE C.V.', '334050', 'LIR'],
              ['AT&T COMERCIALIZACIÓN MÓVIL, S. DE R.L. DE C.V.', '334070', 'LIR'],
              ['AT&T COMERCIALIZACIÓN MÓVIL, S. DE R.L. DE C.V.', '334080', 'LIR'],
              ['AT&T COMUNICACIONES DIGITALES, S. DE R.L. DE C.V.', '334090', 'LIR'],
              ['FREEDOMPOP MÉXICO, S.A. DE C.V.', '334180', 'ADD'],
              ['VIASAT TECNOLOGÍA, S.A. DE C.V.', '334190', 'ADD']],
  'Namibia': [['Capricorn Connect', '64907', 'ADD']],
  'Netherlands': [ ['Mundio Mobile (Netherlands) Ltd', '20406', 'SUP'],
                   ['Intercity Mobile Communications B.V.', '20417', 'SUP'],
                   ['Tismi B.V.', '20429', 'ADD'],
                   ['Nextgen Mobile Ltd', '20460', 'SUP'],
                   ['Alcadis B.V.', '20461', 'ADD'],
                   ['AGMS Nederland B.V.', '20465', 'SUP'],
                   ['Roamware (Netherlands) B.V.', '20468', 'SUP'],
                   ['Intovoice B.V.', '20400', 'ADD'],
                   ['Greenet Netwerk B.V.', '20411', 'ADD'],
                   ['Venus & Mercury Telecom', '20414', 'ADD'],
                   ['L-Mobi Mobile B.V.', '20427', 'ADD'],
                   ['ASpider Solutions Nederland B.V.', '20430', 'ADD'],
                   ['Cubic Telecom Limited', '20432', 'ADD'],
                   ['Truphone B.V.', '20433', 'ADD'],
                   ['Messagebird BV', '20463', 'ADD'],
                   ['Enexis Netbeheer B.V.', '20491', 'ADD'],
                   ['T-Mobile Netherlands B.V.', '20402', 'LIR'],
                   ['Tata Communications MOVE B.V.', '20407', 'LIR'],
                   ['KPN B.V.', '20408', 'LIR'],
                   ['Ziggo Services B.V.', '20418', 'LIR'],
                   ['KORE Wireless Nederland B.V.', '20423', 'LIR'],
                   ['CapX Nederland', '20425', 'LIR'],
                   ['KPN B.V.', '20469', 'LIR'],
                   ['RadioAccess Network Services B.V.', '20401', 'SUP'],
                   ['Elephant Talk Communications Premium Rate Services', '20405', 'SUP'],
                   ['RadioAccess B.V.', '20467', 'SUP'],
                   ['Lebara Ltd', '20417', 'ADD'],
                   ['RGTN Wholesale Netherlands B.V.', '20462', 'ADD'],
                   ['PM Factory B.V.', '20424', 'LIR'],
                   ['Private Mobility Nederland B.V.', '20406', 'ADD']],
  'New Zealand': [['Dense Air New Zealand Ltd', '53007', 'ADD']],
  'North Macedonia': [['MTEL DOOEL Skopje', '29412', 'ADD']],
  'Oman': [['Vodafone Oman', '42206', 'ADD']],
  'Palau': [['Palau Mobile Communications Inc. (PMCI)', '55299', 'ADD']],
  'Panama': [ ['Grupo de Comunicaciones Digitales, S.A. (TIGO)', '71402', 'LIR'],
              ['Grupo de Comunicaciones Digitales, S.A. (TIGO)', '714020', 'LIR'],
              ['Cable & Wireless Panamá, S.A.', '71405', 'ADD']],
  'Papua New Guinea': [['Digitec Communication Limited', '53704', 'ADD']],
  'Rwanda': [['AIRTEL RWANDA Ltd', '63513', 'ADD'], ['AIRTEL RWANDA Ltd', '63514', 'SUP']],
  'Saint Pierre and Miquelon': [['SAS SPM Telecom', '30803', 'ADD']],
  'Seychelles': [['Intelvision Ltd', '63305', 'ADD']],
  'Slovenia': [['BeeIN d.o.o.', '29311', 'ADD'], ['Novatel d.o.o.', '29321', 'ADD']],
  'South Africa': [ ['Vodacom Pty Ltd', '65565', 'ADD'],
                    ['Sasol (Pty) Ltd', '65504', 'SUP'],
                    ['SAPS Gauteng', '65511', 'SUP'],
                    ['Sishen Iron Ore Company (Ltd) Pty', '65517', 'SUP'],
                    ['Cape Town Metropolitan Council', '65521', 'SUP'],
                    ['South African Police Service', '65541', 'SUP'],
                    ['Airport Company South Africa (ACSA)', '65575', 'SUP'],
                    ['Comsol Networks (Pty) Ltd', '65576', 'ADD'],
                    ['K2015315513 (Pty) Ltd t\\a One Telecom (Pty) Ltd', '65577', 'ADD'],
                    ['Telkom SA SOC Ltd', '65503', 'ADD']],
  'Spain': [ ['OPEN CABLE TELECOMUNICACIONES, S.L.', '21436', 'SUP'],
             ['SYMA MOBILE ESPAÑA, S.L.', '21413', 'ADD'],
             ['VODAFONE ESPAÑA, S.A.U.', '21424', 'LIR'],
             ['Xfera Móviles, S.A.U.', '21423', 'ADD'],
             ['Telefónica Móviles España, SAU', '21438', 'ADD'],
             ['XFERA MÓVILES, S.A.U.', '21433', 'ADD'],
             ['R CABLE Y TELECOMUNICACIONES GALICIA, S.A.', '21416', 'LIR'],
             ['ALAI OPERADOR DE TELECOMUNICACIONES, S.L.', '21436', 'ADD'],
             ['XFERA MÓVILES, S.A.U.', '21429', 'ADD'],
             ['Vodafone España, SAU', '21437', 'SUP'],
             ['VODAFONE ESPAÑA, S.A.U.', '21437', 'ADD'],
             ['Telefónica Móviles España, SAU', '21432', 'SUP'],
             ['AVATEL MÓVIL, S.L.U.', '21414', 'ADD'],
             ['SAC CONVERGENT AGGREGATION SERVICES, S.L.U.', '21412', 'SUP'],
             ['Compatel Limited', '21430', 'SUP'],
             ['VENUS MOVIL, S.L. UNIPERSONAL', '21412', 'ADD'],
             ['SYMA MOBILE ESPAÑA, S.L.', '21413', 'SUP'],
             ['ORANGE ESPAGNE, S.A. UNIPERSONAL', '21421', 'SUP'],
             ['XFERA MÓVILES, S.A. UNIPERSONAL', '21425', 'ADD'],
             ['XFERA MÓVILES, S.A.U.', '21433', 'SUP'],
             ['IBERDROLA ESPAÑA, S.A.UNIPERSONAL', '214700', 'ADD'],
             ['ENDESA DISTRIBUCIÓN ELÉCTRICA, S.L.', '214701', 'ADD']],
  'Sri Lanka': [ ['Hutchison Telecommunications Lanka (Pvt) Ltd. (Valid until 12 September 2021)', '41309', 'ADD'],
                 ['Hutchison Telecommunications Lanka (Pvt) Ltd. (Valid until 12 September 2021)', '41303', 'LIR'],
                 ['Hutchison Telecommunications Lanka (Pvt) Ltd.', '41303', 'SUP'],
                 ['Hutchison Telecommunications Lanka (Pvt) Ltd.', '41309', 'SUP']],
  'Sudan': [['Sudanese Telecommunication Co. LTD (SUDATEL)', '63407', 'ADD']],
  'Sweden': [ [ 'Telefonaktiebolaget LM Ericsson (MNC assigned for test purpose. Temporary license until 2019-12-31)',
                '24060',
                'LIR'],
              ['NextGen Mobile Ltd.', '24030', 'SUP'],
              ['Fink Telecom Services', '24063', 'ADD'],
              ['Tismi BV', '24048', 'ADD'],
              ['Shyam Telecom UK Ltd', '24041', 'SUP'],
              ['Primlight AB', '24039', 'LIR'],
              ['Twilio Ireland Ltd.', '24026', 'LIR'],
              ['Telia Sverige AB', '24049', 'ADD'],
              ['Tele2 Sverige AB', '24014', 'LIR'],
              ['Telenor Sverige AB', '24041', 'ADD'],
              ['LINK Mobile A/S', '24028', 'SUP'],
              ['Västra Götalandsregionen (temporary assigned until 2026-12-31)', '24060', 'ADD'],
              ['MessageBird B.V.', '24061', 'SUP'],
              ['Teracom AB', '24003', 'LIR'],
              ['Bredband2 Företag AB', '24013', 'LIR'],
              ['Sierra Wireless Messaging AB', '24020', 'LIR'],
              ['MI Carrier Services AB', '24029', 'LIR'],
              ['Sinch Sweden AB', '24037', 'LIR'],
              ['Netmore Group AB', '24040', 'LIR'],
              ['RebTel Networks AB', '24031', 'SUP'],
              ['Bredband2 Allmänna IT AB', '24013', 'LIR'],
              ['Teracom AB', '24030', 'ADD'],
              ['EuTel AB', '24022', 'SUP'],
              ['ComHem AB', '24011', 'SUP']],
  'Switzerland': [ ['Telecom26 AG', '22862', 'ADD'],
                   ['Fink Telecom Services', '22863', 'ADD'],
                   ['NTH AG', '22864', 'ADD'],
                   ['Compatel Ltd', '22861', 'SUP'],
                   ['Vectone Mobile Limited, London', '22859', 'ADD'],
                   ['Inovia Services SA', '22866', 'ADD'],
                   ['Datatrade Managed AG', '22867', 'ADD'],
                   ['Intellico AG', '22868', 'ADD'],
                   ['Sunrise Communications AG', '22808', 'LIR'],
                   ['MTEL Schweiz GmbH', '22869', 'ADD'],
                   ['Tismi BV', '22870', 'ADD'],
                   ['Spusu AG', '22871', 'ADD']],
  'Syrian Arab Republic': [['MTN Syria', '41702', 'ADD'], ['WAFA Telecom', '41703', 'ADD']],
  'Tanzania': [ ['Shared Network Tanzania Limited', '64001', 'SUP'],
                ['Benson Informatics Limited (Smart)', '64008', 'SUP'],
                ['MO Mobile Holding Limited', '64014', 'ADD'],
                ['Wiafrica Tanzania Limited (Cootel)', '64013', 'SUP'],
                ['MO Mobile Holding Limited', '64014', 'SUP'],
                ['WIA Company Limited', '64006', 'ADD']],
  'Trial of a proposed new international telecommunication service, shared code': [ [ "World's Global Telecom "
                                                                                      '(temporary assignment for trial '
                                                                                      'until 14.I.2021)',
                                                                                      '99101',
                                                                                      'LIR'],
                                                                                    [ 'Orange (temporary assignment '
                                                                                      'for trial until 6.VIII.2021)',
                                                                                      '99102',
                                                                                      'ADD'],
                                                                                    [ "World's Global Telecom (end of "
                                                                                      'temporary assignment for trial '
                                                                                      'on 15.I.2021)',
                                                                                      '99101',
                                                                                      'SUP'],
                                                                                    [ 'Halys SAS (temporary assignment '
                                                                                      'for trial until 5.IV.2022)',
                                                                                      '99103',
                                                                                      'ADD'],
                                                                                    [ 'Orange (temporary assignment '
                                                                                      'for trial until 6.VIII.2022)',
                                                                                      '99102',
                                                                                      'LIR'],
                                                                                    [ 'Orange (end of temporary '
                                                                                      'assignment for trial on '
                                                                                      '7.VIII.2022)',
                                                                                      '99102',
                                                                                      'SUP'],
                                                                                    [ 'Halys SAS (end of temporary '
                                                                                      'assignment for trial on '
                                                                                      '6.IV.2022)',
                                                                                      '99103',
                                                                                      'SUP']],
  'Turks and Caicos Islands': [ ['IslandCom Communication Ltd.', '376352', 'SUP'],
                                ['IslandCom Communication Ltd', '376360', 'SUP'],
                                ['Digicel TCI Ltd', '376351', 'ADD'],
                                ['Digicel TCI Ltd', '376351', 'SUP'],
                                ['Digicel', '376360', 'ADD']],
  'Uganda': [ ['Afrimax Uganda Limited', '64106', 'SUP'],
              ['Lycamobile Network services Uganda Limited', '64126', 'SUP'],
              ['Suretelecom Uganda Limited', '64118', 'SUP'],
              ['Hamilton Telecom Limited', '64120', 'SUP']],
  'Ukraine': [ ['"Ukrtelecom" JSC', '25508', 'ADD'],
               ['"VF UKRAINE" PrJSC', '25501', 'LIR'],
               ['"Kyivstar" PrJSC', '25502', 'LIR'],
               ['"Kyivstar" PrJSC', '25503', 'LIR'],
               ['"Intertelecom" LLC', '25504', 'LIR'],
               ['"lifecell" LLC', '25506', 'LIR'],
               ['"TriMob" LLC', '25507', 'LIR'],
               ['"Telesystems of Ukraine" PrJSC', '25521', 'LIR'],
               ['"Farlep-Invest", PrJSC', '25509', 'ADD'],
               ['"Atlantis Telecom", LLC', '25510', 'ADD']],
  'United Kingdom': [ ['COLT Mobile Telecommunications Limited', '23405', 'SUP'],
                      ['Internet Computer Bureau Limited', '23406', 'SUP'],
                      ['Vodafone Ltd (C&W)', '23407', 'SUP'],
                      ['FleXtel Limited', '23417', 'SUP'],
                      ['Limitless Mobile Ltd', '23459', 'SUP'],
                      ['AMSUK Limited', '23470', 'SUP'],
                      ['Vodafone Ltd (C&W)', '23592', 'SUP'],
                      ['Mass Response Service GmbH', '23440', 'ADD'],
                      ['Hanhaa Limited', '23472', 'ADD'],
                      ['BlueWave Communications', '23473', 'ADD'],
                      ['Pareteum Europe B.V.', '23474', 'ADD'],
                      ['Vodafone Limited', '23477', 'ADD'],
                      ['Telet Research (N.I.) Limited', '23488', 'ADD'],
                      ['University Of Strathclyde', '23504', 'ADD'],
                      ['University Of Strathclyde', '23506', 'ADD'],
                      ['University Of Strathclyde', '23507', 'ADD'],
                      ['Spitfire Network Services Limited', '23508', 'ADD'],
                      ['Telet Research (N.I.) Limited', '23588', 'ADD'],
                      ['Vectone Mobile Limited', '23401', 'LIR'],
                      ['LINK MOBILITY UK LTD', '23414', 'LIR'],
                      ['Vodafone Limited', '23415', 'LIR'],
                      ['TeleWare Group PLC', '23419', 'LIR'],
                      ['Tata Communications Move UK Ltd', '23427', 'LIR'],
                      ['(AQ) LIMITED', '23429', 'LIR'],
                      ['EE Limited (Orange)', '23433', 'LIR'],
                      ['EE Limited (Orange)', '23434', 'LIR'],
                      ['JT (Jersey) Limited', '23450', 'LIR'],
                      ['Tango Networks UK Ltd', '23453', 'LIR'],
                      ['The National Cyber Security Centre', '23456', 'LIR'],
                      ['MANX TELECOM TRADING LIMITED', '23458', 'LIR'],
                      ['Vectone Mobile Limited', '23500', 'LIR'],
                      ['Vodafone Limited', '23591', 'LIR']],
  'United States': [ ['MTA Communications dba MTA Wireless', '310040', 'SUP'],
                     ['Consolidated Telcom', '310060', 'SUP'],
                     ['Blanca Telephone Company', '310300', 'SUP'],
                     ['Elkhart Telephone Co. Inc. dba Epic Touch Co.', '310610', 'SUP'],
                     ['D.D. Inc', '310780', 'SUP'],
                     ['ARINC', '311200', 'SUP'],
                     ['Nexus Communications Inc', '311300', 'SUP'],
                     ['Mosaic Telecom Inc', '311500', 'SUP'],
                     ['Lycamobile USA Inc', '311960', 'SUP'],
                     ['Fuego Wireless LLC', '312050', 'SUP'],
                     ['Adams Networks Inc', '312070', 'SUP'],
                     ['Cleveland Unlimited Inc', '312140', 'SUP'],
                     ['MTA Communications dba MTA Wireless', '312340', 'SUP'],
                     ['Consolidated Telcom', '312440', 'SUP'],
                     ['KDDI America, Inc dba Locus Telecommunications', '312740', 'SUP'],
                     ['Wireless Partners LLC', '310330', 'ADD'],
                     ['Limitless Mobile, LLC', '310340', 'ADD'],
                     ['Verizon Wireless', '310591', 'ADD'],
                     ['Verizon Wireless', '310592', 'ADD'],
                     ['Verizon Wireless', '310593', 'ADD'],
                     ['Verizon Wireless', '310594', 'ADD'],
                     ['Verizon Wireless', '310595', 'ADD'],
                     ['Verizon Wireless', '310596', 'ADD'],
                     ['Verizon Wireless', '310597', 'ADD'],
                     ['Verizon Wireless', '310598', 'ADD'],
                     ['Verizon Wireless', '310599', 'ADD'],
                     ['Pacific Lightwave Inc.', '310810', 'ADD'],
                     ['Verizon Wireless', '310891', 'ADD'],
                     ['Verizon Wireless', '310892', 'ADD'],
                     ['Verizon Wireless', '310893', 'ADD'],
                     ['Verizon Wireless', '310894', 'ADD'],
                     ['Verizon Wireless', '310895', 'ADD'],
                     ['Verizon Wireless', '310896', 'ADD'],
                     ['Verizon Wireless', '310897', 'ADD'],
                     ['Verizon Wireless', '310898', 'ADD'],
                     ['Verizon Wireless', '310899', 'ADD'],
                     ['Telnyx LLC', '311210', 'ADD'],
                     ['ELECTRIC IMP INCORPORATED', '311460', 'ADD'],
                     ['Limitless Mobile, LLC', '311600', 'ADD'],
                     ['Reclaimed 06/21/2016', '311760', 'ADD'],
                     ['The American Samoa Telecommunications Authority', '311780', 'ADD'],
                     ['Sprint', '311882', 'ADD'],
                     ['Country Wireless', '313061', 'ADD'],
                     ['AT&T FirstNet', '313110', 'ADD'],
                     ['AT&T FirstNet', '313120', 'ADD'],
                     ['AT&T FirstNet', '313130', 'ADD'],
                     ['AT&T FirstNet', '313140', 'ADD'],
                     ['RESERVED FOR PUBLIC SAFETY', '313150', 'ADD'],
                     ['RESERVED FOR PUBLIC SAFETY', '313160', 'ADD'],
                     ['RESERVED FOR PUBLIC SAFETY', '313170', 'ADD'],
                     ['RESERVED FOR PUBLIC SAFETY', '313180', 'ADD'],
                     ['RESERVED FOR PUBLIC SAFETY', '313190', 'ADD'],
                     ['Custer Telephone Cooperative,Inc.', '313220', 'ADD'],
                     ['Velocity Communications Inc', '313230', 'ADD'],
                     ['Fundamental Holdings, Corp', '313240', 'ADD'],
                     ['Imperial County Office of Education', '313250', 'ADD'],
                     ['Expeto Wireless Inc.', '313260', 'ADD'],
                     ['King Street Wireless, LP', '313280', 'ADD'],
                     ['Gulf Coast Broadband LLC', '313290', 'ADD'],
                     ['Cambio WiFi of Delmarva, LLC.', '313300', 'ADD'],
                     ['CAL.NET, INC', '313310', 'ADD'],
                     ['Paladin Wireless', '313320', 'ADD'],
                     ['CenturyTel Broadband Services LLC', '313330', 'ADD'],
                     ['Dish Network', '313340', 'ADD'],
                     ['Dish Network', '313350', 'ADD'],
                     ['Dish Network', '313360', 'ADD'],
                     ['Red Truck Wireless, LLC', '313370', 'ADD'],
                     ['OptimERA Inc.', '313380', 'ADD'],
                     ['Altice USA Wireless, Inc.', '313390', 'ADD'],
                     ['Texoma Communications, LLC', '313400', 'ADD'],
                     ['pdvWireless', '313410', 'ADD'],
                     ['Hudson Valley Wireless', '313420', 'ADD'],
                     ['Arvig Enterprises INC', '313440', 'ADD'],
                     ['Spectrum Wireless Holdings, LLC', '313450', 'ADD'],
                     ['Mobi, Inc.', '313460', 'ADD'],
                     ['San Diego Gas & Electric Company', '313470', 'ADD'],
                     ['Ready Wireless, LLC', '313480', 'ADD'],
                     ['Puloli, Inc', '313490', 'ADD'],
                     ['Shelcomm, Inc', '313500', 'ADD'],
                     ['Puerto Rico Telecom Company', '313510', 'ADD'],
                     ['Florida Broadband, Inc', '313520', 'ADD'],
                     ['Nokia Innovations US LLC', '313540', 'ADD'],
                     ['Mile High Networks LLC', '313550', 'ADD'],
                     ['Transit Wireless, LLC', '313560', 'ADD'],
                     ['Celular Network Partnership', '313570', 'ADD'],
                     ['Telecall Telecommuncations Corp.', '313580', 'ADD'],
                     ['Southern Communications Services, Inc. D/B/A Southern Linc', '313590', 'ADD'],
                     ['ST Engineering iDirect', '313600', 'ADD'],
                     ['Crystal Automation Systems, Inc.', '313610', 'ADD'],
                     ['Screened Images', '313620', 'ADD'],
                     ['LICT Corporation', '313630', 'ADD'],
                     ['Geoverse', '313640', 'ADD'],
                     ['Chevron USA INC', '313650', 'ADD'],
                     ['Hudson Valley Wireless', '313660', 'ADD'],
                     ['Hudson Valley Wireless', '313670', 'ADD'],
                     ['Hudson Valley Wireless', '313680', 'ADD'],
                     ['Shenandoah Cable Television, LLC', '313690', 'ADD'],
                     ['Ameren Services Company', '313700', 'ADD'],
                     ['Extent Systems', '313710', 'ADD'],
                     ['1st Point Communications, LLC', '313720', 'ADD'],
                     ['TruAccess Networks', '313730', 'ADD'],
                     ['RTO Wireless, LLC', '313740', 'ADD'],
                     ['313-CellTex Networks, LLC', '313750', 'ADD'],
                     ['Hologram, Inc.', '313760', 'ADD'],
                     ['Tango Networks', '313770', 'ADD'],
                     ['Boingo Wireless Inc', '314010', 'ADD'],
                     ['Spectrum Wireless Holdings, LLC', '314020', 'ADD'],
                     ['Baicells Technologies North America Inc.', '314030', 'ADD'],
                     ['RESERVED FOR PUBLIC SAFETY', '314100', 'ADD'],
                     ['RESERVED FOR PUBLIC SAFETY', '314110', 'ADD'],
                     ['RESERVED FOR PUBLIC SAFETY', '314120', 'ADD'],
                     ['RESERVED FOR PUBLIC SAFETY', '314130', 'ADD'],
                     ['RESERVED FOR PUBLIC SAFETY', '314140', 'ADD'],
                     ['RESERVED FOR PUBLIC SAFETY', '314150', 'ADD'],
                     ['RESERVED FOR PUBLIC SAFETY', '314160', 'ADD'],
                     ['RESERVED FOR PUBLIC SAFETY', '314170', 'ADD'],
                     ['RESERVED FOR PUBLIC SAFETY', '314180', 'ADD'],
                     ['RESERVED FOR PUBLIC SAFETY', '314190', 'ADD'],
                     ['Docomo Pacific Inc', '310470', 'LIR'],
                     ['Broadpoint, LLC (former PetroCom, LLC) c/o MTPCS, LLC dba CellularOne', '310570', 'LIR'],
                     ['Nsighttel Wireless, LLC', '310620', 'LIR'],
                     ['Limitless Mobile, LLC', '310690', 'LIR'],
                     ['Tyntec Inc.', '310940', 'LIR'],
                     ['Evolve Cellular Inc.', '310990', 'LIR'],
                     ['Chariton Valley Communications Corporation', '311010', 'LIR'],
                     ['Tampnet (formerly Broadpoint, LLC (former PetroCom, LLC) c/o MTPCS, LL', '311170', 'LIR'],
                     ['Ligado Networks', '311510', 'LIR'],
                     ['Commnet Wireless, LLC', '311550', 'LIR'],
                     ['Midwest Network Solutions Hub, LLC. (MNS)', '311700', 'LIR'],
                     ['Missouri RSA No 5 Partnership', '311920', 'LIR'],
                     ['Chariton Valley Communications Corporation', '312010', 'LIR'],
                     ['Limitless Mobile, LLC', '312180', 'LIR'],
                     ['Chariton Valley Communications Corporation', '312220', 'LIR'],
                     ['Brightlink', '312650', 'LIR'],
                     ['TGS, LLC', '312690', 'LIR'],
                     ['PREMIER HOLDINGS, LLC', '312990', 'LIR'],
                     ['AT&T FirstNet', '313100', 'LIR'],
                     ['AT&T Mobility', '313210', 'LIR'],
                     ['Wave Runner LLC', '310400', 'SUP'],
                     ['Oklahoma Western Telephone Company', '310540', 'SUP'],
                     ['U.S. Cellular', '310730', 'SUP'],
                     ['Mid-Rivers Telephone Cooperative', '310900', 'SUP'],
                     ['Chariton Valley Communications Corporation', '311010', 'SUP'],
                     ['Missouri RSA No. 5 Partnership', '311020', 'SUP'],
                     ['Wilkes Cellular Inc.', '311150', 'SUP'],
                     ['U.S. Cellular', '311220', 'SUP'],
                     ['Wave Runner LLC', '311250', 'SUP'],
                     ['Pinpoint Wireless Inc.', '311290', 'SUP'],
                     ['Leaco Rural Telephone Company Inc', '311310', 'SUP'],
                     ['Iowa RSA No. 2 Limited Partnership', '311410', 'SUP'],
                     ['ELECTRIC IMP INCORPORATED', '311460', 'SUP'],
                     ['North Dakota Network Co.', '311610', 'SUP'],
                     ['Midwest Network Solutions Hub, LLC. (MNS)', '311700', 'SUP'],
                     ['Northeast Wireless Networks LLC', '311710', 'SUP'],
                     ['Proximiti Mobility Inc', '311730', 'SUP'],
                     ['Flat Wireless, LLC', '311750', 'SUP'],
                     ['SI Wireless LLC', '311910', 'SUP'],
                     ['Missouri RSA No 5 Partnership', '311920', 'SUP'],
                     ['Chariton Valley Communications Corporation', '312010', 'SUP'],
                     ['CoverageCo', '312060', 'SUP'],
                     ['Iowa RSA No. 2 Limited Partnership', '312170', 'SUP'],
                     ['Chariton Valley Communications Corporation', '312220', 'SUP'],
                     ['SRT Communications Inc.', '312230', 'SUP'],
                     ['Sprint', '312240', 'SUP'],
                     ['Mid-Rivers Telephone Cooperative', '312400', 'SUP'],
                     ['TrustComm, Inc', '312490', 'SUP'],
                     ['Santel Communications Cooperative, Inc.', '312820', 'SUP'],
                     ['Flat Wireless, LLC', '312860', 'SUP'],
                     ['Northeast Wireless Networks', '312920', 'SUP'],
                     ['Webformix', '312940', 'SUP'],
                     ['M&A Technology, Inc.', '312960', 'SUP'],
                     ['Tennessee Wireless', '313000', 'SUP'],
                     ['Manti Tele Communications Company, Inc. dba Breakaway Wireless', '313050', 'SUP'],
                     ['Mercury Network Corporation', '313200', 'SUP'],
                     ['CAL.NET, INC', '313310', 'SUP'],
                     ['Florida Broadband, Inc', '313520', 'SUP'],
                     ['Sprint', '316010', 'SUP'],
                     ['Southern Communications Services Inc.', '316011', 'SUP'],
                     ['Mobi', '310040', 'ADD'],
                     ['Dish Wireless', '311200', 'ADD'],
                     ['U.S. Cellular', '311225', 'ADD'],
                     ['U.S. Cellular', '311228', 'ADD'],
                     ['U.S. Cellular', '311229', 'ADD'],
                     ['Mobi', '311500', 'ADD'],
                     ['Coeur Rochester, Inc', '311540', 'ADD'],
                     ['Mediacom', '311570', 'ADD'],
                     ['U.S. Cellular', '311588', 'ADD'],
                     ['U.S. Cellular', '311589', 'ADD'],
                     ['Cox Communications', '311930', 'ADD'],
                     ['ShawnTech Communications', '312610', 'ADD'],
                     ['Windstream Services LLC', '313780', 'ADD'],
                     ['Liberty Cablevision of Puerto Rico LLC', '313790', 'ADD'],
                     ['W.A.T.C.H. TV Co. dba Watch Communications', '313810', 'ADD'],
                     ['Inland Cellular Telephone Company', '313820', 'ADD'],
                     ['360 communications INC', '313830', 'ADD'],
                     ['Celblox Acquisitions', '313840', 'ADD'],
                     ['Softcom Internet Communications, Inc.', '313850', 'ADD'],
                     ['AMG Technology Investment Group dba Nextlink Internet', '313860', 'ADD'],
                     ['Elektrafi LLC', '313870', 'ADD'],
                     ['Shuttle Wireless Solutions Inc.', '313880', 'ADD'],
                     ['Tulare County Office of Education', '313890', 'ADD'],
                     ['All Tribal Networks', '313900', 'ADD'],
                     ['San Diego Gas and Electric', '313910', 'ADD'],
                     ['JCI US INC', '313920', 'ADD'],
                     ['Standing Rock Telecom', '313930', 'ADD'],
                     ['Motorola Solutions, Inc', '313940', 'ADD'],
                     ['Cheyenne and Arapaho Development Group', '313950', 'ADD'],
                     ['Townes 5G, LLC', '313960', 'ADD'],
                     ['Tychron Corporation', '313970', 'ADD'],
                     ['Ericsson US', '313990', 'ADD'],
                     ['Texas A&M University System – RELLIS Campus', '314060', 'ADD'],
                     ['Texas A&M University System – RELLIS Campus', '314070', 'ADD'],
                     ['Texas A&M University System – RELLIS Campus', '314080', 'ADD'],
                     ['Southern Communications Services, Inc. D/B/A Southern Linc', '314090', 'ADD'],
                     ['XF Wireless Investments', '314200', 'ADD'],
                     ['Telecom Resource Center', '314210', 'ADD'],
                     ['Secrus Technologies', '314220', 'ADD'],
                     ['Trace-Tek', '314230', 'ADD'],
                     ['XF Wireless Investments', '314240', 'ADD'],
                     ['AT&T Mobility', '314260', 'ADD'],
                     ['AT&T Mobility', '314270', 'ADD'],
                     ['Pollen Mobile LLC', '314280', 'ADD'],
                     ['Wave', '314290', 'ADD'],
                     ['Terranet', '314310', 'ADD'],
                     ['Agri-Valley Communications, Inc', '314320', 'ADD'],
                     ['Nova Labs Inc.', '314330', 'ADD'],
                     ['E-MARCONI LLC', '314340', 'ADD'],
                     ['Evergy', '314350', 'ADD'],
                     ['Oceus Networks, LLC', '314360', 'ADD'],
                     ['Texas A&M University', '314370', 'ADD'],
                     ['Circle Computer Resources, Inc.', '314380', 'ADD'],
                     ['AT&T', '314390', 'ADD'],
                     ['Cellular South Inc. dba C Spire', '314400', 'ADD'],
                     ['Peeringhub Inc', '314410', 'ADD'],
                     ['Cox Communications, Inc', '314420', 'ADD'],
                     ['Highway9 Networks, Inc.', '314430', 'ADD'],
                     ['Tecore Global Services, LLC', '314440', 'ADD'],
                     ['Mile High Networks LLC', '316700', 'ADD'],
                     ['PTI Pacifica, Inc.', '310110', 'LIR'],
                     ['T-Mobile USA', '310120', 'LIR'],
                     ['Eseye', '310460', 'LIR'],
                     ['PTI Pacifica, Inc.', '310480', 'LIR'],
                     ['T-Mobile', '310530', 'LIR'],
                     ['Choice Wireless', '310630', 'LIR'],
                     ['T-Mobile', '310770', 'LIR'],
                     ['T-Mobile USA', '310830', 'LIR'],
                     ['Tyntec Limited', '310940', 'LIR'],
                     ['PTI Pacifica, Inc.', '311120', 'LIR'],
                     ['T-Mobile', '311260', 'LIR'],
                     ['Verizon Wireless', '311440', 'LIR'],
                     ['T-Mobile USA', '311490', 'LIR'],
                     ['WorldCell Solutions LLC', '311530', 'LIR'],
                     ['Verizon Wireless', '311800', 'LIR'],
                     ['Verizon Wireless', '311810', 'LIR'],
                     ['Ribbon Communications', '311820', 'LIR'],
                     ['T-Mobile USA', '311870', 'LIR'],
                     ['T-Mobile USA', '311880', 'LIR'],
                     ['T-Mobile', '311882', 'LIR'],
                     ['T-Mobile USA', '311940', 'LIR'],
                     ['T-Mobile USA', '312190', 'LIR'],
                     ['T-Mobile USA', '312250', 'LIR'],
                     ['WorldCell Solutions LLC', '312260', 'LIR'],
                     ['T-Mobile USA', '312530', 'LIR'],
                     ['Google LLC', '312580', 'LIR'],
                     ['AT&T Mobility', '313030', 'LIR'],
                     ['Southern California Edison', '313300', 'LIR'],
                     ['Anterix Inc.', '313410', 'LIR'],
                     ['Mobi', '313460', 'LIR'],
                     ['Puerto Rico Telephone Company', '313510', 'LIR'],
                     ['Point Broadband Fiber Holding, LLC', '313610', 'LIR'],
                     ['Omniprophis Corporation', '313620', 'LIR'],
                     ['Extenet Systems', '313710', 'LIR'],
                     ['RTO Wireless', '313740', 'LIR'],
                     ['CellTex Networks, LLC', '313750', 'LIR'],
                     ['Hologram', '313760', 'LIR'],
                     ['World Mobile Networks, Inc', '310420', 'ADD'],
                     ['NUWAVE Communications, Inc.', '314450', 'ADD'],
                     ['Texas A&M University', '314460', 'ADD'],
                     ['Manhattan Telecommunications Corporation LLC', '314470', 'ADD'],
                     ['Xcel Energy Services Inc.', '314480', 'ADD'],
                     ['Utah Education and Telehealth Network (UETN)', '314490', 'ADD'],
                     ['Boldyn Networks Transit US LLC', '313560', 'LIR']],
  'Uruguay': [ ['Ancel - TDMA', '74800', 'SUP'],
               ['Ancel', '74803', 'SUP'],
               ['Administración Nacional de Telecomunicaciones (ANTEL)', '74801', 'LIR'],
               ['Telefónica Móviles del Uruguay S.A. (Movistar)', '74807', 'LIR'],
               ['AM Wireless Uruguay S.A. (Claro)', '74810', 'LIR'],
               ['ENALUR S.A.', '74815', 'ADD']],
  'Venezuela (Bolivarian Republic of)': [['PATRIACELL C.A.', '73408', 'ADD']],
  'Viet Nam': [ ['S Telecom (CDMA)', '45203', 'SUP'],
                ['EVN Telecom', '45206', 'SUP'],
                ['I-Telecom', '45208', 'ADD'],
                ['Vietnamobile', '45205', 'ADD'],
                ['Gmobile', '45207', 'LIR'],
                ['REDDI', '45209', 'ADD']],
  'Zambia': [ ['Liquid Telecom Zambia Limited', '64507', 'ADD'],
              ['Airtel Zambia Limited', '64501', 'LIR'],
              ['MTN Zambia Limited', '64502', 'LIR']]}
