# -*- coding: UTF-8 -*-
# source: https://www.itu.int/pub/T-SP
# license: https://www.itu.int/pub/T-SP

ITUT_MNC_INCR = \
{ '20400': ('Intovoice B.V.', 'Netherlands', 'ADD'),
  '20401': ('RadioAccess Network Services B.V.', 'Netherlands', 'SUP'),
  '20402': ('T-Mobile Netherlands B.V.', 'Netherlands', 'LIR'),
  '20405': ('Elephant Talk Communications Premium Rate Services', 'Netherlands', 'SUP'),
  '20406': ('Mundio Mobile (Netherlands) Ltd', 'Netherlands', 'SUP'),
  '20407': ('Tata Communications MOVE B.V.', 'Netherlands', 'LIR'),
  '20408': ('KPN B.V.', 'Netherlands', 'LIR'),
  '20411': ('Greenet Netwerk B.V.', 'Netherlands', 'ADD'),
  '20414': ('Venus & Mercury Telecom', 'Netherlands', 'ADD'),
  '20417': ('Lebara Ltd', 'Netherlands', 'ADD'),
  '20418': ('Ziggo Services B.V.', 'Netherlands', 'LIR'),
  '20423': ('KORE Wireless Nederland B.V.', 'Netherlands', 'LIR'),
  '20424': ('PM Factory B.V.', 'Netherlands', 'LIR'),
  '20425': ('CapX Nederland', 'Netherlands', 'LIR'),
  '20427': ('L-Mobi Mobile B.V.', 'Netherlands', 'ADD'),
  '20429': ('Tismi B.V.', 'Netherlands', 'ADD'),
  '20430': ('ASpider Solutions Nederland B.V.', 'Netherlands', 'ADD'),
  '20432': ('Cubic Telecom Limited', 'Netherlands', 'ADD'),
  '20433': ('Truphone B.V.', 'Netherlands', 'ADD'),
  '20460': ('Nextgen Mobile Ltd', 'Netherlands', 'SUP'),
  '20461': ('Alcadis B.V.', 'Netherlands', 'ADD'),
  '20462': ('RGTN Wholesale Netherlands B.V.', 'Netherlands', 'ADD'),
  '20463': ('Messagebird BV', 'Netherlands', 'ADD'),
  '20465': ('AGMS Nederland B.V.', 'Netherlands', 'SUP'),
  '20467': ('RadioAccess B.V.', 'Netherlands', 'SUP'),
  '20468': ('Roamware (Netherlands) B.V.', 'Netherlands', 'SUP'),
  '20469': ('KPN B.V.', 'Netherlands', 'LIR'),
  '20491': ('Enexis Netbeheer B.V.', 'Netherlands', 'ADD'),
  '20603': ('Citymesh', 'Belgium', 'ADD'),
  '20604': ('MWINGZ (Proximus/Orange Belgium)', 'Belgium', 'ADD'),
  '20611': ('L-Mobi Mobile', 'Belgium', 'ADD'),
  '20622': ('FEBO Telecom', 'Belgium', 'ADD'),
  '20629': ('TISMI', 'Belgium', 'ADD'),
  '20634': ('ONOFFAPP', 'Belgium', 'ADD'),
  '20640': ('Join Experience (Belgium)', 'Belgium', 'SUP'),
  '20699': ('e-BO Enterprises', 'Belgium', 'ADD'),
  '20812': ('Truphone France', 'France', 'ADD'),
  '20819': ('Haute-Garonne numérique', 'France', 'LIR'),
  '20826': ('Bouygues Telecom Business - Distribution', 'France', 'LIR'),
  '20828': ('Airmob Infra Full', 'France', 'LIR'),
  '20830': ('Syma', 'France', 'LIR'),
  '20833': ('Syndicat mixte La Fibre64', 'France', 'LIR'),
  '20834': ('Cellhire (France)', 'France', 'ADD'),
  '20835': ('Free mobile', 'France', 'ADD'),
  '20836': ('Free mobile', 'France', 'ADD'),
  '20837': ('IP Directions', 'France', 'ADD'),
  '20838': ('Lebara France Limited', 'France', 'ADD'),
  '20839': ('Netwo', 'France', 'ADD'),
  '208501': ('Butachimie', 'France', 'ADD'),
  '208502': ('EDF', 'France', 'ADD'),
  '208701': ('GIP Vendée numérique', 'France', 'ADD'),
  '208702': ('17-Numerique', 'France', 'ADD'),
  '208703': ('Nivertel', 'France', 'ADD'),
  '208704': ('Axione Limousin', 'France', 'ADD'),
  '208705': ('Hautes-Pyrénées Numérique', 'France', 'ADD'),
  '208706': ('Tours Métropole Numérique', 'France', 'ADD'),
  '208707': ('Sartel THD', 'France', 'ADD'),
  '208708': ('Melis@ territoires ruraux', 'France', 'ADD'),
  '208709': ('Quimper communauté télécom', 'France', 'ADD'),
  '208710': ('Losange', 'France', 'ADD'),
  '208711': ('Nomotech', 'France', 'ADD'),
  '208712': ("Syndicat Audois d'énergies et du Numérique", 'France', 'ADD'),
  '208713': ('SD NUM SAS', 'France', 'ADD'),
  '208714': ("Département de l'Isère", 'France', 'ADD'),
  '20887': ('Airbus defence and space SAS', 'France', 'LIR'),
  '20889': ('Hub One', 'France', 'LIR'),
  '20893': ('Thales communications & Security', 'France', 'SUP'),
  '20895': ('Orange', 'France', 'SUP'),
  '20896': ('Région Bourgogne-Franche-Comté', 'France', 'LIR'),
  '20898': ('Société Air France', 'France', 'SUP'),
  '21412': ('VENUS MOVIL, S.L. UNIPERSONAL', 'Spain', 'ADD'),
  '21413': ('SYMA MOBILE ESPAÑA, S.L.', 'Spain', 'SUP'),
  '21414': ('AVATEL MÓVIL, S.L.U.', 'Spain', 'ADD'),
  '21416': ('R CABLE Y TELECOMUNICACIONES GALICIA, S.A.', 'Spain', 'LIR'),
  '21421': ('ORANGE ESPAGNE, S.A. UNIPERSONAL', 'Spain', 'SUP'),
  '21423': ('Xfera Móviles, S.A.U.', 'Spain', 'ADD'),
  '21424': ('VODAFONE ESPAÑA, S.A.U.', 'Spain', 'LIR'),
  '21425': ('XFERA MÓVILES, S.A. UNIPERSONAL', 'Spain', 'ADD'),
  '21429': ('XFERA MÓVILES, S.A.U.', 'Spain', 'ADD'),
  '21430': ('Compatel Limited', 'Spain', 'SUP'),
  '21432': ('Telefónica Móviles España, SAU', 'Spain', 'SUP'),
  '21433': ('XFERA MÓVILES, S.A.U.', 'Spain', 'SUP'),
  '21436': ('ALAI OPERADOR DE TELECOMUNICACIONES, S.L.', 'Spain', 'ADD'),
  '21437': ('VODAFONE ESPAÑA, S.A.U.', 'Spain', 'ADD'),
  '21438': ('Telefónica Móviles España, SAU', 'Spain', 'ADD'),
  '214700': ('IBERDROLA ESPAÑA, S.A.UNIPERSONAL', 'Spain', 'ADD'),
  '214701': ('ENDESA DISTRIBUCIÓN ELÉCTRICA, S.L.', 'Spain', 'ADD'),
  '21601': ('Yettel Hungary Ltd.', 'Hungary', 'LIR'),
  '21604': ('Invitech ICT Services Ltd.', 'Hungary', 'SUP'),
  '21620': ('Yettel Hungary Ltd.', 'Hungary', 'ADD'),
  '21671': ('Vodafone Hungary Ltd', 'Hungary', 'LIR'),
  '22107': ('Dukagjini Telecommunications LLC', 'Kosovo*', 'ADD'),
  '22808': ('Sunrise Communications AG', 'Switzerland', 'LIR'),
  '22859': ('Vectone Mobile Limited, London', 'Switzerland', 'ADD'),
  '22861': ('Compatel Ltd', 'Switzerland', 'SUP'),
  '22862': ('Telecom26 AG', 'Switzerland', 'ADD'),
  '22863': ('Fink Telecom Services', 'Switzerland', 'ADD'),
  '22864': ('NTH AG', 'Switzerland', 'ADD'),
  '22866': ('Inovia Services SA', 'Switzerland', 'ADD'),
  '22867': ('Datatrade Managed AG', 'Switzerland', 'ADD'),
  '22868': ('Intellico AG', 'Switzerland', 'ADD'),
  '22869': ('MTEL Schweiz GmbH', 'Switzerland', 'ADD'),
  '22870': ('Tismi BV', 'Switzerland', 'ADD'),
  '23002': ('O2 Czech Republic a.s.', 'Czech Rep.', 'LIR'),
  '23004': ('Nordic Telecom s.r.o.', 'Czech Rep.', 'LIR'),
  '23007': ('T-Mobile Czech Republic a.s.', 'Czech Rep.', 'ADD'),
  '23009': ('Uniphone, s.r.o.', 'Czech Rep.', 'ADD'),
  '23098': ('Sprava zeleznic, statni organizace', 'Czech Rep.', 'LIR'),
  '23401': ('Vectone Mobile Limited', 'United Kingdom', 'LIR'),
  '23405': ('COLT Mobile Telecommunications Limited', 'United Kingdom', 'SUP'),
  '23406': ('Internet Computer Bureau Limited', 'United Kingdom', 'SUP'),
  '23407': ('Vodafone Ltd (C&W)', 'United Kingdom', 'SUP'),
  '23414': ('LINK MOBILITY UK LTD', 'United Kingdom', 'LIR'),
  '23415': ('Vodafone Limited', 'United Kingdom', 'LIR'),
  '23417': ('FleXtel Limited', 'United Kingdom', 'SUP'),
  '23419': ('TeleWare Group PLC', 'United Kingdom', 'LIR'),
  '23427': ('Tata Communications Move UK Ltd', 'United Kingdom', 'LIR'),
  '23429': ('(AQ) LIMITED', 'United Kingdom', 'LIR'),
  '23433': ('EE Limited (Orange)', 'United Kingdom', 'LIR'),
  '23434': ('EE Limited (Orange)', 'United Kingdom', 'LIR'),
  '23440': ('Mass Response Service GmbH', 'United Kingdom', 'ADD'),
  '23450': ('JT (Jersey) Limited', 'United Kingdom', 'LIR'),
  '23453': ('Tango Networks UK Ltd', 'United Kingdom', 'LIR'),
  '23456': ('The National Cyber Security Centre', 'United Kingdom', 'LIR'),
  '23458': ('MANX TELECOM TRADING LIMITED', 'United Kingdom', 'LIR'),
  '23459': ('Limitless Mobile Ltd', 'United Kingdom', 'SUP'),
  '23470': ('AMSUK Limited', 'United Kingdom', 'SUP'),
  '23472': ('Hanhaa Limited', 'United Kingdom', 'ADD'),
  '23473': ('BlueWave Communications', 'United Kingdom', 'ADD'),
  '23474': ('Pareteum Europe B.V.', 'United Kingdom', 'ADD'),
  '23477': ('Vodafone Limited', 'United Kingdom', 'ADD'),
  '23488': ('Telet Research (N.I.) Limited', 'United Kingdom', 'ADD'),
  '23500': ('Vectone Mobile Limited', 'United Kingdom', 'LIR'),
  '23504': ('University Of Strathclyde', 'United Kingdom', 'ADD'),
  '23506': ('University Of Strathclyde', 'United Kingdom', 'ADD'),
  '23507': ('University Of Strathclyde', 'United Kingdom', 'ADD'),
  '23508': ('Spitfire Network Services Limited', 'United Kingdom', 'ADD'),
  '23588': ('Telet Research (N.I.) Limited', 'United Kingdom', 'ADD'),
  '23591': ('Vodafone Limited', 'United Kingdom', 'LIR'),
  '23592': ('Vodafone Ltd (C&W)', 'United Kingdom', 'SUP'),
  '23817': ('Gotanet AB', 'Denmark', 'ADD'),
  '23877': ('Telenor', 'Denmark', 'SUP'),
  '23888': ('Cobira ApS', 'Denmark', 'ADD'),
  '23896': ('Telia Danmark', 'Denmark', 'ADD'),
  '24003': ('Teracom AB', 'Sweden', 'LIR'),
  '24013': ('Bredband2 Företag AB', 'Sweden', 'LIR'),
  '24014': ('Tele2 Sverige AB', 'Sweden', 'LIR'),
  '24020': ('Sierra Wireless Messaging AB', 'Sweden', 'LIR'),
  '24026': ('Twilio Ireland Ltd.', 'Sweden', 'LIR'),
  '24028': ('LINK Mobile A/S', 'Sweden', 'SUP'),
  '24029': ('MI Carrier Services AB', 'Sweden', 'LIR'),
  '24030': ('NextGen Mobile Ltd.', 'Sweden', 'SUP'),
  '24037': ('Sinch Sweden AB', 'Sweden', 'LIR'),
  '24039': ('Primlight AB', 'Sweden', 'LIR'),
  '24040': ('Netmore Group AB', 'Sweden', 'LIR'),
  '24041': ('Telenor Sverige AB', 'Sweden', 'ADD'),
  '24048': ('Tismi BV', 'Sweden', 'ADD'),
  '24049': ('Telia Sverige AB', 'Sweden', 'ADD'),
  '24060': ('Västra Götalandsregionen (temporary assigned until 2026-12-31)', 'Sweden', 'ADD'),
  '24061': ('MessageBird B.V.', 'Sweden', 'SUP'),
  '24063': ('Fink Telecom Services', 'Sweden', 'ADD'),
  '24805': ('CSC Telecom Estonia OÜ', 'Estonia', 'ADD'),
  '24815': ('Premium Net International S.R.L. Eesti filiaal', 'Estonia', 'SUP'),
  '24816': ('SmartTel Plus OÜ', 'Estonia', 'ADD'),
  '24817': ('Baltergo OÜ', 'Estonia', 'ADD'),
  '24818': ('CLOUD COMMUNICATIONS OÜ', 'Estonia', 'ADD'),
  '24819': ('OkTelecom OÜ', 'Estonia', 'ADD'),
  '24820': ('DOTT Telecom OÜ', 'Estonia', 'ADD'),
  '24821': ('Tismi B.V.', 'Estonia', 'ADD'),
  '24822': ('M2MConnect OÜ', 'Estonia', 'ADD'),
  '24824': ('Novametro OÜ', 'Estonia', 'ADD'),
  '24825': ('Eurofed OÜ', 'Estonia', 'ADD'),
  '24826': ('IT-Decision Telecom OÜ', 'Estonia', 'ADD'),
  '24828': ('Nord Connect OÜ', 'Estonia', 'ADD'),
  '25501': ('"VF UKRAINE" PrJSC', 'Ukraine', 'LIR'),
  '25502': ('"Kyivstar" PrJSC', 'Ukraine', 'LIR'),
  '25503': ('"Kyivstar" PrJSC', 'Ukraine', 'LIR'),
  '25504': ('"Intertelecom" LLC', 'Ukraine', 'LIR'),
  '25506': ('"lifecell" LLC', 'Ukraine', 'LIR'),
  '25507': ('"TriMob" LLC', 'Ukraine', 'LIR'),
  '25508': ('"Ukrtelecom" JSC', 'Ukraine', 'ADD'),
  '25509': ('"Farlep-Invest", PrJSC', 'Ukraine', 'ADD'),
  '25510': ('"Atlantis Telecom", LLC', 'Ukraine', 'ADD'),
  '25521': ('"Telesystems of Ukraine" PrJSC', 'Ukraine', 'LIR'),
  '26603': ('GibFibre Ltd (trading as “Gibfibrespeed”)', 'Gibraltar', 'ADD'),
  '27005': ('Luxembourg Online S.A.', 'Luxembourg', 'ADD'),
  '27077': ('Proximus Luxembourg S.A.', 'Luxembourg', 'LIR'),
  '27221': ('Net Feasa Limited', 'Ireland', 'ADD'),
  '27268': ('Office of the Government Chief Information Officer', 'Ireland', 'ADD'),
  '27601': ('ONE TELECOMMUNICATIONS sh.a', 'Albania', 'LIR'),
  '27603': ('ALBTELECOM sh.a.', 'Albania', 'LIR'),
  '27604': ('Mobile 4 AL', 'Albania', 'SUP'),
  '27801': ('Epic Communications Ltd', 'Malta', 'LIR'),
  '27811': ('YOM', 'Malta', 'SUP'),
  '27877': ('Melita Ltd', 'Malta', 'LIR'),
  '28002': ('CYTA', 'Cyprus', 'ADD'),
  '28023': ('Mundio Mobile Cyprus Ltd', 'Cyprus', 'SUP'),
  '28212': ('"Telecom1" LTD', 'Georgia', 'LIR'),
  '28213': ('"Asanet" LTD', 'Georgia', 'ADD'),
  '28214': ('"Datahouseglobal” LTD', 'Georgia', 'ADD'),
  '28215': ('"Servicebox" LTD', 'Georgia', 'ADD'),
  '28222': ('"Myphone" LTD', 'Georgia', 'ADD'),
  '28803': ('Sp/f Tosa', 'Faroe Islands', 'SUP'),
  '29311': ('BeeIN d.o.o.', 'Slovenia', 'ADD'),
  '29321': ('Novatel d.o.o.', 'Slovenia', 'ADD'),
  '29412': ('MTEL DOOEL Skopje', 'North Macedonia', 'ADD'),
  '29507': ('First Mobile AG', 'Liechtenstein', 'SUP'),
  '29510': ('SORACOM CORPORATION, LTD.', 'Liechtenstein', 'LIR'),
  '29511': ('DIMOCO Messaging AG', 'Liechtenstein', 'ADD'),
  '302150': ('Cogeco Connexion Inc.', 'Canada', 'ADD'),
  '302151': ('Cogeco Connexion Inc.', 'Canada', 'ADD'),
  '302152': ('Cogeco Connexion Inc.', 'Canada', 'ADD'),
  '302230': ('ISP Telecom', 'Canada', 'ADD'),
  '302330': ('Blue Canada Wireless Inc', 'Canada', 'SUP'),
  '302350': ('Naskapi Imuun Inc.', 'Canada', 'ADD'),
  '302550': ('Star Solutions International Inc.', 'Canada', 'ADD'),
  '302570': ('Ligado Networks Corp.', 'Canada', 'LIR'),
  '302721': ('Rogers Communications Canada Inc. (Wireless)', 'Canada', 'ADD'),
  '302770': ('TNW Wireless Inc.', 'Canada', 'LIR'),
  '302848': ('Vocom International Telecommunications, Inc', 'Canada', 'ADD'),
  '302910': ('Halton Regional Police Service (reserved)', 'Canada', 'ADD'),
  '302996': ('Powertech Labs (experimental)', 'Canada', 'ADD'),
  '302998': ('Institut de Recherche d’Hydro-Québec (experimental)', 'Canada', 'ADD'),
  '30803': ('SAS SPM Telecom', 'Saint Pierre and Miquelon', 'ADD'),
  '310040': ('MTA Communications dba MTA Wireless', 'United States', 'SUP'),
  '310060': ('Consolidated Telcom', 'United States', 'SUP'),
  '310300': ('Blanca Telephone Company', 'United States', 'SUP'),
  '310330': ('Wireless Partners LLC', 'United States', 'ADD'),
  '310340': ('Limitless Mobile, LLC', 'United States', 'ADD'),
  '310470': ('Docomo Pacific Inc', 'United States', 'LIR'),
  '310570': ('Broadpoint, LLC (former PetroCom, LLC) c/o MTPCS, LLC dba CellularOne', 'United States', 'LIR'),
  '310591': ('Verizon Wireless', 'United States', 'ADD'),
  '310592': ('Verizon Wireless', 'United States', 'ADD'),
  '310593': ('Verizon Wireless', 'United States', 'ADD'),
  '310594': ('Verizon Wireless', 'United States', 'ADD'),
  '310595': ('Verizon Wireless', 'United States', 'ADD'),
  '310596': ('Verizon Wireless', 'United States', 'ADD'),
  '310597': ('Verizon Wireless', 'United States', 'ADD'),
  '310598': ('Verizon Wireless', 'United States', 'ADD'),
  '310599': ('Verizon Wireless', 'United States', 'ADD'),
  '310610': ('Elkhart Telephone Co. Inc. dba Epic Touch Co.', 'United States', 'SUP'),
  '310620': ('Nsighttel Wireless, LLC', 'United States', 'LIR'),
  '310690': ('Limitless Mobile, LLC', 'United States', 'LIR'),
  '310780': ('D.D. Inc', 'United States', 'SUP'),
  '310810': ('Pacific Lightwave Inc.', 'United States', 'ADD'),
  '310891': ('Verizon Wireless', 'United States', 'ADD'),
  '310892': ('Verizon Wireless', 'United States', 'ADD'),
  '310893': ('Verizon Wireless', 'United States', 'ADD'),
  '310894': ('Verizon Wireless', 'United States', 'ADD'),
  '310895': ('Verizon Wireless', 'United States', 'ADD'),
  '310896': ('Verizon Wireless', 'United States', 'ADD'),
  '310897': ('Verizon Wireless', 'United States', 'ADD'),
  '310898': ('Verizon Wireless', 'United States', 'ADD'),
  '310899': ('Verizon Wireless', 'United States', 'ADD'),
  '310940': ('Tyntec Inc.', 'United States', 'LIR'),
  '310990': ('Evolve Cellular Inc.', 'United States', 'LIR'),
  '311010': ('Chariton Valley Communications Corporation', 'United States', 'LIR'),
  '311170': ('Tampnet (formerly Broadpoint, LLC (former PetroCom, LLC) c/o MTPCS, LL', 'United States', 'LIR'),
  '311200': ('ARINC', 'United States', 'SUP'),
  '311210': ('Telnyx LLC', 'United States', 'ADD'),
  '311300': ('Nexus Communications Inc', 'United States', 'SUP'),
  '311460': ('ELECTRIC IMP INCORPORATED', 'United States', 'ADD'),
  '311500': ('Mosaic Telecom Inc', 'United States', 'SUP'),
  '311510': ('Ligado Networks', 'United States', 'LIR'),
  '311550': ('Commnet Wireless, LLC', 'United States', 'LIR'),
  '311600': ('Limitless Mobile, LLC', 'United States', 'ADD'),
  '311700': ('Midwest Network Solutions Hub, LLC. (MNS)', 'United States', 'LIR'),
  '311760': ('Reclaimed 06/21/2016', 'United States', 'ADD'),
  '311780': ('The American Samoa Telecommunications Authority', 'United States', 'ADD'),
  '311882': ('Sprint', 'United States', 'ADD'),
  '311920': ('Missouri RSA No 5 Partnership', 'United States', 'LIR'),
  '311960': ('Lycamobile USA Inc', 'United States', 'SUP'),
  '312010': ('Chariton Valley Communications Corporation', 'United States', 'LIR'),
  '312050': ('Fuego Wireless LLC', 'United States', 'SUP'),
  '312070': ('Adams Networks Inc', 'United States', 'SUP'),
  '312140': ('Cleveland Unlimited Inc', 'United States', 'SUP'),
  '312180': ('Limitless Mobile, LLC', 'United States', 'LIR'),
  '312220': ('Chariton Valley Communications Corporation', 'United States', 'LIR'),
  '312340': ('MTA Communications dba MTA Wireless', 'United States', 'SUP'),
  '312440': ('Consolidated Telcom', 'United States', 'SUP'),
  '312650': ('Brightlink', 'United States', 'LIR'),
  '312690': ('TGS, LLC', 'United States', 'LIR'),
  '312740': ('KDDI America, Inc dba Locus Telecommunications', 'United States', 'SUP'),
  '312990': ('PREMIER HOLDINGS, LLC', 'United States', 'LIR'),
  '313061': ('Country Wireless', 'United States', 'ADD'),
  '313100': ('AT&T FirstNet', 'United States', 'LIR'),
  '313110': ('AT&T FirstNet', 'United States', 'ADD'),
  '313120': ('AT&T FirstNet', 'United States', 'ADD'),
  '313130': ('AT&T FirstNet', 'United States', 'ADD'),
  '313140': ('AT&T FirstNet', 'United States', 'ADD'),
  '313150': ('RESERVED FOR PUBLIC SAFETY', 'United States', 'ADD'),
  '313160': ('RESERVED FOR PUBLIC SAFETY', 'United States', 'ADD'),
  '313170': ('RESERVED FOR PUBLIC SAFETY', 'United States', 'ADD'),
  '313180': ('RESERVED FOR PUBLIC SAFETY', 'United States', 'ADD'),
  '313190': ('RESERVED FOR PUBLIC SAFETY', 'United States', 'ADD'),
  '313210': ('AT&T Mobility', 'United States', 'LIR'),
  '313220': ('Custer Telephone Cooperative,Inc.', 'United States', 'ADD'),
  '313230': ('Velocity Communications Inc', 'United States', 'ADD'),
  '313240': ('Fundamental Holdings, Corp', 'United States', 'ADD'),
  '313250': ('Imperial County Office of Education', 'United States', 'ADD'),
  '313260': ('Expeto Wireless Inc.', 'United States', 'ADD'),
  '313280': ('King Street Wireless, LP', 'United States', 'ADD'),
  '313290': ('Gulf Coast Broadband LLC', 'United States', 'ADD'),
  '313300': ('Cambio WiFi of Delmarva, LLC.', 'United States', 'ADD'),
  '313310': ('CAL.NET, INC', 'United States', 'ADD'),
  '313320': ('Paladin Wireless', 'United States', 'ADD'),
  '313330': ('CenturyTel Broadband Services LLC', 'United States', 'ADD'),
  '313340': ('Dish Network', 'United States', 'ADD'),
  '313350': ('Dish Network', 'United States', 'ADD'),
  '313360': ('Dish Network', 'United States', 'ADD'),
  '313370': ('Red Truck Wireless, LLC', 'United States', 'ADD'),
  '313380': ('OptimERA Inc.', 'United States', 'ADD'),
  '313390': ('Altice USA Wireless, Inc.', 'United States', 'ADD'),
  '313400': ('Texoma Communications, LLC', 'United States', 'ADD'),
  '313410': ('pdvWireless', 'United States', 'ADD'),
  '313420': ('Hudson Valley Wireless', 'United States', 'ADD'),
  '313440': ('Arvig Enterprises INC', 'United States', 'ADD'),
  '313450': ('Spectrum Wireless Holdings, LLC', 'United States', 'ADD'),
  '313460': ('Mobi, Inc.', 'United States', 'ADD'),
  '313470': ('San Diego Gas & Electric Company', 'United States', 'ADD'),
  '313480': ('Ready Wireless, LLC', 'United States', 'ADD'),
  '313490': ('Puloli, Inc', 'United States', 'ADD'),
  '313500': ('Shelcomm, Inc', 'United States', 'ADD'),
  '313510': ('Puerto Rico Telecom Company', 'United States', 'ADD'),
  '313520': ('Florida Broadband, Inc', 'United States', 'ADD'),
  '313540': ('Nokia Innovations US LLC', 'United States', 'ADD'),
  '313550': ('Mile High Networks LLC', 'United States', 'ADD'),
  '313560': ('Transit Wireless, LLC', 'United States', 'ADD'),
  '313570': ('Celular Network Partnership', 'United States', 'ADD'),
  '313580': ('Telecall Telecommuncations Corp.', 'United States', 'ADD'),
  '313590': ('Southern Communications Services, Inc. D/B/A Southern Linc', 'United States', 'ADD'),
  '313600': ('ST Engineering iDirect', 'United States', 'ADD'),
  '313610': ('Crystal Automation Systems, Inc.', 'United States', 'ADD'),
  '313620': ('Screened Images', 'United States', 'ADD'),
  '313630': ('LICT Corporation', 'United States', 'ADD'),
  '313640': ('Geoverse', 'United States', 'ADD'),
  '313650': ('Chevron USA INC', 'United States', 'ADD'),
  '313660': ('Hudson Valley Wireless', 'United States', 'ADD'),
  '313670': ('Hudson Valley Wireless', 'United States', 'ADD'),
  '313680': ('Hudson Valley Wireless', 'United States', 'ADD'),
  '313690': ('Shenandoah Cable Television, LLC', 'United States', 'ADD'),
  '313700': ('Ameren Services Company', 'United States', 'ADD'),
  '313710': ('Extent Systems', 'United States', 'ADD'),
  '313720': ('1st Point Communications, LLC', 'United States', 'ADD'),
  '313730': ('TruAccess Networks', 'United States', 'ADD'),
  '313740': ('RTO Wireless, LLC', 'United States', 'ADD'),
  '313750': ('313-CellTex Networks, LLC', 'United States', 'ADD'),
  '313760': ('Hologram, Inc.', 'United States', 'ADD'),
  '313770': ('Tango Networks', 'United States', 'ADD'),
  '314010': ('Boingo Wireless Inc', 'United States', 'ADD'),
  '314020': ('Spectrum Wireless Holdings, LLC', 'United States', 'ADD'),
  '314030': ('Baicells Technologies North America Inc.', 'United States', 'ADD'),
  '314100': ('RESERVED FOR PUBLIC SAFETY', 'United States', 'ADD'),
  '314110': ('RESERVED FOR PUBLIC SAFETY', 'United States', 'ADD'),
  '314120': ('RESERVED FOR PUBLIC SAFETY', 'United States', 'ADD'),
  '314130': ('RESERVED FOR PUBLIC SAFETY', 'United States', 'ADD'),
  '314140': ('RESERVED FOR PUBLIC SAFETY', 'United States', 'ADD'),
  '314150': ('RESERVED FOR PUBLIC SAFETY', 'United States', 'ADD'),
  '314160': ('RESERVED FOR PUBLIC SAFETY', 'United States', 'ADD'),
  '314170': ('RESERVED FOR PUBLIC SAFETY', 'United States', 'ADD'),
  '314180': ('RESERVED FOR PUBLIC SAFETY', 'United States', 'ADD'),
  '314190': ('RESERVED FOR PUBLIC SAFETY', 'United States', 'ADD'),
  '334010': ('AT&T COMUNICACIONES DIGITALES, S. DE R.L. DE C.V.', 'Mexico', 'LIR'),
  '334030': ('PEGASO PCS, S.A. DE C.V.', 'Mexico', 'LIR'),
  '334040': ( 'AT&T NORTE, S. DE R.L. DE C.V. Y AT&T DESARROLLO EN COMUNICACIONES DE MÉXICO, S. DE R.L. DE C.V.',
              'Mexico',
              'LIR'),
  '334050': ('GRUPO AT&T CELULLAR, S. DE R.L. DE C.V.', 'Mexico', 'LIR'),
  '334070': ('AT&T COMERCIALIZACIÓN MÓVIL, S. DE R.L. DE C.V.', 'Mexico', 'LIR'),
  '334080': ('AT&T COMERCIALIZACIÓN MÓVIL, S. DE R.L. DE C.V.', 'Mexico', 'LIR'),
  '334090': ('AT&T COMUNICACIONES DIGITALES, S. DE R.L. DE C.V.', 'Mexico', 'LIR'),
  '334100': ('TELECOMUNICACIONES DE MÉXICO', 'Mexico', 'ADD'),
  '334110': ('MAXCOM TELECOMUNICACIONES, S.A.B. DE C.V.', 'Mexico', 'ADD'),
  '334120': ('QUICKLY PHONE, S.A. DE C.V.', 'Mexico', 'ADD'),
  '334130': ('AXTEL, S.A.B. DE C.V.', 'Mexico', 'ADD'),
  '334140': ('ALTÁN REDES, S.A.P.I. DE C.V.', 'Mexico', 'ADD'),
  '334150': ('ULTRAVISIÓN, S.A. DE C.V.', 'Mexico', 'ADD'),
  '334160': ('CABLEVISIÓN RED, S.A. DE C.V.', 'Mexico', 'ADD'),
  '334170': ('OXIO MOBILE, S.A. DE C.V.', 'Mexico', 'ADD'),
  '334180': ('FREEDOMPOP MÉXICO, S.A. DE C.V.', 'Mexico', 'ADD'),
  '334190': ('VIASAT TECNOLOGÍA, S.A. DE C.V.', 'Mexico', 'ADD'),
  '338040': ('Symbiote Investment Limited', 'Jamaica', 'SUP'),
  '338080': ('Rock Mobile Limited', 'Jamaica', 'ADD'),
  '34004': ('Free Caraïbe', 'Guadeloupe', 'SUP'),
  '34011': ('Guyane Téléphone Mobile', 'French Guiana', 'SUP'),
  '34012': ('Martinique Téléphone Mobile', 'Martinique', 'SUP'),
  '342600': ('Cable & Wireless', 'Barbados', 'LIR'),
  '342646': ('KW Telecommunications Inc.', 'Barbados', 'ADD'),
  '342800': ('Ozone', 'Barbados', 'ADD'),
  '342820': ('Neptune Communications Inc.', 'Barbados', 'ADD'),
  '346001': ('WestTel Ltd., trading as Logic', 'Cayman Islands', 'ADD'),
  '350007': ('Paradise Mobile', 'Bermuda', 'ADD'),
  '35015': ('FKB Net Ltd.', 'Bermuda', 'ADD'),
  '376351': ('Digicel TCI Ltd', 'Turks and Caicos Islands', 'SUP'),
  '376352': ('IslandCom Communication Ltd.', 'Turks and Caicos Islands', 'SUP'),
  '376360': ('Digicel', 'Turks and Caicos Islands', 'ADD'),
  '40211': ('Bhutan Telecom Limited (Bmobile)', 'Bhutan', 'LIR'),
  '40217': ('Bhutan Telecom Limited (Bmobile)', 'Bhutan', 'LIR'),
  '40277': ('Tashi InfoComm Limited (Tashi Cell)', 'Bhutan', 'ADD'),
  '41303': ('Hutchison Telecommunications Lanka (Pvt) Ltd.', 'Sri Lanka', 'SUP'),
  '41309': ('Hutchison Telecommunications Lanka (Pvt) Ltd.', 'Sri Lanka', 'SUP'),
  '41702': ('MTN Syria', 'Syrian Arab Republic', 'ADD'),
  '41703': ('WAFA Telecom', 'Syrian Arab Republic', 'ADD'),
  '42206': ('Vodafone Oman', 'Oman', 'ADD'),
  '42522': ('Maskyoo Telephonia Ltd.', 'Israel', 'ADD'),
  '42527': ('BITIT Ltd.', 'Israel', 'ADD'),
  '42606': ('STC Bahrain', 'Bahrain', 'ADD'),
  '42607': ('TAIF', 'Bahrain', 'ADD'),
  '43201': ('KISH CELL PARS', 'Iran (Islamic Republic of)', 'ADD'),
  '43202': ('NEGIN ERTEBATAT AVA', 'Iran (Islamic Republic of)', 'ADD'),
  '43203': ('PARSIAN HAMRAH LOTUS', 'Iran (Islamic Republic of)', 'ADD'),
  '43204': ('TOSE E FANAVARI ERTEBATAT NOVIN HAMRAH', 'Iran (Islamic Republic of)', 'ADD'),
  '43205': ('HAMRAH HOSHMAND AYANDEH', 'Iran (Islamic Republic of)', 'ADD'),
  '43206': ('ERTEBATAT ARYANTEL', 'Iran (Islamic Republic of)', 'ADD'),
  '43207': ('HOOSHMAND AMIN MOBILE', 'Iran (Islamic Republic of)', 'ADD'),
  '43208': ('TOSE-E ERTEBATAT HAMRAH SHATEL', 'Iran (Islamic Republic of)', 'LIR'),
  '43209': ('HIWEB', 'Iran (Islamic Republic of)', 'ADD'),
  '43211': ('MCI (Mobile Communications of Iran)', 'Iran (Islamic Republic of)', 'LIR'),
  '43212': ('HIWEB', 'Iran (Islamic Republic of)', 'ADD'),
  '43213': ('HIWEB', 'Iran (Islamic Republic of)', 'ADD'),
  '43214': ('Kish Free Zone Organization', 'Iran (Islamic Republic of)', 'LIR'),
  '43219': ('Telecommunication Company of Iran (TCI) - Isfahan Celcom GSM', 'Iran (Islamic Republic of)', 'SUP'),
  '43220': ('RIGHTEL', 'Iran (Islamic Republic of)', 'ADD'),
  '43232': ('TCI (Telecommunication Company of Iran)', 'Iran (Islamic Republic of)', 'ADD'),
  '43235': ('IRANCELL', 'Iran (Islamic Republic of)', 'ADD'),
  '43244': ('ERTEBATAT MOBIN NET', 'Iran (Islamic Republic of)', 'ADD'),
  '43245': ('FARABORD DADEHAYE IRANIAN', 'Iran (Islamic Republic of)', 'ADD'),
  '43246': ('HIWEB', 'Iran (Islamic Republic of)', 'ADD'),
  '43249': ('GOSTARESH ERTEBATAT MABNA', 'Iran (Islamic Republic of)', 'ADD'),
  '43250': ('SHATEL', 'Iran (Islamic Republic of)', 'LIR'),
  '43251': ('PISHGAMAN TOSE-E ERTEBATAT', 'Iran (Islamic Republic of)', 'ADD'),
  '43252': ('ASIATECH', 'Iran (Islamic Republic of)', 'ADD'),
  '43270': ('TCI (Telecommunication Company of Iran)', 'Iran (Islamic Republic of)', 'ADD'),
  '43271': ('ERTEBATAT KOOHE NOOR', 'Iran (Islamic Republic of)', 'ADD'),
  '43293': ('ERTEBATAT FARZANEGAN PARS', 'Iran (Islamic Republic of)', 'ADD'),
  '44001': ('KDDI CORPORATION', 'Japan', 'LIR'),
  '44007': ('closip, Inc.', 'Japan', 'LIR'),
  '44008': ('Panasonic Systems Solutions Japan Co., Ltd', 'Japan', 'ADD'),
  '44009': ('Marubeni Wireless Communications Inc.', 'Japan', 'ADD'),
  '44011': ('Rakuten Mobile Network, Inc.', 'Japan', 'ADD'),
  '44012': ('CABLE MEDIA WAIWAI CORPORATION', 'Japan', 'ADD'),
  '44013': ('NTT Communications Corporation', 'Japan', 'ADD'),
  '44014': ('GRAPE ONE LTD.', 'Japan', 'ADD'),
  '44015': ('BB Backbone Corp.', 'Japan', 'ADD'),
  '44016': ('Nokia Innovations Japan G.K.', 'Japan', 'ADD'),
  '44017': ('OSAKA GAS BUSINESS CREATE CORPORATION', 'Japan', 'ADD'),
  '44018': ('Kintetsu Cable Network, Ltd', 'Japan', 'ADD'),
  '44019': ('NEC Networks & System Integration Corporation', 'Japan', 'ADD'),
  '44022': ('JTOWER Inc.', 'Japan', 'ADD'),
  '44023': ('FUJITSU LIMITED', 'Japan', 'ADD'),
  '44110': ('UQ Communications Inc.', 'Japan', 'SUP'),
  '441200': ('SORACOM, Inc.', 'Japan', 'ADD'),
  '441201': ('Aurens Co.,Ltd.', 'Japan', 'ADD'),
  '441202': ('Sony Wireless Communications Inc.', 'Japan', 'ADD'),
  '441203': ('GujoCity', 'Japan', 'ADD'),
  '441204': ('Wicom Inc.', 'Japan', 'ADD'),
  '441205': ('KATCH NETWORK INC.', 'Japan', 'ADD'),
  '441206': ('MITSUBISHI ELECTRIC CORPORATION', 'Japan', 'ADD'),
  '441207': ('Mitsui Knowledge Industry Co., Ltd.', 'Japan', 'ADD'),
  '441208': ('CHUDENKO CORPORATION', 'Japan', 'ADD'),
  '441209': ('Cable Television TOYAMA Inc.', 'Japan', 'ADD'),
  '441210': ('NIPPON TELEGRAPH AND TELEPHONE EAST CORPORATION', 'Japan', 'ADD'),
  '44191': ('The Tokyo Organising Committee of the Olympic and Paralympic Games', 'Japan', 'SUP'),
  '45203': ('S Telecom (CDMA)', 'Viet Nam', 'SUP'),
  '45205': ('Vietnamobile', 'Viet Nam', 'ADD'),
  '45206': ('EVN Telecom', 'Viet Nam', 'SUP'),
  '45207': ('Gmobile', 'Viet Nam', 'LIR'),
  '45208': ('I-Telecom', 'Viet Nam', 'ADD'),
  '45209': ('REDDI', 'Viet Nam', 'ADD'),
  '45409': ('CMMobile Global Communications Ltd', 'Hong Kong, China', 'SUP'),
  '45412': ('China Mobile Hong Kong Company Limited', 'Hong Kong, China', 'LIR'),
  '45413': ('China Mobile Hong Kong Company Limited', 'Hong Kong, China', 'LIR'),
  '45421': ('21 ViaNet Group Limited', 'Hong Kong, China', 'LIR'),
  '45423': ('Lycamobile Hong Kong Ltd', 'Hong Kong, China', 'SUP'),
  '45430': ('China Mobile Hong Kong Company Limited', 'Hong Kong, China', 'LIR'),
  '45435': ('Webbing Hong Kong Limited', 'Hong Kong, China', 'ADD'),
  '45436': ('Easco Telecommunications Limited', 'Hong Kong, China', 'ADD'),
  '45701': ('Lao Telecommunication Public Company', 'Lao P.D.R.', 'LIR'),
  '45702': ('ETL Company Limited', 'Lao P.D.R.', 'LIR'),
  '45703': ('Star Telecom Co., Ltd', 'Lao P.D.R.', 'ADD'),
  '45707': ('Best Telecom Co., Ltd', 'Lao P.D.R.', 'ADD'),
  '45708': ('TPLUS Digital Sole Company Limited', 'Lao P.D.R.', 'LIR'),
  '50512': ('Vodafone Hutchison Australia Pty Ltd', 'Australia', 'LIR'),
  '50518': ('Pactel International Pty Ltd', 'Australia', 'SUP'),
  '50546': ('ANGLOGOLD ASHANTI AUSTRALIA LTD', 'Australia', 'ADD'),
  '50547': ('Woodside Energy Limited', 'Australia', 'ADD'),
  '50548': ('Titan ICT Pty Ltd', 'Australia', 'ADD'),
  '50549': ('Field Solutions Group Pty Ltd', 'Australia', 'ADD'),
  '50551': ('Fortescue Metals Group Ltd', 'Australia', 'ADD'),
  '50552': ('Optitel Pty Ltd', 'Australia', 'ADD'),
  '50553': ('Shell Australia Pty Ltd', 'Australia', 'ADD'),
  '50554': ('Nokia Solutions and Networks Australia Pty Ltd', 'Australia', 'ADD'),
  '52801': ('Telekom Brunei Berhad (TelBru)', 'Brunei Darussalam', 'ADD'),
  '52802': ('Progresif Cellular Sdn Bhd (PCSB)', 'Brunei Darussalam', 'ADD'),
  '52803': ('Unified National Networks Sdn Bhd (UNN)', 'Brunei Darussalam', 'ADD'),
  '53007': ('Dense Air New Zealand Ltd', 'New Zealand', 'ADD'),
  '53704': ('Digitec Communication Limited', 'Papua New Guinea', 'ADD'),
  '55299': ('Palau Mobile Communications Inc. (PMCI)', 'Palau', 'ADD'),
  '63105': ('AFRICELL', 'Angola', 'ADD'),
  '63305': ('Intelvision Ltd', 'Seychelles', 'ADD'),
  '63407': ('Sudanese Telecommunication Co. LTD (SUDATEL)', 'Sudan', 'ADD'),
  '63513': ('AIRTEL RWANDA Ltd', 'Rwanda', 'ADD'),
  '63514': ('AIRTEL RWANDA Ltd', 'Rwanda', 'SUP'),
  '63901': ('Safaricom PLC', 'Kenya', 'LIR'),
  '63902': ('Safaricom PLC', 'Kenya', 'LIR'),
  '63908': ('Sema Mobile Services Limited', 'Kenya', 'SUP'),
  '63911': ('Jambo Telcoms Limited', 'Kenya', 'ADD'),
  '63912': ('Infura Limited', 'Kenya', 'ADD'),
  '64001': ('Shared Network Tanzania Limited', 'Tanzania', 'SUP'),
  '64006': ('WIA Company Limited', 'Tanzania', 'ADD'),
  '64008': ('Benson Informatics Limited (Smart)', 'Tanzania', 'SUP'),
  '64013': ('Wiafrica Tanzania Limited (Cootel)', 'Tanzania', 'SUP'),
  '64014': ('MO Mobile Holding Limited', 'Tanzania', 'SUP'),
  '64106': ('Afrimax Uganda Limited', 'Uganda', 'SUP'),
  '64118': ('Suretelecom Uganda Limited', 'Uganda', 'SUP'),
  '64120': ('Hamilton Telecom Limited', 'Uganda', 'SUP'),
  '64126': ('Lycamobile Network services Uganda Limited', 'Uganda', 'SUP'),
  '64501': ('Airtel Zambia Limited', 'Zambia', 'LIR'),
  '64502': ('MTN Zambia Limited', 'Zambia', 'LIR'),
  '64507': ('Liquid Telecom Zambia Limited', 'Zambia', 'ADD'),
  '64907': ('Capricorn Connect', 'Namibia', 'ADD'),
  '65503': ('Telkom SA SOC Ltd', 'South Africa', 'ADD'),
  '65504': ('Sasol (Pty) Ltd', 'South Africa', 'SUP'),
  '65511': ('SAPS Gauteng', 'South Africa', 'SUP'),
  '65517': ('Sishen Iron Ore Company (Ltd) Pty', 'South Africa', 'SUP'),
  '65521': ('Cape Town Metropolitan Council', 'South Africa', 'SUP'),
  '65541': ('South African Police Service', 'South Africa', 'SUP'),
  '65565': ('Vodacom Pty Ltd', 'South Africa', 'ADD'),
  '65575': ('Airport Company South Africa (ACSA)', 'South Africa', 'SUP'),
  '65576': ('Comsol Networks (Pty) Ltd', 'South Africa', 'ADD'),
  '65577': ('K2015315513 (Pty) Ltd t\\a One Telecom (Pty) Ltd', 'South Africa', 'ADD'),
  '71402': ('Grupo de Comunicaciones Digitales, S.A. (TIGO)', 'Panama', 'LIR'),
  '714020': ('Grupo de Comunicaciones Digitales, S.A. (TIGO)', 'Panama', 'LIR'),
  '71405': ('Cable & Wireless Panamá, S.A.', 'Panama', 'ADD'),
  '72406': ('Telefônica Brasil S.A.', 'Brazil', 'LIR'),
  '72410': ('Telefônica Brasil S.A.', 'Brazil', 'LIR'),
  '72411': ('Telefônica Brasil S.A.', 'Brazil', 'LIR'),
  '72417': ('SURF TELECOM S.A.', 'Brazil', 'ADD'),
  '72421': ('LIGUE', 'Brazil', 'ADD'),
  '72423': ('Telefônica Brasil S.A.', 'Brazil', 'LIR'),
  '72454': ('TIM S.A.', 'Brazil', 'LIR'),
  '73026': ('WILL S.A.', 'Chile', 'ADD'),
  '73027': ('Cibeles Telecom S.A.', 'Chile', 'ADD'),
  '73800': ('E-Networks Inc.', 'Guyana', 'ADD'),
  '74204': ('Free Caraïbe', 'French Guiana', 'ADD'),
  '74800': ('Ancel - TDMA', 'Uruguay', 'SUP'),
  '74801': ('Administración Nacional de Telecomunicaciones (ANTEL)', 'Uruguay', 'LIR'),
  '74803': ('Ancel', 'Uruguay', 'SUP'),
  '74807': ('Telefónica Móviles del Uruguay S.A. (Movistar)', 'Uruguay', 'LIR'),
  '74810': ('AM Wireless Uruguay S.A. (Claro)', 'Uruguay', 'LIR'),
  '90113': ('BebbiCell AG (Formerly Global Networks Switzerland AG', 'International Mobile, shared code', 'SUP'),
  '90119': ('Vodafone Malta (Monaco Telecom)', 'International Mobile, shared code', 'LIR'),
  '90129': ('Telenor Connexion AB', 'International Mobile, shared code', 'SUP'),
  '90133': ('Smart Communications, Inc', 'International Mobile, shared code', 'SUP'),
  '90141': ('One Network B.V.', 'International Mobile, shared code', 'LIR'),
  '90142': ('IMC Island Ehf (formerly DCN Hub ehf)', 'International Mobile, shared code', 'SUP'),
  '90147': ('Ooredoo', 'International Mobile, shared code', 'SUP'),
  '90149': ( 'Mobile Telecommunications Company K.S.C.P. (Formerly Zain Kuwait)',
             'International Mobile, shared code',
             'LIR'),
  '90151': ('VisionNG', 'International Mobile, shared code', 'SUP'),
  '90153': ('Inmarsat Ltd. (replacing Deutsche Telekom AG)', 'International Mobile, shared code', 'LIR'),
  '90157': ('SAP', 'International Mobile, shared code', 'SUP'),
  '90163': ('GloTell B.V.', 'International Mobile, shared code', 'SUP'),
  '90165': ('Plintron Global Technology Solutions Private Limited', 'International Mobile, shared code', 'SUP'),
  '90166': ('Limitless Mobile, LLC', 'International Mobile, shared code', 'ADD'),
  '90167': ('1NCE GmbH', 'International Mobile, shared code', 'ADD'),
  '90168': ('Maersk Line A/S', 'International Mobile, shared code', 'ADD'),
  '90169': ('Legos', 'International Mobile, shared code', 'ADD'),
  '90170': ('Clementvale Baltic OÜ', 'International Mobile, shared code', 'SUP'),
  '90171': ('Tampnet AS', 'International Mobile, shared code', 'ADD'),
  '90172': ('Tele2 Sverige Aktiebolag (Formerly Tele2 IoT)', 'International Mobile, shared code', 'LIR'),
  '90173': ('Cubic Telecom Limited', 'International Mobile, shared code', 'ADD'),
  '90174': ('Etisalat', 'International Mobile, shared code', 'ADD'),
  '90175': ('Podsystem Ltd.', 'International Mobile, shared code', 'ADD'),
  '90176': ('A1 Telekom Austria AG', 'International Mobile, shared code', 'ADD'),
  '90177': ('Bouygues Telecom', 'International Mobile, shared code', 'ADD'),
  '90178': ('Telecom Italia Sparkle S.p.A.', 'International Mobile, shared code', 'ADD'),
  '90179': ('Nokia Corporation', 'International Mobile, shared code', 'ADD'),
  '90180': ('Flo Live Limited', 'International Mobile, shared code', 'SUP'),
  '90181': ('Airnity SAS', 'International Mobile, shared code', 'ADD'),
  '90182': ('Eseye Limited', 'International Mobile, shared code', 'ADD'),
  '90183': ('iBasis Netherlands BV', 'International Mobile, shared code', 'ADD'),
  '90184': ('TELEFONICA MOVILES ESPAÑA, S.A. UNIPERSONAL (TME)', 'International Mobile, shared code', 'ADD'),
  '90185': ('Telefónica Germany GmbH & Co. OHG', 'International Mobile, shared code', 'ADD'),
  '90186': ('BJT PARTNERS SAS', 'International Mobile, shared code', 'ADD'),
  '90187': ('Cisco Systems, Inc.', 'International Mobile, shared code', 'ADD'),
  '90188': ( 'UN Office for the Coordination of Humanitarian Affairs (OCHA)',
             'International              Mobile, shared code',
             'SUP'),
  '90189': ('DIDWW Ireland Limited', 'International Mobile, shared code', 'ADD'),
  '90190': ('Truphone Limited', 'International Mobile, shared code', 'ADD'),
  '90191': ('World Mobile Group Limited', 'International Mobile, shared code', 'ADD'),
  '90192': ('Phonegroup SA', 'International Mobile, shared code', 'ADD'),
  '90193': ('SkyFive AG', 'International Mobile, shared code', 'ADD'),
  '90194': ('Intelsat US LLC', 'International Mobile, shared code', 'ADD'),
  '90195': ('HMD Global Oy', 'International Mobile, shared code', 'ADD'),
  '90196': ('KORE Wireless', 'International Mobile, shared code', 'ADD'),
  '99101': ( "World's Global Telecom (end of temporary assignment for trial on 15.I.2021)",
             'Trial of a proposed new international telecommunication service, shared code',
             'SUP'),
  '99102': ( 'Orange (end of temporary assignment for trial on 7.VIII.2022)',
             'Trial of a proposed new international telecommunication service, shared code',
             'SUP'),
  '99103': ( 'Halys SAS (temporary assignment for trial until 5.IV.2022)',
             'Trial of a proposed new international telecommunication service, shared code',
             'ADD')}
