# -*- coding: UTF-8 -*-
# source: https://en.wikipedia.org/wiki/List_of_country_calling_codes
# license: https://en.wikipedia.org/wiki/Wikipedia:Text_of_Creative_Commons_Attribution-ShareAlike_3.0_Unported_License

WIKIP_MSISDN = \
{ '1': [ ( 'CA',
           'Canada',
           'https://en.wikipedia.org/wiki/Canada',
           'https://en.wikipedia.org/wiki/List_of_NANP_area_codes'),
         ( 'US',
           'United States',
           'https://en.wikipedia.org/wiki/United_States',
           'https://en.wikipedia.org/wiki/List_of_NANP_area_codes')],
  '1242': [ ( 'BS',
              'The Bahamas',
              'https://en.wikipedia.org/wiki/The_Bahamas',
              'https://en.wikipedia.org/wiki/Area_code_242')],
  '1246': [('BB', 'Barbados', 'https://en.wikipedia.org/wiki/Barbados', 'https://en.wikipedia.org/wiki/Area_code_246')],
  '1264': [('AI', 'Anguilla', 'https://en.wikipedia.org/wiki/Anguilla', 'https://en.wikipedia.org/wiki/Area_code_264')],
  '1268': [ ( 'AG',
              'Antigua and Barbuda',
              'https://en.wikipedia.org/wiki/Antigua_and_Barbuda',
              'https://en.wikipedia.org/wiki/Area_code_268')],
  '1284': [ ( 'VG',
              'British Virgin Islands',
              'https://en.wikipedia.org/wiki/British_Virgin_Islands',
              'https://en.wikipedia.org/wiki/Area_code_284')],
  '1340': [ ( 'VI',
              'United States Virgin Islands',
              'https://en.wikipedia.org/wiki/United_States_Virgin_Islands',
              'https://en.wikipedia.org/wiki/Area_code_340')],
  '1345': [ ( 'KY',
              'Cayman Islands',
              'https://en.wikipedia.org/wiki/Cayman_Islands',
              'https://en.wikipedia.org/wiki/Area_code_345')],
  '1441': [('BM', 'Bermuda', 'https://en.wikipedia.org/wiki/Bermuda', 'https://en.wikipedia.org/wiki/Area_code_441')],
  '1473': [('GD', 'Grenada', 'https://en.wikipedia.org/wiki/Grenada', 'https://en.wikipedia.org/wiki/Area_code_473')],
  '1649': [ ( 'TC',
              'Turks and Caicos Islands',
              'https://en.wikipedia.org/wiki/Turks_and_Caicos_Islands',
              'https://en.wikipedia.org/wiki/Area_code_649')],
  '1658': [('JM', 'Jamaica', 'https://en.wikipedia.org/wiki/Jamaica', 'https://en.wikipedia.org/wiki/Area_code_658')],
  '1664': [ ( 'MS',
              'Montserrat',
              'https://en.wikipedia.org/wiki/Montserrat',
              'https://en.wikipedia.org/wiki/Area_code_664')],
  '1670': [ ( 'MP',
              'Northern Mariana Islands',
              'https://en.wikipedia.org/wiki/Northern_Mariana_Islands',
              'https://en.wikipedia.org/wiki/Area_code_670')],
  '1671': [('GU', 'Guam', 'https://en.wikipedia.org/wiki/Guam', 'https://en.wikipedia.org/wiki/Area_code_671')],
  '1684': [ ( 'AS',
              'American Samoa',
              'https://en.wikipedia.org/wiki/American_Samoa',
              'https://en.wikipedia.org/wiki/Area_code_684')],
  '1721': [ ( 'SX',
              'Sint Maarten',
              'https://en.wikipedia.org/wiki/Sint_Maarten',
              'https://en.wikipedia.org/wiki/Area_code_721')],
  '1758': [ ( 'LC',
              'St. Lucia',
              'https://en.wikipedia.org/wiki/St._Lucia',
              'https://en.wikipedia.org/wiki/Area_code_758')],
  '1767': [('DM', 'Dominica', 'https://en.wikipedia.org/wiki/Dominica', 'https://en.wikipedia.org/wiki/Area_code_767')],
  '1784': [ ( 'VC',
              'St. Vincent and the Grenadines',
              'https://en.wikipedia.org/wiki/St._Vincent_and_the_Grenadines',
              'https://en.wikipedia.org/wiki/Area_code_784')],
  '1787': [ ( 'PR',
              'Puerto Rico',
              'https://en.wikipedia.org/wiki/Puerto_Rico',
              'https://en.wikipedia.org/wiki/Telephone_numbers_in_Puerto_Rico')],
  '1809': [ ( 'DO',
              'Dominican Republic',
              'https://en.wikipedia.org/wiki/Dominican_Republic',
              'https://en.wikipedia.org/wiki/Telephone_numbers_in_the_Dominican_Republic')],
  '1829': [ ( 'DO',
              'Dominican Republic',
              'https://en.wikipedia.org/wiki/Dominican_Republic',
              'https://en.wikipedia.org/wiki/Telephone_numbers_in_the_Dominican_Republic')],
  '1849': [ ( 'DO',
              'Dominican Republic',
              'https://en.wikipedia.org/wiki/Dominican_Republic',
              'https://en.wikipedia.org/wiki/Telephone_numbers_in_the_Dominican_Republic')],
  '1868': [ ( 'TT',
              'Trinidad and Tobago',
              'https://en.wikipedia.org/wiki/Trinidad_and_Tobago',
              'https://en.wikipedia.org/wiki/Area_code_868')],
  '1869': [ ( 'KN',
              'St. Kitts and Nevis',
              'https://en.wikipedia.org/wiki/St._Kitts_and_Nevis',
              'https://en.wikipedia.org/wiki/Area_code_869')],
  '1876': [('JM', 'Jamaica', 'https://en.wikipedia.org/wiki/Jamaica', 'https://en.wikipedia.org/wiki/Area_code_876')],
  '1939': [ ( 'PR',
              'Puerto Rico',
              'https://en.wikipedia.org/wiki/Puerto_Rico',
              'https://en.wikipedia.org/wiki/Telephone_numbers_in_Puerto_Rico')],
  '20': [('EG', 'Egypt', 'https://en.wikipedia.org/wiki/Egypt', 'https://en.wikipedia.org/wiki/%2B20')],
  '211': [('SS', 'South Sudan', 'https://en.wikipedia.org/wiki/South_Sudan', 'https://en.wikipedia.org/wiki/%2B211')],
  '212': [ ( 'EH',
             'Western Sahara',
             'https://en.wikipedia.org/wiki/Western_Sahara',
             'https://en.wikipedia.org/wiki/%2B212'),
           ('MA', 'Morocco', 'https://en.wikipedia.org/wiki/Morocco', 'https://en.wikipedia.org/wiki/%2B212')],
  '213': [('DZ', 'Algeria', 'https://en.wikipedia.org/wiki/Algeria', 'https://en.wikipedia.org/wiki/%2B213')],
  '216': [('TN', 'Tunisia', 'https://en.wikipedia.org/wiki/Tunisia', 'https://en.wikipedia.org/wiki/%2B216')],
  '218': [('LY', 'Libya', 'https://en.wikipedia.org/wiki/Libya', 'https://en.wikipedia.org/wiki/%2B218')],
  '220': [ ( 'GM',
             'The Gambia',
             'https://en.wikipedia.org/wiki/The_Gambia',
             'https://en.wikipedia.org/wiki/Telephone_numbers_in_the_Gambia')],
  '221': [ ( 'SN',
             'Senegal',
             'https://en.wikipedia.org/wiki/Senegal',
             'https://en.wikipedia.org/wiki/Telephone_numbers_in_Senegal')],
  '222': [ ( 'MR',
             'Mauritania',
             'https://en.wikipedia.org/wiki/Mauritania',
             'https://en.wikipedia.org/wiki/Telephone_numbers_in_Mauritania')],
  '223': [ ( 'ML',
             'Mali',
             'https://en.wikipedia.org/wiki/Mali',
             'https://en.wikipedia.org/wiki/Telephone_numbers_in_Mali')],
  '224': [ ( 'GN',
             'Guinea',
             'https://en.wikipedia.org/wiki/Guinea',
             'https://en.wikipedia.org/wiki/Telephone_numbers_in_Guinea')],
  '225': [ ( 'CI',
             'Ivory Coast',
             'https://en.wikipedia.org/wiki/Ivory_Coast',
             'https://en.wikipedia.org/wiki/Telephone_numbers_in_Ivory_Coast')],
  '226': [ ( 'BF',
             'Burkina Faso',
             'https://en.wikipedia.org/wiki/Burkina_Faso',
             'https://en.wikipedia.org/wiki/Telephone_numbers_in_Burkina_Faso')],
  '227': [ ( 'NE',
             'Niger',
             'https://en.wikipedia.org/wiki/Niger',
             'https://en.wikipedia.org/wiki/Telephone_numbers_in_Niger')],
  '228': [ ( 'TG',
             'Togo',
             'https://en.wikipedia.org/wiki/Togo',
             'https://en.wikipedia.org/wiki/Telephone_numbers_in_Togo')],
  '229': [ ( 'BJ',
             'Benin',
             'https://en.wikipedia.org/wiki/Benin',
             'https://en.wikipedia.org/wiki/Telephone_numbers_in_Benin')],
  '230': [ ( 'MU',
             'Mauritius',
             'https://en.wikipedia.org/wiki/Mauritius',
             'https://en.wikipedia.org/wiki/Telephone_numbers_in_Mauritius')],
  '231': [ ( 'LR',
             'Liberia',
             'https://en.wikipedia.org/wiki/Liberia',
             'https://en.wikipedia.org/wiki/Telephone_numbers_in_Liberia')],
  '232': [ ( 'SL',
             'Sierra Leone',
             'https://en.wikipedia.org/wiki/Sierra_Leone',
             'https://en.wikipedia.org/wiki/Telephone_numbers_in_Sierra_Leone')],
  '233': [ ( 'GH',
             'Ghana',
             'https://en.wikipedia.org/wiki/Ghana',
             'https://en.wikipedia.org/wiki/Telephone_numbers_in_Ghana')],
  '234': [ ( 'NG',
             'Nigeria',
             'https://en.wikipedia.org/wiki/Nigeria',
             'https://en.wikipedia.org/wiki/Telephone_numbers_in_Nigeria')],
  '235': [ ( 'TD',
             'Chad',
             'https://en.wikipedia.org/wiki/Chad',
             'https://en.wikipedia.org/wiki/Telephone_numbers_in_Chad')],
  '236': [ ( 'CF',
             'Central African Republic',
             'https://en.wikipedia.org/wiki/Central_African_Republic',
             'https://en.wikipedia.org/wiki/%2B236')],
  '237': [ ( 'CM',
             'Cameroon',
             'https://en.wikipedia.org/wiki/Cameroon',
             'https://en.wikipedia.org/wiki/Telephone_numbers_in_Cameroon')],
  '238': [ ( 'CV',
             'Cape Verde',
             'https://en.wikipedia.org/wiki/Cape_Verde',
             'https://en.wikipedia.org/wiki/Telephone_numbers_in_Cape_Verde')],
  '239': [ ( 'ST',
             'São Tomé and Príncipe',
             'https://en.wikipedia.org/wiki/S%C3%A3o_Tom%C3%A9_and_Pr%C3%ADncipe',
             'https://en.wikipedia.org/wiki/%2B239')],
  '240': [ ( 'GQ',
             'Equatorial Guinea',
             'https://en.wikipedia.org/wiki/Equatorial_Guinea',
             'https://en.wikipedia.org/wiki/Telephone_numbers_in_Equatorial_Guinea')],
  '241': [ ( 'GA',
             'Gabon',
             'https://en.wikipedia.org/wiki/Gabon',
             'https://en.wikipedia.org/wiki/Telephone_numbers_in_Gabon')],
  '242': [ ( 'CG',
             'Republic of Congo',
             'https://en.wikipedia.org/wiki/Republic_of_Congo',
             'https://en.wikipedia.org/wiki/%2B242')],
  '243': [ ( 'CD',
             'Democratic Republic of the Congo',
             'https://en.wikipedia.org/wiki/Democratic_Republic_of_the_Congo',
             'https://en.wikipedia.org/wiki/%2B243')],
  '244': [ ( 'AO',
             'Angola',
             'https://en.wikipedia.org/wiki/Angola',
             'https://en.wikipedia.org/wiki/Telephone_numbers_in_Angola')],
  '245': [ ( 'GW',
             'Guinea-Bissau',
             'https://en.wikipedia.org/wiki/Guinea-Bissau',
             'https://en.wikipedia.org/wiki/Telephone_numbers_in_Guinea-Bissau')],
  '246': [ ( 'IO',
             'British Indian Ocean Territory',
             'https://en.wikipedia.org/wiki/British_Indian_Ocean_Territory',
             'https://en.wikipedia.org/wiki/%2B246')],
  '247': [ ( 'AC',
             'Ascension Island',
             'https://en.wikipedia.org/wiki/Ascension_Island',
             'https://en.wikipedia.org/wiki/Telephone_numbers_in_Ascension_Island')],
  '248': [ ( 'SC',
             'Seychelles',
             'https://en.wikipedia.org/wiki/Seychelles',
             'https://en.wikipedia.org/wiki/Telephone_numbers_in_Seychelles')],
  '249': [ ( 'SD',
             'Sudan',
             'https://en.wikipedia.org/wiki/Sudan',
             'https://en.wikipedia.org/wiki/Telephone_numbers_in_Sudan')],
  '250': [('RW', 'Rwanda', 'https://en.wikipedia.org/wiki/Rwanda', 'https://en.wikipedia.org/wiki/%2B250')],
  '251': [('ET', 'Ethiopia', 'https://en.wikipedia.org/wiki/Ethiopia', 'https://en.wikipedia.org/wiki/%2B251')],
  '252': [ ( 'SO',
             'Somalia',
             'https://en.wikipedia.org/wiki/Somalia',
             'https://en.wikipedia.org/wiki/Telephone_numbers_in_Somalia')],
  '253': [ ( 'DJ',
             'Djibouti',
             'https://en.wikipedia.org/wiki/Djibouti',
             'https://en.wikipedia.org/wiki/Telephone_numbers_in_Djibouti')],
  '254': [ ( 'KE',
             'Kenya',
             'https://en.wikipedia.org/wiki/Kenya',
             'https://en.wikipedia.org/wiki/Telephone_numbers_in_Kenya')],
  '255': [('TZ', 'Tanzania', 'https://en.wikipedia.org/wiki/Tanzania', 'https://en.wikipedia.org/wiki/%2B255')],
  '256': [('UG', 'Uganda', 'https://en.wikipedia.org/wiki/Uganda', 'https://en.wikipedia.org/wiki/%2B256')],
  '257': [('BI', 'Burundi', 'https://en.wikipedia.org/wiki/Burundi', 'https://en.wikipedia.org/wiki/%2B257')],
  '258': [('MZ', 'Mozambique', 'https://en.wikipedia.org/wiki/Mozambique', 'https://en.wikipedia.org/wiki/%2B258')],
  '260': [('ZM', 'Zambia', 'https://en.wikipedia.org/wiki/Zambia', 'https://en.wikipedia.org/wiki/%2B260')],
  '261': [('MG', 'Madagascar', 'https://en.wikipedia.org/wiki/Madagascar', 'https://en.wikipedia.org/wiki/%2B261')],
  '262': [ ('RE', 'Réunion', 'https://en.wikipedia.org/wiki/R%C3%A9union', 'https://en.wikipedia.org/wiki/%2B262'),
           ( 'TF',
             'French Southern and Antarctic Lands',
             'https://en.wikipedia.org/wiki/French_Southern_and_Antarctic_Lands',
             'https://en.wikipedia.org/wiki/%2B262'),
           ('YT', 'Mayotte', 'https://en.wikipedia.org/wiki/Mayotte', 'https://en.wikipedia.org/wiki/%2B262')],
  '263': [('ZW', 'Zimbabwe', 'https://en.wikipedia.org/wiki/Zimbabwe', 'https://en.wikipedia.org/wiki/%2B263')],
  '264': [('NA', 'Namibia', 'https://en.wikipedia.org/wiki/Namibia', 'https://en.wikipedia.org/wiki/%2B264')],
  '265': [('MW', 'Malawi', 'https://en.wikipedia.org/wiki/Malawi', 'https://en.wikipedia.org/wiki/%2B265')],
  '266': [('LS', 'Lesotho', 'https://en.wikipedia.org/wiki/Lesotho', 'https://en.wikipedia.org/wiki/%2B266')],
  '267': [('BW', 'Botswana', 'https://en.wikipedia.org/wiki/Botswana', 'https://en.wikipedia.org/wiki/%2B267')],
  '268': [('SZ', 'Eswatini', 'https://en.wikipedia.org/wiki/Eswatini', 'https://en.wikipedia.org/wiki/%2B268')],
  '269': [('KM', 'Comoros', 'https://en.wikipedia.org/wiki/Comoros', 'https://en.wikipedia.org/wiki/%2B269')],
  '27': [('ZA', 'South Africa', 'https://en.wikipedia.org/wiki/South_Africa', 'https://en.wikipedia.org/wiki/%2B27')],
  '290': [ ('SH', 'Saint Helena', 'https://en.wikipedia.org/wiki/Saint_Helena', 'https://en.wikipedia.org/wiki/%2B290'),
           ( 'TA',
             'Tristan da Cunha',
             'https://en.wikipedia.org/wiki/Tristan_da_Cunha',
             'https://en.wikipedia.org/wiki/%2B290')],
  '291': [('ER', 'Eritrea', 'https://en.wikipedia.org/wiki/Eritrea', 'https://en.wikipedia.org/wiki/%2B291')],
  '297': [('AW', 'Aruba', 'https://en.wikipedia.org/wiki/Aruba', 'https://en.wikipedia.org/wiki/%2B297')],
  '298': [ ( 'FO',
             'Faroe Islands',
             'https://en.wikipedia.org/wiki/Faroe_Islands',
             'https://en.wikipedia.org/wiki/%2B298')],
  '299': [('GL', 'Greenland', 'https://en.wikipedia.org/wiki/Greenland', 'https://en.wikipedia.org/wiki/%2B299')],
  '30': [('GR', 'Greece', 'https://en.wikipedia.org/wiki/Greece', 'https://en.wikipedia.org/wiki/%2B30')],
  '31': [('NL', 'Netherlands', 'https://en.wikipedia.org/wiki/Netherlands', 'https://en.wikipedia.org/wiki/%2B31')],
  '32': [('BE', 'Belgium', 'https://en.wikipedia.org/wiki/Belgium', 'https://en.wikipedia.org/wiki/%2B32')],
  '33': [('FR', 'France', 'https://en.wikipedia.org/wiki/France', 'https://en.wikipedia.org/wiki/%2B33')],
  '34': [('ES', 'Spain', 'https://en.wikipedia.org/wiki/Spain', 'https://en.wikipedia.org/wiki/%2B34')],
  '350': [('GI', 'Gibraltar', 'https://en.wikipedia.org/wiki/Gibraltar', 'https://en.wikipedia.org/wiki/%2B350')],
  '351': [('PT', 'Portugal', 'https://en.wikipedia.org/wiki/Portugal', 'https://en.wikipedia.org/wiki/%2B351')],
  '352': [('LU', 'Luxembourg', 'https://en.wikipedia.org/wiki/Luxembourg', 'https://en.wikipedia.org/wiki/%2B352')],
  '353': [ ( 'IE',
             'Republic of Ireland',
             'https://en.wikipedia.org/wiki/Republic_of_Ireland',
             'https://en.wikipedia.org/wiki/%2B353')],
  '354': [('IS', 'Iceland', 'https://en.wikipedia.org/wiki/Iceland', 'https://en.wikipedia.org/wiki/%2B354')],
  '355': [('AL', 'Albania', 'https://en.wikipedia.org/wiki/Albania', 'https://en.wikipedia.org/wiki/%2B355')],
  '356': [('MT', 'Malta', 'https://en.wikipedia.org/wiki/Malta', 'https://en.wikipedia.org/wiki/%2B356')],
  '357': [('CY', 'Cyprus', 'https://en.wikipedia.org/wiki/Cyprus', 'https://en.wikipedia.org/wiki/%2B357')],
  '358': [ ('AX', 'Åland', 'https://en.wikipedia.org/wiki/%C3%85land', 'https://en.wikipedia.org/wiki/%2B358'),
           ('FI', 'Finland', 'https://en.wikipedia.org/wiki/Finland', 'https://en.wikipedia.org/wiki/%2B358')],
  '359': [('BG', 'Bulgaria', 'https://en.wikipedia.org/wiki/Bulgaria', 'https://en.wikipedia.org/wiki/%2B359')],
  '36': [('HU', 'Hungary', 'https://en.wikipedia.org/wiki/Hungary', 'https://en.wikipedia.org/wiki/%2B36')],
  '370': [('LT', 'Lithuania', 'https://en.wikipedia.org/wiki/Lithuania', 'https://en.wikipedia.org/wiki/%2B370')],
  '371': [('LV', 'Latvia', 'https://en.wikipedia.org/wiki/Latvia', 'https://en.wikipedia.org/wiki/%2B371')],
  '372': [('EE', 'Estonia', 'https://en.wikipedia.org/wiki/Estonia', 'https://en.wikipedia.org/wiki/%2B372')],
  '373': [('MD', 'Moldova', 'https://en.wikipedia.org/wiki/Moldova', 'https://en.wikipedia.org/wiki/%2B373')],
  '374': [('AM', 'Armenia', 'https://en.wikipedia.org/wiki/Armenia', 'https://en.wikipedia.org/wiki/%2B374')],
  '375': [('BY', 'Belarus', 'https://en.wikipedia.org/wiki/Belarus', 'https://en.wikipedia.org/wiki/%2B375')],
  '376': [('AD', 'Andorra', 'https://en.wikipedia.org/wiki/Andorra', 'https://en.wikipedia.org/wiki/%2B376')],
  '377': [('MC', 'Monaco', 'https://en.wikipedia.org/wiki/Monaco', 'https://en.wikipedia.org/wiki/%2B377')],
  '378': [('SM', 'San Marino', 'https://en.wikipedia.org/wiki/San_Marino', 'https://en.wikipedia.org/wiki/%2B378')],
  '379': [('VA', 'Vatican City', 'https://en.wikipedia.org/wiki/Vatican_City', 'https://en.wikipedia.org/wiki/%2B379')],
  '380': [('UA', 'Ukraine', 'https://en.wikipedia.org/wiki/Ukraine', 'https://en.wikipedia.org/wiki/%2B380')],
  '381': [('RS', 'Serbia', 'https://en.wikipedia.org/wiki/Serbia', 'https://en.wikipedia.org/wiki/%2B381')],
  '382': [('ME', 'Montenegro', 'https://en.wikipedia.org/wiki/Montenegro', 'https://en.wikipedia.org/wiki/%2B382')],
  '383': [('XK', 'Kosovo', 'https://en.wikipedia.org/wiki/Kosovo', 'https://en.wikipedia.org/wiki/%2B383')],
  '385': [('HR', 'Croatia', 'https://en.wikipedia.org/wiki/Croatia', 'https://en.wikipedia.org/wiki/%2B385')],
  '386': [('SI', 'Slovenia', 'https://en.wikipedia.org/wiki/Slovenia', 'https://en.wikipedia.org/wiki/%2B386')],
  '387': [ ( 'BA',
             'Bosnia and Herzegovina',
             'https://en.wikipedia.org/wiki/Bosnia_and_Herzegovina',
             'https://en.wikipedia.org/wiki/%2B387')],
  '389': [ ( 'MK',
             'North Macedonia',
             'https://en.wikipedia.org/wiki/North_Macedonia',
             'https://en.wikipedia.org/wiki/%2B389')],
  '39': [ ('IT', 'Italy', 'https://en.wikipedia.org/wiki/Italy', 'https://en.wikipedia.org/wiki/%2B39'),
          ('VA', 'Vatican City', 'https://en.wikipedia.org/wiki/Vatican_City', 'https://en.wikipedia.org/wiki/%2B39')],
  '40': [('RO', 'Romania', 'https://en.wikipedia.org/wiki/Romania', 'https://en.wikipedia.org/wiki/%2B40')],
  '41': [('CH', 'Switzerland', 'https://en.wikipedia.org/wiki/Switzerland', 'https://en.wikipedia.org/wiki/%2B41')],
  '420': [ ( 'CZ',
             'Czech Republic',
             'https://en.wikipedia.org/wiki/Czech_Republic',
             'https://en.wikipedia.org/wiki/%2B420')],
  '421': [('SK', 'Slovakia', 'https://en.wikipedia.org/wiki/Slovakia', 'https://en.wikipedia.org/wiki/%2B421')],
  '423': [ ( 'LI',
             'Liechtenstein',
             'https://en.wikipedia.org/wiki/Liechtenstein',
             'https://en.wikipedia.org/wiki/%2B423')],
  '43': [('AT', 'Austria', 'https://en.wikipedia.org/wiki/Austria', 'https://en.wikipedia.org/wiki/%2B43')],
  '44': [ ( 'GB',
            'United Kingdom',
            'https://en.wikipedia.org/wiki/United_Kingdom',
            'https://en.wikipedia.org/wiki/Telephone_numbers_in_the_United_Kingdom'),
          ( 'GG',
            'Guernsey',
            'https://en.wikipedia.org/wiki/Guernsey',
            'https://en.wikipedia.org/wiki/Telephone_numbers_in_the_United_Kingdom'),
          ( 'IM',
            'Isle of Man',
            'https://en.wikipedia.org/wiki/Isle_of_Man',
            'https://en.wikipedia.org/wiki/Telephone_numbers_in_the_United_Kingdom'),
          ( 'JE',
            'Jersey',
            'https://en.wikipedia.org/wiki/Jersey',
            'https://en.wikipedia.org/wiki/Telephone_numbers_in_the_United_Kingdom')],
  '45': [('DK', 'Denmark', 'https://en.wikipedia.org/wiki/Denmark', 'https://en.wikipedia.org/wiki/%2B45')],
  '46': [('SE', 'Sweden', 'https://en.wikipedia.org/wiki/Sweden', 'https://en.wikipedia.org/wiki/%2B46')],
  '47': [ ('BV', 'Bouvet Island', 'https://en.wikipedia.org/wiki/Bouvet_Island', 'https://en.wikipedia.org/wiki/%2B47'),
          ('NO', 'Norway', 'https://en.wikipedia.org/wiki/Norway', 'https://en.wikipedia.org/wiki/%2B47'),
          ( 'SJ',
            'Svalbard and Jan Mayen',
            'https://en.wikipedia.org/wiki/Svalbard_and_Jan_Mayen',
            'https://en.wikipedia.org/wiki/%2B47')],
  '48': [('PL', 'Poland', 'https://en.wikipedia.org/wiki/Poland', 'https://en.wikipedia.org/wiki/%2B48')],
  '49': [('DE', 'Germany', 'https://en.wikipedia.org/wiki/Germany', 'https://en.wikipedia.org/wiki/%2B49')],
  '500': [ ( 'FK',
             'Falkland Islands',
             'https://en.wikipedia.org/wiki/Falkland_Islands',
             'https://en.wikipedia.org/wiki/%2B500'),
           ( 'GS',
             'South Georgia and the South Sandwich Islands',
             'https://en.wikipedia.org/wiki/South_Georgia_and_the_South_Sandwich_Islands',
             'https://en.wikipedia.org/wiki/%2B500')],
  '501': [('BZ', 'Belize', 'https://en.wikipedia.org/wiki/Belize', 'https://en.wikipedia.org/wiki/%2B501')],
  '502': [('GT', 'Guatemala', 'https://en.wikipedia.org/wiki/Guatemala', 'https://en.wikipedia.org/wiki/%2B502')],
  '503': [('SV', 'El Salvador', 'https://en.wikipedia.org/wiki/El_Salvador', 'https://en.wikipedia.org/wiki/%2B503')],
  '504': [('HN', 'Honduras', 'https://en.wikipedia.org/wiki/Honduras', 'https://en.wikipedia.org/wiki/%2B504')],
  '505': [('NI', 'Nicaragua', 'https://en.wikipedia.org/wiki/Nicaragua', 'https://en.wikipedia.org/wiki/%2B505')],
  '506': [('CR', 'Costa Rica', 'https://en.wikipedia.org/wiki/Costa_Rica', 'https://en.wikipedia.org/wiki/%2B506')],
  '507': [('PA', 'Panama', 'https://en.wikipedia.org/wiki/Panama', 'https://en.wikipedia.org/wiki/%2B507')],
  '508': [ ( 'PM',
             'St. Pierre and Miquelon',
             'https://en.wikipedia.org/wiki/St._Pierre_and_Miquelon',
             'https://en.wikipedia.org/wiki/%2B508')],
  '509': [('HT', 'Haiti', 'https://en.wikipedia.org/wiki/Haiti', 'https://en.wikipedia.org/wiki/%2B509')],
  '51': [('PE', 'Peru', 'https://en.wikipedia.org/wiki/Peru', 'https://en.wikipedia.org/wiki/%2B51')],
  '52': [('MX', 'Mexico', 'https://en.wikipedia.org/wiki/Mexico', 'https://en.wikipedia.org/wiki/%2B52')],
  '53': [('CU', 'Cuba', 'https://en.wikipedia.org/wiki/Cuba', 'https://en.wikipedia.org/wiki/%2B53')],
  '54': [('AR', 'Argentina', 'https://en.wikipedia.org/wiki/Argentina', 'https://en.wikipedia.org/wiki/%2B54')],
  '55': [('BR', 'Brazil', 'https://en.wikipedia.org/wiki/Brazil', 'https://en.wikipedia.org/wiki/%2B55')],
  '56': [('CL', 'Chile', 'https://en.wikipedia.org/wiki/Chile', 'https://en.wikipedia.org/wiki/%2B56')],
  '57': [('CO', 'Colombia', 'https://en.wikipedia.org/wiki/Colombia', 'https://en.wikipedia.org/wiki/%2B57')],
  '58': [('VE', 'Venezuela', 'https://en.wikipedia.org/wiki/Venezuela', 'https://en.wikipedia.org/wiki/%2B58')],
  '590': [ ( 'BL',
             'Saint Barthélemy',
             'https://en.wikipedia.org/wiki/Saint_Barth%C3%A9lemy',
             'https://en.wikipedia.org/wiki/%2B590'),
           ('GP', 'Guadeloupe', 'https://en.wikipedia.org/wiki/Guadeloupe', 'https://en.wikipedia.org/wiki/%2B590'),
           ( 'MF',
             'Collectivity of Saint Martin',
             'https://en.wikipedia.org/wiki/Collectivity_of_Saint_Martin',
             'https://en.wikipedia.org/wiki/%2B590')],
  '591': [('BO', 'Bolivia', 'https://en.wikipedia.org/wiki/Bolivia', 'https://en.wikipedia.org/wiki/%2B591')],
  '592': [('GY', 'Guyana', 'https://en.wikipedia.org/wiki/Guyana', 'https://en.wikipedia.org/wiki/%2B592')],
  '593': [('EC', 'Ecuador', 'https://en.wikipedia.org/wiki/Ecuador', 'https://en.wikipedia.org/wiki/%2B593')],
  '594': [ ( 'GF',
             'French Guiana',
             'https://en.wikipedia.org/wiki/French_Guiana',
             'https://en.wikipedia.org/wiki/%2B594')],
  '595': [('PY', 'Paraguay', 'https://en.wikipedia.org/wiki/Paraguay', 'https://en.wikipedia.org/wiki/%2B595')],
  '596': [('MQ', 'Martinique', 'https://en.wikipedia.org/wiki/Martinique', 'https://en.wikipedia.org/wiki/%2B596')],
  '597': [('SR', 'Suriname', 'https://en.wikipedia.org/wiki/Suriname', 'https://en.wikipedia.org/wiki/%2B597')],
  '598': [('UY', 'Uruguay', 'https://en.wikipedia.org/wiki/Uruguay', 'https://en.wikipedia.org/wiki/%2B598')],
  '599': [ ( 'BQ',
             'Caribbean Netherlands',
             'https://en.wikipedia.org/wiki/Caribbean_Netherlands',
             'https://en.wikipedia.org/wiki/Telephone_numbers_in_Cura%C3%A7ao_and_the_Caribbean_Netherlands'),
           ( 'CW',
             'Curaçao',
             'https://en.wikipedia.org/wiki/Cura%C3%A7ao',
             'https://en.wikipedia.org/wiki/Telephone_numbers_in_Cura%C3%A7ao_and_the_Caribbean_Netherlands')],
  '60': [('MY', 'Malaysia', 'https://en.wikipedia.org/wiki/Malaysia', 'https://en.wikipedia.org/wiki/%2B60')],
  '61': [ ('AU', 'Australia', 'https://en.wikipedia.org/wiki/Australia', 'https://en.wikipedia.org/wiki/%2B61'),
          ('CC', 'Cocos Islands', 'https://en.wikipedia.org/wiki/Cocos_Islands', 'https://en.wikipedia.org/wiki/%2B61'),
          ( 'CX',
            'Christmas Island',
            'https://en.wikipedia.org/wiki/Christmas_Island',
            'https://en.wikipedia.org/wiki/%2B61')],
  '62': [('ID', 'Indonesia', 'https://en.wikipedia.org/wiki/Indonesia', 'https://en.wikipedia.org/wiki/%2B62')],
  '63': [('PH', 'Philippines', 'https://en.wikipedia.org/wiki/Philippines', 'https://en.wikipedia.org/wiki/%2B63')],
  '64': [ ('NZ', 'New Zealand', 'https://en.wikipedia.org/wiki/New_Zealand', 'https://en.wikipedia.org/wiki/%2B64'),
          ( 'PN',
            'Pitcairn Islands',
            'https://en.wikipedia.org/wiki/Pitcairn_Islands',
            'https://en.wikipedia.org/wiki/%2B64')],
  '65': [('SG', 'Singapore', 'https://en.wikipedia.org/wiki/Singapore', 'https://en.wikipedia.org/wiki/%2B65')],
  '66': [('TH', 'Thailand', 'https://en.wikipedia.org/wiki/Thailand', 'https://en.wikipedia.org/wiki/%2B66')],
  '670': [('TL', 'East Timor', 'https://en.wikipedia.org/wiki/East_Timor', 'https://en.wikipedia.org/wiki/%2B670')],
  '672': [ ( 'AQ',
             'Australian Antarctic Territory',
             'https://en.wikipedia.org/wiki/Australian_Antarctic_Territory',
             'https://en.wikipedia.org/wiki/Telephone_numbers_in_Oceania'),
           ( 'HM',
             'Heard Island and McDonald Islands',
             'https://en.wikipedia.org/wiki/Heard_Island_and_McDonald_Islands',
             'https://en.wikipedia.org/wiki/Telephone_numbers_in_Oceania'),
           ( 'NF',
             'Norfolk Island',
             'https://en.wikipedia.org/wiki/Norfolk_Island',
             'https://en.wikipedia.org/wiki/Telephone_numbers_in_Oceania')],
  '673': [ ( 'BN',
             'Brunei Darussalam',
             'https://en.wikipedia.org/wiki/Brunei_Darussalam',
             'https://en.wikipedia.org/wiki/%2B673')],
  '674': [('NR', 'Nauru', 'https://en.wikipedia.org/wiki/Nauru', 'https://en.wikipedia.org/wiki/%2B674')],
  '675': [ ( 'PG',
             'Papua New Guinea',
             'https://en.wikipedia.org/wiki/Papua_New_Guinea',
             'https://en.wikipedia.org/wiki/%2B675')],
  '676': [('TO', 'Tonga', 'https://en.wikipedia.org/wiki/Tonga', 'https://en.wikipedia.org/wiki/%2B676')],
  '677': [ ( 'SB',
             'Solomon Islands',
             'https://en.wikipedia.org/wiki/Solomon_Islands',
             'https://en.wikipedia.org/wiki/%2B677')],
  '678': [('VU', 'Vanuatu', 'https://en.wikipedia.org/wiki/Vanuatu', 'https://en.wikipedia.org/wiki/%2B678')],
  '679': [('FJ', 'Fiji', 'https://en.wikipedia.org/wiki/Fiji', 'https://en.wikipedia.org/wiki/%2B679')],
  '680': [('PW', 'Palau', 'https://en.wikipedia.org/wiki/Palau', 'https://en.wikipedia.org/wiki/%2B680')],
  '681': [ ( 'WF',
             'Wallis and Futuna',
             'https://en.wikipedia.org/wiki/Wallis_and_Futuna',
             'https://en.wikipedia.org/wiki/%2B681')],
  '682': [('CK', 'Cook Islands', 'https://en.wikipedia.org/wiki/Cook_Islands', 'https://en.wikipedia.org/wiki/%2B682')],
  '683': [('NU', 'Niue', 'https://en.wikipedia.org/wiki/Niue', 'https://en.wikipedia.org/wiki/%2B683')],
  '685': [('WS', 'Samoa', 'https://en.wikipedia.org/wiki/Samoa', 'https://en.wikipedia.org/wiki/%2B685')],
  '686': [('KI', 'Kiribati', 'https://en.wikipedia.org/wiki/Kiribati', 'https://en.wikipedia.org/wiki/%2B686')],
  '687': [ ( 'NC',
             'New Caledonia',
             'https://en.wikipedia.org/wiki/New_Caledonia',
             'https://en.wikipedia.org/wiki/%2B687')],
  '688': [('TV', 'Tuvalu', 'https://en.wikipedia.org/wiki/Tuvalu', 'https://en.wikipedia.org/wiki/%2B688')],
  '689': [ ( 'PF',
             'French Polynesia',
             'https://en.wikipedia.org/wiki/French_Polynesia',
             'https://en.wikipedia.org/wiki/%2B689')],
  '690': [('TK', 'Tokelau', 'https://en.wikipedia.org/wiki/Tokelau', 'https://en.wikipedia.org/wiki/%2B690')],
  '691': [ ( 'FM',
             'Federated States of Micronesia',
             'https://en.wikipedia.org/wiki/Federated_States_of_Micronesia',
             'https://en.wikipedia.org/wiki/%2B691')],
  '692': [ ( 'MH',
             'Marshall Islands',
             'https://en.wikipedia.org/wiki/Marshall_Islands',
             'https://en.wikipedia.org/wiki/%2B692')],
  '7': [('RU', 'Russia', 'https://en.wikipedia.org/wiki/Russia', 'https://en.wikipedia.org/wiki/%2B7')],
  '73': [ ( 'RU',
            'Russia',
            'https://en.wikipedia.org/wiki/Russia',
            'https://en.wikipedia.org/wiki/Telephone_numbers_in_Russia')],
  '74': [ ( 'RU',
            'Russia',
            'https://en.wikipedia.org/wiki/Russia',
            'https://en.wikipedia.org/wiki/Telephone_numbers_in_Russia')],
  '76': [ ( 'KZ',
            'Kazakhstan',
            'https://en.wikipedia.org/wiki/Kazakhstan',
            'https://en.wikipedia.org/wiki/Telephone_numbers_in_Kazakhstan')],
  '77': [ ( 'KZ',
            'Kazakhstan',
            'https://en.wikipedia.org/wiki/Kazakhstan',
            'https://en.wikipedia.org/wiki/Telephone_numbers_in_Kazakhstan')],
  '78': [ ( 'RU',
            'Russia',
            'https://en.wikipedia.org/wiki/Russia',
            'https://en.wikipedia.org/wiki/Telephone_numbers_in_Russia')],
  '79': [ ( 'RU',
            'Russia',
            'https://en.wikipedia.org/wiki/Russia',
            'https://en.wikipedia.org/wiki/Telephone_numbers_in_Russia')],
  '81': [('JP', 'Japan', 'https://en.wikipedia.org/wiki/Japan', 'https://en.wikipedia.org/wiki/%2B81')],
  '82': [('KR', 'South Korea', 'https://en.wikipedia.org/wiki/South_Korea', 'https://en.wikipedia.org/wiki/%2B82')],
  '84': [('VN', 'Vietnam', 'https://en.wikipedia.org/wiki/Vietnam', 'https://en.wikipedia.org/wiki/%2B84')],
  '850': [('KP', 'North Korea', 'https://en.wikipedia.org/wiki/North_Korea', 'https://en.wikipedia.org/wiki/%2B850')],
  '852': [('HK', 'Hong Kong', 'https://en.wikipedia.org/wiki/Hong_Kong', 'https://en.wikipedia.org/wiki/%2B852')],
  '853': [('MO', 'Macau', 'https://en.wikipedia.org/wiki/Macau', 'https://en.wikipedia.org/wiki/%2B853')],
  '855': [('KH', 'Cambodia', 'https://en.wikipedia.org/wiki/Cambodia', 'https://en.wikipedia.org/wiki/%2B855')],
  '856': [('LA', 'Laos', 'https://en.wikipedia.org/wiki/Laos', 'https://en.wikipedia.org/wiki/%2B856')],
  '86': [('CN', 'China', 'https://en.wikipedia.org/wiki/China', 'https://en.wikipedia.org/wiki/%2B86')],
  '880': [ ( 'BD',
             'Bangladesh',
             'https://en.wikipedia.org/wiki/Bangladesh',
             'https://en.wikipedia.org/wiki/Telephone_numbers_in_Bangladesh')],
  '886': [('TW', 'Taiwan', 'https://en.wikipedia.org/wiki/Taiwan', 'https://en.wikipedia.org/wiki/%2B886')],
  '90': [ ( 'CT',
            'Northern Cyprus',
            'https://en.wikipedia.org/wiki/Northern_Cyprus',
            'https://en.wikipedia.org/wiki/%2B90'),
          ('TR', 'Turkey', 'https://en.wikipedia.org/wiki/Turkey', 'https://en.wikipedia.org/wiki/%2B90')],
  '91': [('IN', 'India', 'https://en.wikipedia.org/wiki/India', 'https://en.wikipedia.org/wiki/%2B91')],
  '92': [('PK', 'Pakistan', 'https://en.wikipedia.org/wiki/Pakistan', 'https://en.wikipedia.org/wiki/%2B92')],
  '93': [('AF', 'Afghanistan', 'https://en.wikipedia.org/wiki/Afghanistan', 'https://en.wikipedia.org/wiki/%2B93')],
  '94': [('LK', 'Sri Lanka', 'https://en.wikipedia.org/wiki/Sri_Lanka', 'https://en.wikipedia.org/wiki/%2B94')],
  '95': [('MM', 'Myanmar', 'https://en.wikipedia.org/wiki/Myanmar', 'https://en.wikipedia.org/wiki/%2B95')],
  '960': [('MV', 'Maldives', 'https://en.wikipedia.org/wiki/Maldives', 'https://en.wikipedia.org/wiki/%2B960')],
  '961': [('LB', 'Lebanon', 'https://en.wikipedia.org/wiki/Lebanon', 'https://en.wikipedia.org/wiki/%2B961')],
  '962': [('JO', 'Jordan', 'https://en.wikipedia.org/wiki/Jordan', 'https://en.wikipedia.org/wiki/%2B962')],
  '963': [('SY', 'Syria', 'https://en.wikipedia.org/wiki/Syria', 'https://en.wikipedia.org/wiki/%2B963')],
  '964': [('IQ', 'Iraq', 'https://en.wikipedia.org/wiki/Iraq', 'https://en.wikipedia.org/wiki/%2B964')],
  '965': [('KW', 'Kuwait', 'https://en.wikipedia.org/wiki/Kuwait', 'https://en.wikipedia.org/wiki/%2B965')],
  '966': [('SA', 'Saudi Arabia', 'https://en.wikipedia.org/wiki/Saudi_Arabia', 'https://en.wikipedia.org/wiki/%2B966')],
  '967': [('YE', 'Yemen', 'https://en.wikipedia.org/wiki/Yemen', 'https://en.wikipedia.org/wiki/%2B967')],
  '968': [('OM', 'Oman', 'https://en.wikipedia.org/wiki/Oman', 'https://en.wikipedia.org/wiki/%2B968')],
  '970': [ ( 'PS',
             'State of Palestine',
             'https://en.wikipedia.org/wiki/State_of_Palestine',
             'https://en.wikipedia.org/wiki/%2B970')],
  '971': [ ( 'AE',
             'United Arab Emirates',
             'https://en.wikipedia.org/wiki/United_Arab_Emirates',
             'https://en.wikipedia.org/wiki/%2B971')],
  '972': [ ( 'IL',
             'Israel',
             'https://en.wikipedia.org/wiki/Israel',
             'https://en.wikipedia.org/wiki/Telephone_numbers_in_Israel')],
  '973': [('BH', 'Bahrain', 'https://en.wikipedia.org/wiki/Bahrain', 'https://en.wikipedia.org/wiki/%2B973')],
  '974': [('QA', 'Qatar', 'https://en.wikipedia.org/wiki/Qatar', 'https://en.wikipedia.org/wiki/%2B974')],
  '975': [('BT', 'Bhutan', 'https://en.wikipedia.org/wiki/Bhutan', 'https://en.wikipedia.org/wiki/%2B975')],
  '976': [('MN', 'Mongolia', 'https://en.wikipedia.org/wiki/Mongolia', 'https://en.wikipedia.org/wiki/%2B976')],
  '977': [('NP', 'Nepal', 'https://en.wikipedia.org/wiki/Nepal', 'https://en.wikipedia.org/wiki/%2B977')],
  '98': [('IR', 'Iran', 'https://en.wikipedia.org/wiki/Iran', 'https://en.wikipedia.org/wiki/%2B98')],
  '992': [('TJ', 'Tajikistan', 'https://en.wikipedia.org/wiki/Tajikistan', 'https://en.wikipedia.org/wiki/%2B992')],
  '993': [('TM', 'Turkmenistan', 'https://en.wikipedia.org/wiki/Turkmenistan', 'https://en.wikipedia.org/wiki/%2B993')],
  '994': [('AZ', 'Azerbaijan', 'https://en.wikipedia.org/wiki/Azerbaijan', 'https://en.wikipedia.org/wiki/%2B994')],
  '995': [ ( 'GE',
             'Georgia (country)',
             'https://en.wikipedia.org/wiki/Georgia_(country)',
             'https://en.wikipedia.org/wiki/%2B995')],
  '996': [('KG', 'Kyrgyzstan', 'https://en.wikipedia.org/wiki/Kyrgyzstan', 'https://en.wikipedia.org/wiki/%2B996')],
  '997': [('KZ', 'Kazakhstan', 'https://en.wikipedia.org/wiki/Kazakhstan', 'https://en.wikipedia.org/wiki/%2B997')],
  '998': [('UZ', 'Uzbekistan', 'https://en.wikipedia.org/wiki/Uzbekistan', 'https://en.wikipedia.org/wiki/%2B998')]}
