# -*- coding: UTF-8 -*-
# source: https://en.wikipedia.org/wiki/List_of_country_calling_codes
# license: https://en.wikipedia.org/wiki/Wikipedia:Text_of_Creative_Commons_Attribution-ShareAlike_3.0_Unported_License

WIKIP_TERRITORY = \
{ 'Almirante Brown Antarctic Base': ('54', 'Argentina', 'https://en.wikipedia.org/wiki/Almirante_Brown_Antarctic_Base'),
  'Amundsen–Scott South Pole Station': ( '1',
                                         'United States',
                                         'https://en.wikipedia.org/wiki/Amundsen%E2%80%93Scott_South_Pole_Station'),
  'Artigas Base': ('598', 'Uruguay', 'https://en.wikipedia.org/wiki/Artigas_Base'),
  'Asuka Station': ('81', 'Japan', 'https://en.wikipedia.org/wiki/Asuka_Station_(Antarctica)'),
  'Base Presidente Eduardo Frei Montalva': ( '56',
                                             'Chile',
                                             'https://en.wikipedia.org/wiki/Base_Presidente_Eduardo_Frei_Montalva'),
  'Belgrano II': ('54', 'Argentina', 'https://en.wikipedia.org/wiki/General_Belgrano_II'),
  'Bellingshausen Station': ('7', 'Russia', 'https://en.wikipedia.org/wiki/Bellingshausen_Station'),
  "Bernardo O'Higgins Station": ( '56',
                                  'Chile',
                                  'https://en.wikipedia.org/wiki/Base_General_Bernardo_O%27Higgins_Riquelme'),
  'Byrd Station': ('1', 'United States', 'https://en.wikipedia.org/wiki/Byrd_Station'),
  'Captain Arturo Prat Base': ('56', 'Chile', 'https://en.wikipedia.org/wiki/Captain_Arturo_Prat_Base'),
  'Casey Station': ('672', 'Australia', 'https://en.wikipedia.org/wiki/Casey_Station'),
  'Comandante Ferraz Brazilian Antarctic Base': ( '55',
                                                  'Brazil',
                                                  'https://en.wikipedia.org/wiki/Comandante_Ferraz_Brazilian_Antarctic_Base'),
  'Concordia Station': ('39', 'Italy', 'https://en.wikipedia.org/wiki/Concordia_Station'),
  'Davis Station': ('672', 'Australia', 'https://en.wikipedia.org/wiki/Davis_Station'),
  'Dome Fuji Station': ('81', 'Japan', 'https://en.wikipedia.org/wiki/Dome_F'),
  "Dumont d'Urville Station": ('33', 'France', 'https://en.wikipedia.org/wiki/Dumont_d%27Urville_Station'),
  'Esperanza Base': ('54', 'Argentina', 'https://en.wikipedia.org/wiki/Esperanza_Base'),
  'Gabriel de Castilla Spanish Antarctic Station': ( '34',
                                                     'Spain',
                                                     'https://en.wikipedia.org/wiki/Gabriel_de_Castilla_Spanish_Antarctic_Station'),
  'Georg-von-Neumayer-Station': ('49', 'Germany', 'https://en.wikipedia.org/wiki/Georg-von-Neumayer-Station'),
  'Gonzalez Videla Station': ('56', 'Chile', 'https://en.wikipedia.org/wiki/Gonzalez_Videla_Station'),
  'Great Wall Station': ('86', 'China', 'https://en.wikipedia.org/wiki/Great_Wall_Station'),
  'Halley Research Station': ('44', 'United Kingdom', 'https://en.wikipedia.org/wiki/Halley_Research_Station'),
  'Henryk Arctowski Polish Antarctic Station': ( '48',
                                                 'Poland',
                                                 'https://en.wikipedia.org/wiki/Henryk_Arctowski_Polish_Antarctic_Station'),
  'Jang Bogo Station': ('82', 'South Korea', 'https://en.wikipedia.org/wiki/Jang_Bogo_Station'),
  'Jinnah Antarctic Station': ('92', 'Pakistan', 'https://en.wikipedia.org/wiki/Jinnah_Antarctic_Station'),
  'Juan Carlos I Base': ('34', 'Spain', 'https://en.wikipedia.org/wiki/Juan_Carlos_I_Base'),
  'Jubany': ('54', 'Argentina', 'https://en.wikipedia.org/wiki/Jubany'),
  'King Sejong Station': ('82', 'South Korea', 'https://en.wikipedia.org/wiki/King_Sejong_Station'),
  'Kohnen-Station': ( '49',
                      'Germany',
                      'https://en.wikipedia.org/wiki/European_Project_for_Ice_Coring_in_Antarctica#Kohnen_Station,_Dronning_Maud_Land'),
  'Kunlun Station': ('852', 'China', 'https://en.wikipedia.org/wiki/Kunlun_Station'),
  'Law-Racoviţă Station': ('40', 'Romania', 'https://en.wikipedia.org/wiki/Law-Racovi%C5%A3%C4%83_Station'),
  'Leningradskaya Station': ('7', 'Russia', 'https://en.wikipedia.org/wiki/Leningradskaya_Station'),
  'Machu Picchu Research Station': ('51', 'Peru', 'https://en.wikipedia.org/wiki/Machu_Picchu_Research_Station'),
  'Macquarie Island Station': ('672', 'Australia', 'https://en.wikipedia.org/wiki/Macquarie_Island_Station'),
  'Maitri Station': ('91', 'India', 'https://en.wikipedia.org/wiki/Maitri_(research_station)'),
  'Marambio Base': ('54', 'Argentina', 'https://en.wikipedia.org/wiki/Marambio_Base'),
  'Mario Zucchelli Station': ('39', 'Italy', 'https://en.wikipedia.org/wiki/Zucchelli_Station'),
  'Mawson Station': ('672', 'Australia', 'https://en.wikipedia.org/wiki/Mawson_Station'),
  'McMurdo Station': ('1', 'United States', 'https://en.wikipedia.org/wiki/McMurdo_Station'),
  'Mendel Polar Station': ('420', 'Czech Republic', 'https://en.wikipedia.org/wiki/Mendel_Polar_Station'),
  'Mirny Station': ('7', 'Russia', 'https://en.wikipedia.org/wiki/Mirny_Station'),
  'Mizuho Station': ('81', 'Japan', 'https://en.wikipedia.org/wiki/Mizuho_Station_(Antarctica)'),
  'Molodyozhnaya Station': ('7', 'Russia', 'https://en.wikipedia.org/wiki/Molodyozhnaya_Station_(Antarctica)'),
  'Neumayer Station': ('49', 'Germany', 'https://en.wikipedia.org/wiki/Neumayer_Station'),
  'Novolazarevskaya Station': ('7', 'Russia', 'https://en.wikipedia.org/wiki/Novolazarevskaya_Station'),
  'Orcadas Base': ('54', 'Argentina', 'https://en.wikipedia.org/wiki/Orcadas_Base'),
  'Palmer Station': ('1', 'United States', 'https://en.wikipedia.org/wiki/Palmer_Station'),
  'Princess Elisabeth Base': ('32', 'Belgium', 'https://en.wikipedia.org/wiki/Princess_Elisabeth_Base'),
  'Professor Julio Escudero Base': ('56', 'Chile', 'https://en.wikipedia.org/wiki/Professor_Julio_Escudero_Base'),
  'Progress Station': ('7', 'Russia', 'https://en.wikipedia.org/wiki/Progress_Station'),
  'Rothera Research Station': ('44', 'United Kingdom', 'https://en.wikipedia.org/wiki/Rothera_Research_Station'),
  'Russkaya Station': ('7', 'Russia', 'https://en.wikipedia.org/wiki/Russkaya_Station'),
  'SANAE IV': ('27', 'South Africa', 'https://en.wikipedia.org/wiki/SANAE_IV'),
  'San Martín Base': ('54', 'Argentina', 'https://en.wikipedia.org/wiki/San_Mart%C3%ADn_Base'),
  'Scott Base': ('64', 'New Zealand', 'https://en.wikipedia.org/wiki/Scott_Base'),
  'Showa Station': ('81', 'Japan', 'https://en.wikipedia.org/wiki/Showa_Station_(Antarctica)'),
  'Signy Research Station': ('44', 'United Kingdom', 'https://en.wikipedia.org/wiki/Signy_Research_Station'),
  'St. Kliment Ohridski Base': ('359', 'Bulgaria', 'https://en.wikipedia.org/wiki/St._Kliment_Ohridski_Base'),
  'Svea': ('46', 'Sweden', 'https://en.wikipedia.org/wiki/Svea_Research_Station'),
  'Tor Station': ('47', 'Norway', 'https://en.wikipedia.org/wiki/Tor_(research_station)'),
  'Troll Station': ('47', 'Norway', 'https://en.wikipedia.org/wiki/Troll_(research_station)'),
  'Vernadsky Research Base': ('380', 'Ukraine', 'https://en.wikipedia.org/wiki/Vernadsky_Research_Base'),
  'Vostok Station': ('7', 'Russia', 'https://en.wikipedia.org/wiki/Vostok_Station'),
  'Wasa Research Station': ('46', 'Sweden', 'https://en.wikipedia.org/wiki/Wasa_Research_Station'),
  'Zhongshan (Sun Yat-Sen) Station': ('86', 'China', 'https://en.wikipedia.org/wiki/Sun_Yat-Sen_Station')}
